const RAFSI: Map<string, string[]> = new Map([
  ["babda", []],
  ["bablo", []],
  ["backi", []],
  ["bacru", ["ba'u"]],
  ["badji", []],
  ["badna", []],
  ["badri", ['dri']],
  ["bajra", ['baj']],
  ["bakfu", ['baf']],
  ["bakni", ['bak']],
  ["bakri", []],
  ["baktu", []],
  ["balji", []],
  ["balni", []],
  ["balre", ["ba'e"]],
  ["balto", []],
  ["balvi", ['bav']],
  ["bambu", []],
  ["bancu", ['bac']],
  ["bandu", ['bad']],
  ["banfi", []],
  ["bangu", ['ban', 'bau']],
  ["banli", ['bal', "ba'i"]],
  ["banro", ["ba'o"]],
  ["banxa", ['bax']],
  ["banzu", ['baz']],
  ["bapli", ['bap', 'bai']],
  ["barda", ['bra']],
  ["bargu", ['bag']],
  ["barja", []],
  ["barna", ["ba'a"]],
  ["bartu", ['bar']],
  ["basfa", []],
  ["basna", []],
  ["basti", ['bas']],
  ["batci", ['bat']],
  ["batke", []],
  ["bavmi", []],
  ["bavza", []],
  ["baxso", []],
  ["bebna", ['beb']],
  ["bekpi", []],
  ["belta", []],
  ["bemro", ['bem', "be'o"]],
  ["bende", ['bed', "be'e"]],
  ["bengo", ['beg']],
  ["benji", ["be'i", 'bej']],
  ["benre", []],
  ["benzo", []],
  ["bergu", []],
  ["bersa", ["be'a", 'bes']],
  ["berti", ['ber']],
  ["besna", ['ben']],
  ["besto", []],
  ["betfu", ['bef', "be'u"]],
  ["betka", []],
  ["betri", ['bet']],
  ["bevri", ['bei', 'bev']],
  ["bi", ['biv']],
  ["bidju", []],
  ["bifce", ['bic']],
  ["bi'i", ['biz']],
  ["bikla", ['bik']],
  ["bilbo", []],
  ["bilga", ['big']],
  ["bilma", ["bi'a"]],
  ["bilni", ['bil']],
  ["bindo", ['bid']],
  ["binra", []],
  ["binxo", ['bix', "bi'o"]],
  ["birje", []],
  ["birka", ['bir']],
  ["birti", ['bit']],
  ["bisli", ['bis']],
  ["bitmu", ["bi'u", 'bim']],
  ["bitni", []],
  ["blabi", ['lab']],
  ["blaci", []],
  ["blanu", ['bla']],
  ["bliku", ['bli']],
  ["blina", []],
  ["blolo", []],
  ["bloti", ['lot', 'blo', "lo'i"]],
  ["bluji", []],
  ["bo", ['bor']],
  ["bolci", ['bol', 'boi']],
  ["bongu", ["bo'u", 'bog']],
  ["boske", []],
  ["botpi", ["bo'i", 'bot']],
  ["boxfo", ["bo'o", 'bof']],
  ["boxna", ["bo'a", 'bon']],
  ["bradi", []],
  ["brano", []],
  ["bratu", []],
  ["bravi", []],
  ["brazo", ['raz']],
  ["bredi", ['red', 'bre']],
  ["bridi", ['bri']],
  ["brife", ["bi'e", 'bif']],
  ["briju", ['bij']],
  ["brito", ['rit']],
  ["brivo", []],
  ["broda", ['rod']],
  ["brode", ["bo'e"]],
  ["brodi", []],
  ["brodo", []],
  ["brodu", []],
  ["bruna", ["bu'a", 'bun']],
  ["bu", ["bu'i", 'bus']],
  ["bu'a", ['bul']],
  ["budjo", ['buj', "bu'o"]],
  ["budza", []],
  ["bukpu", ['buk', "bu'u"]],
  ["bumru", ['bum']],
  ["bunda", ['bud']],
  ["bunre", ['bur', "bu'e"]],
  ["buntu", []],
  ["bunxa", []],
  ["burcu", ['bru']],
  ["burka", []],
  ["burna", []],
  ["buvla", []],
  ["ca'a", ['caz']],
  ["cabna", ['cab']],
  ["cabra", ["ca'a"]],
  ["cacra", []],
  ["cadga", []],
  ["cadma", []],
  ["cadzu", ['dzu']],
  ["cafne", ['caf']],
  ["cagna", []],
  ["cajni", []],
  ["cakla", []],
  ["calku", ['cak']],
  ["calse", []],
  ["campu", []],
  ["canci", []],
  ["cando", ['cad']],
  ["cange", ['cag']],
  ["canja", ['caj']],
  ["canko", ["ca'o"]],
  ["canlu", ["ca'u", 'cal']],
  ["canma", []],
  ["canpa", ['cna']],
  ["canre", ['can']],
  ["canti", []],
  ["carce", []],
  ["carfu", []],
  ["carmi", ['cai', 'cam']],
  ["carna", ['car']],
  ["cartu", ['cat']],
  ["carvi", ['cav']],
  ["casnu", ['snu']],
  ["catke", ["ca'e"]],
  ["catlu", ['cta']],
  ["catni", ["ca'i"]],
  ["catra", []],
  ["caxno", ['cax']],
  ["ce", ['cec']],
  ["cecla", ["ce'a", 'cel']],
  ["cecmu", ['cem', "ce'u"]],
  ["cedra", []],
  ["ce'i", ['cez']],
  ["celdi", ['cle']],
  ["celxa", []],
  ["cenba", ['cne']],
  ["cendo", []],
  ["censa", ['ces']],
  ["centi", ['cen']],
  ["ce'o", ["ce'o"]],
  ["cerda", ['ced']],
  ["cerni", ['cer']],
  ["certu", ['cre']],
  ["cevni", ['cev', 'cei']],
  ["cfale", []],
  ["cfari", ['cfa']],
  ["cfika", ["fi'a", 'fik']],
  ["cfila", ['cfi']],
  ["cfine", []],
  ["cfipu", ["fi'u"]],
  ["ci", ['cib']],
  ["ciblu", ['blu']],
  ["cicna", []],
  ["cidja", ['dja']],
  ["cidni", ['cid']],
  ["cidro", ['dro']],
  ["cifnu", ['cif']],
  ["cigla", ['cig']],
  ["cikna", ['cik']],
  ["cikre", []],
  ["ciksi", ['cki']],
  ["cilce", ['cic']],
  ["cilfu", []],
  ["cilmo", ['cim']],
  ["cilre", ['cli']],
  ["cilta", ['cil']],
  ["cimde", []],
  ["cimle", []],
  ["cimni", []],
  ["cinba", []],
  ["cindu", []],
  ["cinfo", []],
  ["cinje", ['cij']],
  ["cinki", []],
  ["cinla", []],
  ["cinmo", ['cni']],
  ["cinri", ["ci'i"]],
  ["cinse", ['cin']],
  ["cinta", []],
  ["cinza", []],
  ["cipni", ['cpi']],
  ["cipra", ['cip']],
  ["cirko", ['cri']],
  ["cirla", []],
  ["ciska", ["ci'a"]],
  ["cisma", []],
  ["cisni", []],
  ["ciste", ["ci'e"]],
  ["citka", ['cti']],
  ["citno", ['cit', "ci'o"]],
  ["citri", ['cir']],
  ["citsi", []],
  ["civla", ['civ']],
  ["cizra", ['ciz']],
  ["ckabu", []],
  ["ckafi", ['kaf']],
  ["ckaji", ['kai']],
  ["ckana", ['cka']],
  ["ckape", ['cap']],
  ["ckasu", ['cas']],
  ["ckeji", ['cke', 'kej']],
  ["ckiku", ['kik']],
  ["ckilu", ["ci'u"]],
  ["ckini", ["ki'i"]],
  ["ckire", ['kir']],
  ["ckule", ["cu'e", 'kul']],
  ["ckunu", ["ku'u"]],
  ["cladu", ['lau']],
  ["clafi", []],
  ["clani", ['cla']],
  ["claxu", ['cau']],
  ["clenu", []],
  ["cletu", []],
  ["clika", []],
  ["clinu", []],
  ["clira", ['lir']],
  ["clite", ['lit']],
  ["cliva", ['liv', "li'a"]],
  ["clupa", ['cup']],
  ["cmaci", []],
  ["cmalu", ['cma']],
  ["cmana", ["ma'a"]],
  ["cmavo", ["ma'o"]],
  ["cmene", ["me'e", 'cme']],
  ["cmeta", []],
  ["cmevo", []],
  ["cmila", ["mi'a"]],
  ["cmima", ['mim', 'cmi']],
  ["cmoni", ['cmo', "co'i"]],
  ["cnano", ["na'o"]],
  ["cnata", []],
  ["cnebo", ['neb', "ne'o"]],
  ["cnemu", ["ne'u", 'nem']],
  ["cnici", ['nic']],
  ["cnida", []],
  ["cnino", ["ni'o", 'nin']],
  ["cnisa", ['nis']],
  ["cnita", ['nit', "ni'a"]],
  ["co", ['col']],
  ["co'a", ["co'a"]],
  ["co'e", ['com', "co'e"]],
  ["cokcu", ['cko']],
  ["cokte", []],
  ["condi", ['coi', 'cno', 'con']],
  ["conka", []],
  ["corci", ['coc']],
  ["cortu", ['cro', 'cor']],
  ["cotci", []],
  ["co'u", ["co'u"]],
  ["cpacu", ['cpa']],
  ["cpana", []],
  ["cpare", ['par']],
  ["cpedu", ['cpe']],
  ["cpina", []],
  ["cpixa", []],
  ["cradi", []],
  ["crami", []],
  ["crane", ['cra']],
  ["cravi", []],
  ["creka", ['cek']],
  ["crepu", ['rep']],
  ["cribe", ['rib']],
  ["crida", ['rid']],
  ["crino", ["ri'o"]],
  ["cripu", ['rip']],
  ["crisa", ['cis']],
  ["critu", []],
  ["ctaru", []],
  ["ctebi", ['teb']],
  ["cteki", ['tek', "ce'i"]],
  ["ctera", []],
  ["ctile", []],
  ["ctino", ["ti'o"]],
  ["ctuca", ['ctu']],
  ["cukla", ['cuk']],
  ["cukre", []],
  ["cukta", ['cku']],
  ["culno", ['clu']],
  ["cumba", []],
  ["cumki", ['cum', "cu'i"]],
  ["cumla", ['cul']],
  ["cunmi", []],
  ["cunso", ["cu'o", 'cun']],
  ["cuntu", ["cu'u"]],
  ["cupra", ['pra']],
  ["curmi", ['cru']],
  ["curnu", ['cur']],
  ["curve", ['cuv']],
  ["cusku", ['cus', 'sku']],
  ["cusna", []],
  ["cutci", ['cuc']],
  ["cutne", ['cut']],
  ["cuxna", ["cu'a", 'cux']],
  ["da", ['dza', 'dav']],
  ["da'a", ['daz']],
  ["dacru", ['dac']],
  ["dacti", ['dai']],
  ["dadjo", ['daj']],
  ["dajbu", []],
  ["dajne", []],
  ["dakfu", ['dak']],
  ["dakli", []],
  ["damba", ["da'a", 'dab']],
  ["damri", []],
  ["danci", []],
  ["dandu", ['dad']],
  ["danfu", ['daf']],
  ["danke", []],
  ["danlu", ["da'u", 'dal']],
  ["danmo", ['dam']],
  ["danre", ["da'e"]],
  ["dansu", []],
  ["danti", ['dan']],
  ["daplu", ['plu']],
  ["dapma", ['dap']],
  ["darca", []],
  ["dardu", []],
  ["dargu", ['dag']],
  ["darlu", ['dau']],
  ["darno", ["da'o", 'dar']],
  ["darsi", []],
  ["darxi", ['dax', "da'i"]],
  ["daski", []],
  ["dasni", ['das']],
  ["daspo", ['spo']],
  ["dasri", ['sri']],
  ["datca", []],
  ["datka", []],
  ["datni", []],
  ["datro", []],
  ["datru", []],
  ["datxo", []],
  ["decti", ['dec']],
  ["degji", ['deg']],
  ["dejni", ['dej']],
  ["dekpu", []],
  ["dekto", ['dek']],
  ["delca", []],
  ["delno", ["de'o", 'del']],
  ["delta", []],
  ["dembi", ['deb']],
  ["denci", ["de'i", 'den']],
  ["dendi", []],
  ["denmi", ['dem']],
  ["denpa", ['dep', "de'a"]],
  ["dertu", ["de'u", 'der']],
  ["derxi", ['dre']],
  ["desku", ['des']],
  ["detri", ['det']],
  ["dicma", []],
  ["dicra", ['dir']],
  ["didni", []],
  ["digno", []],
  ["dikca", ['dic']],
  ["diklo", ['klo']],
  ["dikni", ['dik']],
  ["dilcu", []],
  ["dildo", []],
  ["dilma", []],
  ["dilnu", ['dil']],
  ["dimna", ['dim']],
  ["dindi", []],
  ["dinju", ["di'u", 'dij']],
  ["dinko", ["di'o"]],
  ["dinso", ['dis']],
  ["dinti", []],
  ["dirba", ['dib']],
  ["dirce", ["di'e"]],
  ["dirgo", ['dig']],
  ["disko", []],
  ["ditcu", ['dit']],
  ["divzi", []],
  ["dizlo", ['dzi', 'diz']],
  ["djacu", ['jau', 'jac']],
  ["djedi", ['dje', 'dei']],
  ["djica", ['dji']],
  ["djika", []],
  ["djine", ['jin']],
  ["djuno", ["ju'o", 'jun']],
  ["do", ['don', 'doi']],
  ["dolna", ['dol']],
  ["donri", ['dor', "do'i"]],
  ["dotco", ['dot', "do'o"]],
  ["draci", []],
  ["drani", ['dra']],
  ["drata", ['dat']],
  ["drisu", []],
  ["drudi", ['rud', 'dru']],
  ["du", ['dub', "du'o"]],
  ["dugri", ['dug']],
  ["dukni", []],
  ["dukse", ['dus', "du'e"]],
  ["dukti", ['dut']],
  ["dunda", ["du'a", 'dud']],
  ["dunja", ['duj']],
  ["dunku", ['duk', "du'u"]],
  ["dunli", ['dun', "du'i"]],
  ["dunra", ['dur']],
  ["durna", []],
  ["dutso", ['tso']],
  ["du'u", ['dum']],
  ["dzama", []],
  ["dzena", ['dze']],
  ["dzipo", ['zip', "zi'o"]],
  ["dzoli", ['dzo']],
  ["facki", ["fa'i", 'fak']],
  ["facni", []],
  ["fadni", ['fad']],
  ["fagri", ['fag']],
  ["falnu", ['fan']],
  ["famti", []],
  ["fancu", []],
  ["fange", []],
  ["fanji", []],
  ["fanmo", ["fa'o", 'fam']],
  ["fanri", []],
  ["fanta", []],
  ["fanva", []],
  ["fanza", ['faz']],
  ["fapro", ['fap', 'pro']],
  ["fardu", []],
  ["farka", []],
  ["farlu", ['fal', "fa'u"]],
  ["farna", ["fa'a", 'far']],
  ["farvi", ['fav']],
  ["fasnu", ['fau']],
  ["fatci", ['fac']],
  ["fatne", ['fat', "fa'e"]],
  ["fatri", ['fai']],
  ["febvi", ['feb']],
  ["fegli", []],
  ["femti", ['fem']],
  ["fendi", ['fed']],
  ["fenfa", []],
  ["fengu", ['feg', "fe'u"]],
  ["fenki", ['fek']],
  ["fenra", ["fe'a", 'fer']],
  ["fenso", ["fe'o", 'fen']],
  ["fepni", ['fei', 'fep']],
  ["fepri", []],
  ["ferti", ['fre']],
  ["festi", ['fes']],
  ["fetsi", ['fet', "fe'i"]],
  ["fibra", []],
  ["fidna", ['fid']],
  ["figre", ['fig']],
  ["filso", ['fis']],
  ["finpe", ['fip', "fi'e"]],
  ["finti", ["fi'i", 'fin']],
  ["firca", []],
  ["fisli", []],
  ["fizbu", []],
  ["fizde", ['fiz']],
  ["flaci", []],
  ["flalu", ['fla']],
  ["flani", []],
  ["flecu", ['fle']],
  ["flese", ['les']],
  ["fliba", ['fli']],
  ["flipo", []],
  ["flira", ['fir']],
  ["fo'a", ["fo'a"]],
  ["fo'e", ["fo'e"]],
  ["fo'i", ["fo'i"]],
  ["foldi", ['flo', 'foi']],
  ["fonmo", ['fom', "fo'o"]],
  ["fonxa", ['fon']],
  ["forca", ['fro']],
  ["forse", []],
  ["fraso", ['fas']],
  ["frati", ['fra']],
  ["fraxu", ['fax']],
  ["frica", ['fic']],
  ["friko", ["fi'o"]],
  ["frili", ['fil']],
  ["frinu", []],
  ["friti", ['fit']],
  ["frumu", ['fru']],
  ["fugvo", []],
  ["fukpi", ["fu'i", 'fuk']],
  ["fulta", ['flu', 'ful']],
  ["funca", ["fu'a", 'fun']],
  ["fusra", ['fur']],
  ["fuvla", []],
  ["fuzme", ['fuz', "fu'e"]],
  ["gacri", ['gai']],
  ["gadri", ['gad']],
  ["galfi", ["ga'i", 'gaf']],
  ["galki", []],
  ["galtu", ["ga'u", 'gal']],
  ["galxe", []],
  ["ganda", []],
  ["ganlo", ["ga'o"]],
  ["ganra", ['gan']],
  ["ganse", ["ga'e", 'gas']],
  ["ganti", []],
  ["ganvi", []],
  ["ganxo", ['gax']],
  ["ganzu", ['gaz']],
  ["gapci", ['gac']],
  ["gapru", ['gap']],
  ["garna", ['gar']],
  ["gasnu", ['gau']],
  ["gaspo", []],
  ["gasta", ['gat']],
  ["genja", ['gej']],
  ["gento", ["ge'o", 'get']],
  ["genxu", ['gex']],
  ["gerku", ["ge'u", 'ger']],
  ["gerna", ["ge'a", 'gen']],
  ["gicmu", []],
  ["gidva", ['gid', "gi'a"]],
  ["gigdo", ["gi'o", 'gig']],
  ["ginka", ['gik']],
  ["girzu", ['gir', 'gri']],
  ["gismu", ['gim', "gi'u"]],
  ["glare", ['gla']],
  ["gleki", ['gek', 'gei']],
  ["gletu", ['let', 'gle']],
  ["glico", ['gic', 'gli']],
  ["glife", []],
  ["glosa", []],
  ["gluta", ['glu']],
  ["gocti", ['goc']],
  ["gomsi", []],
  ["gonte", []],
  ["gotro", ['got']],
  ["gradu", ['rau']],
  ["grafu", []],
  ["grake", ['gra']],
  ["grame", []],
  ["grana", ["ga'a"]],
  ["grasu", ['ras']],
  ["grava", ['gav']],
  ["greku", ['rek']],
  ["grusi", ['rus']],
  ["grute", ['rut']],
  ["gubni", ['gub']],
  ["gugde", ['gug', "gu'e"]],
  ["gugle", []],
  ["gumri", []],
  ["gundi", ['gud']],
  ["gunka", ["gu'a", 'gun']],
  ["gunma", ['gum']],
  ["gunro", ['gur', "gu'o"]],
  ["gunse", []],
  ["gunta", ['gut']],
  ["gurni", ['gru']],
  ["guska", ['guk']],
  ["gusni", ["gu'i", 'gus']],
  ["gusta", []],
  ["gutci", ['guc']],
  ["gutra", []],
  ["guzme", ['zme', 'guz']],
  ["ja", ['jav']],
  ["jabre", []],
  ["jadni", ['jad', "ja'i"]],
  ["jai", ['jax']],
  ["jakne", []],
  ["jaldi", []],
  ["jalge", ["ja'e", 'jag']],
  ["jalna", []],
  ["jalra", []],
  ["jamfu", ['jaf', 'jma']],
  ["jamna", ['jam']],
  ["janbe", ['jab']],
  ["janco", ['jan']],
  ["janli", ['jal']],
  ["jansu", ['jas']],
  ["janta", ['jat']],
  ["jarbu", []],
  ["jarco", ["ja'o"]],
  ["jarki", ['jak']],
  ["jaspu", ['jap']],
  ["jatna", ["ja'a"]],
  ["jatsu", []],
  ["javni", ['jva']],
  ["jbama", ['bam']],
  ["jbari", ['jba']],
  ["jbena", ['jbe']],
  ["jbera", ['jer']],
  ["jbini", ['bin', "bi'i"]],
  ["jbobo", []],
  ["jdari", ['jar']],
  ["jdice", ['jdi']],
  ["jdika", []],
  ["jdima", ["di'a"]],
  ["jdini", ['din', "di'i"]],
  ["jduli", ['dul', 'jdu']],
  ["je", ['jve', 'jev']],
  ["jecta", ["je'a", 'jec']],
  ["jeftu", ['jef']],
  ["jegvo", ['jeg', "je'o"]],
  ["jei", ['jez']],
  ["jelca", ['jel']],
  ["jemna", ['jme']],
  ["jenca", ['jen']],
  ["jendu", ['jed']],
  ["jenje", []],
  ["jenmi", ['jem', 'jei']],
  ["jensi", []],
  ["jerna", []],
  ["jersi", ["je'i"]],
  ["jerxo", ['jex']],
  ["jesni", ['jes']],
  ["jetce", ["je'e"]],
  ["jetnu", ['jet', "je'u"]],
  ["jgalu", ["ja'u"]],
  ["jganu", ['jga']],
  ["jgari", ['jai']],
  ["jgena", ['jge']],
  ["jgina", ['gin']],
  ["jgira", ['jgi']],
  ["jgita", ['git']],
  ["jguvi", []],
  ["jibni", ['jbi']],
  ["jibri", ['jib']],
  ["jicfo", []],
  ["jicla", []],
  ["jicmu", ['cmu']],
  ["jidge", ['jid']],
  ["jijgi", []],
  ["jijnu", ['jij']],
  ["jikca", ['jik']],
  ["jikfi", []],
  ["jikni", []],
  ["jikru", []],
  ["jilka", ['jil']],
  ["jilra", []],
  ["jimca", ['jic']],
  ["jimpe", ['jmi']],
  ["jimte", ['jit']],
  ["jinci", []],
  ["jinda", []],
  ["jinga", ["ji'a", 'jig']],
  ["jinku", []],
  ["jinme", ['jim']],
  ["jinru", ['jir']],
  ["jinsa", ['jis']],
  ["jinto", []],
  ["jinvi", ['jiv', "ji'i"]],
  ["jinzi", ['jiz']],
  ["jipci", []],
  ["jipno", ['jip', "ji'o"]],
  ["jirna", []],
  ["jisra", []],
  ["jitfa", ['jif']],
  ["jitni", []],
  ["jitro", ['tro']],
  ["jivbu", []],
  ["jivna", ['jvi']],
  ["jmaji", ['jaj']],
  ["jmice", []],
  ["jmifa", []],
  ["jmina", ['min']],
  ["jmite", []],
  ["jmive", ["ji'e", 'miv']],
  ["jo", ['jov']],
  ["jo'e", ['jom']],
  ["joi", ['jol', 'joi']],
  ["jonse", ['jos']],
  ["jordo", ["jo'o", 'jor']],
  ["jorne", ["jo'e", 'jon']],
  ["jo'u", ["jo'u"]],
  ["ju", ['juv']],
  ["jubme", ['jub', 'jbu']],
  ["judri", []],
  ["jufra", ["ju'a", 'juf']],
  ["jukni", ['juk']],
  ["jukpa", ['jup']],
  ["julne", ["ju'e"]],
  ["julro", []],
  ["jundi", ["ju'i", 'jud']],
  ["jungo", ['jug']],
  ["junla", ['jul']],
  ["junri", ['jur']],
  ["junta", []],
  ["jurme", ['jum']],
  ["jursa", ['jus']],
  ["jutsi", ['jut']],
  ["juxre", ['jux']],
  ["jvinu", ["ji'u", 'vin']],
  ["jviso", []],
  ["ka", ['kam']],
  ["kabri", []],
  ["kacma", []],
  ["kadno", []],
  ["kafke", []],
  ["kagni", ['kag']],
  ["kajde", ['jde']],
  ["kajna", []],
  ["kakne", ["ka'e"]],
  ["kakpa", []],
  ["kakti", []],
  ["kalci", []],
  ["kalri", ['kar']],
  ["kalsa", ['kas']],
  ["kalte", ['kat']],
  ["kamju", []],
  ["kamni", []],
  ["kampu", ['kau']],
  ["kamre", []],
  ["kamro", []],
  ["kanba", []],
  ["kancu", ['kac']],
  ["kandi", ['kad']],
  ["kanji", ['kaj']],
  ["kanla", ['kal']],
  ["kanpe", []],
  ["kanro", ["ka'o"]],
  ["kansa", ['kan']],
  ["kantu", ["ka'u"]],
  ["kanxe", ['kax']],
  ["kapli", []],
  ["kapsi", []],
  ["karbi", ['kab']],
  ["karce", []],
  ["karda", []],
  ["kargu", []],
  ["karli", []],
  ["karmo", []],
  ["karni", []],
  ["karpa", []],
  ["katci", []],
  ["katna", ["ka'a"]],
  ["katso", []],
  ["kavbu", ['kav']],
  ["kavzi", []],
  ["kazmi", []],
  ["kazra", ['kaz']],
  ["ke", ['kem']],
  ["kebzo", []],
  ["kecti", ['kec', "ke'i"]],
  ["ke'e", ['kep', "ke'e"]],
  ["kei", ['kez']],
  ["kekli", ['kek']],
  ["kekti", []],
  ["kelci", ['kei', 'kel']],
  ["kelto", []],
  ["kelvo", ["ke'o"]],
  ["kenka", []],
  ["kenra", ['ken']],
  ["kensa", ['kes']],
  ["kerfa", ['kre']],
  ["kerlo", ['ker']],
  ["kerni", []],
  ["kesfi", []],
  ["kesri", []],
  ["ketco", ['tco', 'ket']],
  ["ketli", []],
  ["ketro", []],
  ["ketsu", []],
  ["kevna", ["ke'a", 'kev']],
  ["kibro", ['kib']],
  ["kicne", ["ki'e", 'kic']],
  ["kicra", []],
  ["kijno", ['kij']],
  ["kilto", ["ki'o"]],
  ["kinda", []],
  ["kinfi", []],
  ["kinli", ['kil']],
  ["kinmu", []],
  ["kinra", []],
  ["kipsi", []],
  ["kisto", ['kis']],
  ["klaji", ['laj']],
  ["klaku", ['kak']],
  ["klama", ['kla']],
  ["klani", ['lai']],
  ["klaso", []],
  ["klesi", ['kle', 'lei']],
  ["kliki", []],
  ["klina", ['kli']],
  ["kliru", []],
  ["kliti", ['kit']],
  ["kloje", []],
  ["klupe", ["lu'e", 'lup']],
  ["kluza", ['luz']],
  ["kobli", ["ko'i", 'kob']],
  ["kogno", []],
  ["kojna", ['koj', "ko'a"]],
  ["kokso", []],
  ["kolme", ["ko'e", 'kol']],
  ["komcu", ['kom']],
  ["konju", ["ko'u", 'kon']],
  ["konve", []],
  ["korbi", ['koi', 'kor']],
  ["korcu", ['kro']],
  ["korka", ['kok']],
  ["korvo", []],
  ["kosmu", []],
  ["kosta", ['kos']],
  ["krali", []],
  ["kramu", []],
  ["krasi", ['kra']],
  ["krati", ["ka'i"]],
  ["krefu", ['ref', "ke'u"]],
  ["krici", ['kri']],
  ["krili", []],
  ["krinu", ["ki'u", 'rin']],
  ["krixa", ['kix', "ki'a"]],
  ["kroke", []],
  ["kroxo", []],
  ["kruca", ['kuc']],
  ["kruji", ['ruj']],
  ["kruvi", ['kru', 'ruv']],
  ["ku'a", ['kuz']],
  ["kubli", ['kub']],
  ["kucli", []],
  ["kufra", ['kuf']],
  ["kukru", []],
  ["kukte", ['kuk']],
  ["kulnu", ['klu']],
  ["kumfa", ["ku'a", 'kum']],
  ["kumte", []],
  ["kunra", ['kun']],
  ["kunti", ['kut']],
  ["kurfa", ['kur']],
  ["kurji", ["ku'i", 'kuj']],
  ["kurki", []],
  ["kurti", []],
  ["kuspe", ['kup', "ku'e"]],
  ["kusru", ['kus']],
  ["labno", []],
  ["lacni", []],
  ["lacpu", ['lap', 'cpu']],
  ["lacri", ['lac']],
  ["ladru", ['lad']],
  ["lafti", ['laf']],
  ["lakne", ["la'e"]],
  ["lakse", ['lak']],
  ["laldo", []],
  ["lalxu", ["la'u"]],
  ["lamda", []],
  ["lamdu", []],
  ["lamji", ["la'i", 'lam']],
  ["lanbi", []],
  ["lanci", []],
  ["landa", []],
  ["lanka", []],
  ["lanli", ['lal']],
  ["lanme", ['lan']],
  ["lanru", []],
  ["lante", []],
  ["lanxe", ['lax']],
  ["lanzu", ['laz']],
  ["larcu", ['lar']],
  ["larva", []],
  ["lasna", ["la'a"]],
  ["lastu", []],
  ["latmo", ["la'o"]],
  ["latna", []],
  ["laxte", []],
  ["lazni", []],
  ["lebna", ["le'a", 'leb']],
  ["le'e", ['lem']],
  ["lelxe", []],
  ["lenga", []],
  ["lengu", []],
  ["lenjo", ['len', "le'o"]],
  ["lenku", ['lek']],
  ["lerci", ['lec']],
  ["lerfu", ["le'u", 'ler']],
  ["letci", []],
  ["libjo", ['lib']],
  ["lidne", ["li'e"]],
  ["lifri", ['lif', 'fri']],
  ["ligma", []],
  ["li'i", ['liz']],
  ["lijda", ['jda']],
  ["likse", []],
  ["limfa", []],
  ["limna", ['lim']],
  ["lince", []],
  ["lindi", ['lid']],
  ["linga", []],
  ["linji", ['lij', "li'i"]],
  ["linsi", ['lin']],
  ["linto", ["li'o"]],
  ["lisri", ['lis']],
  ["liste", ['ste']],
  ["litce", ['lic']],
  ["litki", ['lik']],
  ["litru", ["li'u"]],
  ["livga", []],
  ["livla", ['lil']],
  ["lo'e", ['lom']],
  ["logji", ['loj']],
  ["loglo", []],
  ["lojbo", ['lob', 'jbo']],
  ["lojgo", []],
  ["lokra", []],
  ["loldi", ['loi', 'lol']],
  ["lorxu", ['lor', "lo'u"]],
  ["lubma", []],
  ["lubno", ["lu'o"]],
  ["lujvo", ['luv', 'jvo']],
  ["luksi", ['luk']],
  ["lumci", ['lum', "lu'i"]],
  ["lunbe", ['lub']],
  ["lungo", []],
  ["lunra", ['lur']],
  ["lunsa", ['lus']],
  ["luska", []],
  ["lusto", []],
  ["mabla", ['mal']],
  ["mabru", ['mab']],
  ["macnu", ['cnu']],
  ["majga", []],
  ["majvu", []],
  ["makcu", ["ma'u"]],
  ["makfa", ['maf']],
  ["maksi", ['mak']],
  ["malsi", ['mas']],
  ["maltu", []],
  ["malve", []],
  ["mamta", ['mam']],
  ["manci", ['mac']],
  ["manfo", []],
  ["mango", []],
  ["manku", ['man']],
  ["manri", ['mar']],
  ["mansa", []],
  ["manti", []],
  ["manva", []],
  ["mapku", ['map']],
  ["mapni", []],
  ["mapra", []],
  ["mapti", ['mat']],
  ["marbi", ['mra']],
  ["marce", ["ma'e"]],
  ["marde", ['mad']],
  ["margu", ['mag']],
  ["marji", ['mai', 'maj']],
  ["marna", []],
  ["marxa", ['max']],
  ["maska", []],
  ["masno", ['sno']],
  ["masti", ["ma'i"]],
  ["matci", []],
  ["matli", []],
  ["matne", []],
  ["matra", []],
  ["mavji", ['mav']],
  ["maxri", ['xri']],
  ["mebri", ['meb']],
  ["medzo", []],
  ["megdo", ['meg']],
  ["mei", ['mem', 'mei']],
  ["mekso", ["me'o", 'mek']],
  ["melbi", ['mel', 'mle']],
  ["meljo", ['mej']],
  ["melmi", []],
  ["menli", ['men']],
  ["menre", []],
  ["mensi", ['mes', "me'i"]],
  ["mentu", ['met', "me'u"]],
  ["merko", ['mer']],
  ["merli", ['mre']],
  ["mespo", []],
  ["metfo", []],
  ["metro", []],
  ["mexno", ['mex']],
  ["mi", ['mib']],
  ["midju", ['mij']],
  ["mifra", ['mif']],
  ["mikce", ['mic']],
  ["mikri", ['mik']],
  ["milti", ['mil']],
  ["milxe", ['mli']],
  ["mimta", []],
  ["minde", ["mi'e", 'mid']],
  ["minji", ["mi'i"]],
  ["minli", []],
  ["minra", ['mir']],
  ["mintu", ['mit', "mi'u"]],
  ["mipri", ['mip']],
  ["mirli", []],
  ["misno", ['mis', "mi'o"]],
  ["misro", []],
  ["miste", []],
  ["mitre", ['tre']],
  ["mixre", ['mix', 'xre']],
  ["mlana", ['mla']],
  ["mlatu", ['lat']],
  ["mleca", ["me'a", 'mec']],
  ["mledi", ['led']],
  ["mluni", ['lun']],
  ["mo'a", ['mob']],
  ["modju", []],
  ["modzi", []],
  ["mogle", []],
  ["mo'i", ['mov']],
  ["moi", ['mom', 'moi']],
  ["mokca", ['moc']],
  ["moklu", ['mol', "mo'u"]],
  ["molki", ['mlo']],
  ["molro", ["mo'o"]],
  ["morji", ["mo'i", 'moj']],
  ["morko", ['mor']],
  ["mormo", []],
  ["morna", ["mo'a", 'mon']],
  ["morsi", ['mro']],
  ["mosra", ['mos']],
  ["moxna", []],
  ["mraji", []],
  ["mrilu", ['mri']],
  ["mruli", ['mru']],
  ["mu", ['mum']],
  ["mucti", ['mut']],
  ["mudri", ['mud']],
  ["mu'e", ['muf']],
  ["mugle", []],
  ["mukti", ["mu'i", 'muk']],
  ["mulno", ["mu'o", 'mul']],
  ["munje", ['muj', "mu'e"]],
  ["mupli", ['mup']],
  ["murse", []],
  ["murta", ["mu'a", 'mur']],
  ["muslo", ['mus']],
  ["mutce", ['tce']],
  ["muvdu", ["mu'u", 'muv']],
  ["muzga", ['muz']],
  ["na", ['nar']],
  ["nabmi", ['nam']],
  ["na'e", ['nal']],
  ["nakni", ['nak']],
  ["nalci", ["na'i"]],
  ["nalfi", []],
  ["nalti", []],
  ["namcu", ['nac', "na'u"]],
  ["namra", []],
  ["nanba", ['nab']],
  ["nanca", ["na'a"]],
  ["nandu", ['nad']],
  ["nanla", []],
  ["nanmu", ['nau']],
  ["nanvi", ['nav']],
  ["narge", ['nag']],
  ["narju", ['naj']],
  ["natfe", ['naf', "na'e"]],
  ["natmi", ['nat', 'nai']],
  ["natsi", []],
  ["navni", []],
  ["naxle", ['xle', 'nax']],
  ["nazbi", ['zbi', 'naz']],
  ["nejni", ['nen']],
  ["nelci", ['nel', 'nei']],
  ["nenmu", []],
  ["nenri", ["ne'i", 'ner']],
  ["nerde", []],
  ["ni", ['nil']],
  ["nibli", ["ni'i", 'nib']],
  ["nicfa", ['nif']],
  ["nicte", ['cte']],
  ["nikle", ['nik']],
  ["nilce", ["ni'e"]],
  ["nimre", []],
  ["ninja", []],
  ["ninmu", ['nim', "ni'u"]],
  ["nirna", ['nir']],
  ["nitcu", ['tcu']],
  ["nivji", ['niv']],
  ["nixli", ['xli', 'nix']],
  ["no", ['non']],
  ["nobli", ['nol', "no'i"]],
  ["no'e", ['nor', "no'e"]],
  ["nonka", ['nok']],
  ["nonmu", []],
  ["nordo", []],
  ["norgo", []],
  ["notci", ['not', 'noi']],
  ["nu", ['nun']],
  ["nudle", []],
  ["nukni", ['nuk']],
  ["nuktu", []],
  ["nulpa", []],
  ["numje", []],
  ["nunmu", []],
  ["nu'o", ["nu'o"]],
  ["nupre", ['nup', "nu'e"]],
  ["nurma", ['num']],
  ["nusna", []],
  ["nutka", []],
  ["nutko", []],
  ["nutli", ["nu'i", 'nul']],
  ["nuzba", ['nuz']],
  ["nuzlo", []],
  ["pa", ['pav']],
  ["pacna", ["pa'a"]],
  ["pagbu", ['pag', 'pau']],
  ["pagre", ['gre']],
  ["pagzu", []],
  ["pajni", ['pai']],
  ["palci", ['pac']],
  ["palku", ['pak']],
  ["palma", []],
  ["palne", []],
  ["palpi", []],
  ["palta", []],
  ["pambe", []],
  ["pamga", []],
  ["panci", ['pan']],
  ["pandi", ['pad']],
  ["panje", []],
  ["panka", []],
  ["panlo", ["pa'o"]],
  ["panpi", ['pap']],
  ["panra", []],
  ["pante", ['pat']],
  ["panzi", ['paz']],
  ["papri", []],
  ["parbi", ['pab']],
  ["pardu", []],
  ["parji", []],
  ["paska", []],
  ["pastu", ['pas']],
  ["patfu", ["pa'u", 'paf']],
  ["patlu", []],
  ["patxu", ['pax']],
  ["paxra", []],
  ["paznu", []],
  ["pe'a", ['pev']],
  ["pegva", ['peg']],
  ["pelji", ['ple']],
  ["pelxu", ['pel']],
  ["pemci", ['pem']],
  ["penbi", ['peb']],
  ["pencu", ["pe'u", 'pec']],
  ["pendo", ['ped', "pe'o"]],
  ["penka", []],
  ["penki", []],
  ["penmi", ['pen', "pe'i"]],
  ["pensi", ['pei', 'pes']],
  ["pentu", []],
  ["pepsi", []],
  ["perli", ['per']],
  ["pesxu", ['pex']],
  ["petso", ['pet']],
  ["pevna", []],
  ["pezli", ['pez']],
  ["pi", ['piz']],
  ["picti", ['pic']],
  ["pijne", []],
  ["pikci", []],
  ["pikpi", []],
  ["pikta", []],
  ["pilda", []],
  ["pilji", ["pi'i"]],
  ["pilka", ["pi'a", 'pil']],
  ["pilno", ['pli']],
  ["pimlu", ["pi'u", 'pim']],
  ["pinca", []],
  ["pindi", ['pid']],
  ["pinfu", ['pif']],
  ["Pingo", []],
  ["pinji", []],
  ["pinka", ['pik']],
  ["pinsi", ['pis']],
  ["pinta", ['pin']],
  ["pinxe", ['pix']],
  ["pipno", ["pi'o"]],
  ["pirxo", []],
  ["pitsa", []],
  ["pi'u", ['piv']],
  ["pixra", ['xra', 'pir']],
  ["plana", []],
  ["platu", ['pla']],
  ["pleji", ["le'i", 'lej']],
  ["plibu", ['pib']],
  ["plini", []],
  ["plipe", ['pip', "pi'e"]],
  ["plise", []],
  ["plita", ['pit']],
  ["plixa", ['lix']],
  ["pluja", ['luj']],
  ["pluka", ["pu'a", 'puk']],
  ["pluna", []],
  ["pluta", ["lu'a", 'lut']],
  ["pocli", []],
  ["polje", ['plo']],
  ["polno", ['pol']],
  ["ponjo", ["po'o", 'pon']],
  ["ponse", ['pos', "po'e"]],
  ["poplu", []],
  ["porno", []],
  ["porpi", ['pop', "po'i"]],
  ["porsi", ['poi', 'por']],
  ["porto", ['pot']],
  ["prali", ['pal']],
  ["prami", ["pa'i", 'pam']],
  ["prane", ["pa'e"]],
  ["predi", []],
  ["preja", ["pe'a", 'pej']],
  ["premi", []],
  ["prenu", ['pre']],
  ["preri", []],
  ["preti", ['rei', 'ret']],
  ["prije", ['pij']],
  ["prina", ['pri']],
  ["pritu", []],
  ["proga", ['pog']],
  ["proji", []],
  ["prosa", ["ro'a", 'ros']],
  ["pruce", ["ru'e", 'ruc']],
  ["pruni", ['pun']],
  ["pruri", []],
  ["pruxi", ["ru'i", 'rux']],
  ["pu'i", ['pus']],
  ["pulce", ['puc', "pu'e"]],
  ["pulji", []],
  ["pulni", []],
  ["punji", ['puj', "pu'i"]],
  ["punli", ['pul']],
  ["pupsu", ['pup']],
  ["purci", ['pur', 'pru']],
  ["purdi", ['pud']],
  ["purmo", ["pu'o", 'pum']],
  ["purni", []],
  ["pu'u", ['puv']],
  ["puvza", []],
  ["racli", []],
  ["ractu", []],
  ["radno", ["ra'o"]],
  ["rafsi", ['raf']],
  ["ragbi", []],
  ["ragve", ['rav']],
  ["rakle", []],
  ["rakso", []],
  ["raktu", ["ra'u"]],
  ["ralci", ['rac']],
  ["ralju", ['ral']],
  ["ralte", ["ra'e"]],
  ["randa", ['rad']],
  ["rango", ['rag']],
  ["ranji", ["ra'i"]],
  ["ranlu", []],
  ["ranmi", ['ram']],
  ["ransu", []],
  ["ranti", ['ran']],
  ["ranxi", ['rax']],
  ["rapli", ['rap']],
  ["rarna", ['rar']],
  ["ratcu", []],
  ["ratma", []],
  ["ratni", ['rat']],
  ["re", ['rel']],
  ["rebla", ['reb']],
  ["rectu", ['rec', "re'u"]],
  ["reksa", []],
  ["rekto", []],
  ["remna", ['rem', "re'a"]],
  ["renro", ["re'o", 'rer']],
  ["renvi", ['rev', "re'i"]],
  ["respa", ['res']],
  ["rexsa", ['rex']],
  ["ribga", []],
  ["ricfu", ['cfu', 'rif']],
  ["rigni", ['rig']],
  ["rijno", ['rij']],
  ["rilti", ['ril']],
  ["rimni", ['rim']],
  ["rinci", []],
  ["rindo", []],
  ["rinju", ["ri'u"]],
  ["rinka", ['rik', "ri'a"]],
  ["rinsa", []],
  ["ripto", []],
  ["rirci", []],
  ["rirli", []],
  ["rirni", ['rir']],
  ["rirxe", ["ri'e"]],
  ["rismi", ['ris']],
  ["risna", []],
  ["ritli", ["ri'i"]],
  ["rivbi", ['riv']],
  ["ro", ['rol']],
  ["roi", ['roi', 'rom']],
  ["rokci", ['rok', "ro'i"]],
  ["romge", ['rog']],
  ["romlo", []],
  ["ronci", ['roc']],
  ["ronro", []],
  ["ronsa", []],
  ["ronti", []],
  ["ropno", ['ron', "ro'o"]],
  ["rorci", ['ror']],
  ["rotsu", ["ro'u", 'rot', 'tsu']],
  ["rozgu", ['zgu', 'roz']],
  ["ruble", ['ble', 'rub']],
  ["rucni", []],
  ["rufsu", ['ruf']],
  ["runme", ['rum']],
  ["runta", []],
  ["rupnu", ['rup', "ru'u"]],
  ["rusko", ['ruk', "ru'o"]],
  ["rutni", ['run']],
  ["sabji", ['sab']],
  ["sabnu", []],
  ["sacki", []],
  ["saclu", []],
  ["sacni", []],
  ["sadjo", ['djo']],
  ["sakci", ['sak']],
  ["sakli", ['sal']],
  ["sakta", ['sat']],
  ["salci", ['sla']],
  ["salmo", []],
  ["salni", []],
  ["salpo", ["sa'o"]],
  ["salri", []],
  ["salta", []],
  ["samcu", []],
  ["sampu", ['sap']],
  ["sanbu", []],
  ["sance", ['sna']],
  ["sanga", ["sa'a", 'sag']],
  ["sanji", ['saj']],
  ["sanli", ["sa'i"]],
  ["sanmi", ['sai']],
  ["sanra", []],
  ["sanso", []],
  ["santa", []],
  ["sarcu", ["sa'u"]],
  ["sarji", ['sra']],
  ["sarlu", []],
  ["sarni", []],
  ["sarxe", ['sax']],
  ["saske", ['ske']],
  ["satci", []],
  ["satre", ["sa'e"]],
  ["savru", ['sav', 'vru']],
  ["sazri", ['saz']],
  ["se", ['sel']],
  ["sefsi", []],
  ["sefta", ['sfe']],
  ["sekre", []],
  ["selci", ['sle']],
  ["selfu", ['sef', "se'u"]],
  ["semto", ['sme']],
  ["senci", ['sec']],
  ["sengi", []],
  ["senpi", ['sen']],
  ["senta", ['set']],
  ["senva", ['sev', 'sne']],
  ["sepli", ['sei', 'sep']],
  ["sepre", []],
  ["serti", ['ser']],
  ["sesre", []],
  ["setca", ["se'a"]],
  ["sevzi", ["se'i", 'sez']],
  ["sezni", []],
  ["sfani", []],
  ["sfasa", ['sfa']],
  ["sfero", []],
  ["sfite", ['sfi']],
  ["sfofa", ['sfo']],
  ["sfubu", ['sub', "su'u"]],
  ["sibli", []],
  ["siclu", ['sil']],
  ["sicni", ["si'i"]],
  ["sicpi", []],
  ["sidbo", ["si'o", 'sib']],
  ["sidju", ['dju']],
  ["sigda", []],
  ["sigja", ['sig']],
  ["sigma", []],
  ["sikta", []],
  ["silja", []],
  ["silka", ['sik']],
  ["silna", []],
  ["silru", []],
  ["simlu", ['mlu']],
  ["simsa", ['smi']],
  ["simxu", ['sim', "si'u"]],
  ["since", []],
  ["sinma", ["si'a"]],
  ["sinso", []],
  ["sinxa", ['sni']],
  ["si'o", ['siz']],
  ["sipna", ['sip']],
  ["sirji", ['sir']],
  ["sirxo", ['six']],
  ["sisku", ['sis']],
  ["sisti", ['sti']],
  ["sitla", []],
  ["sitna", ['sit']],
  ["sivni", ['siv']],
  ["sizgo", []],
  ["skaci", []],
  ["skami", ['sam']],
  ["skano", []],
  ["skapi", ['kap']],
  ["skari", ['ska']],
  ["skicu", ['ski']],
  ["skifa", []],
  ["skiji", ['sij']],
  ["skina", ['kin']],
  ["skori", ['sko']],
  ["skoto", ["ko'o", 'kot']],
  ["skuba", []],
  ["skudi", []],
  ["skuna", []],
  ["skuro", ["ku'o"]],
  ["slabu", ['sau']],
  ["slaka", []],
  ["slami", []],
  ["slanu", []],
  ["slari", ['sar']],
  ["slasi", ['las']],
  ["sligu", ['lig']],
  ["slilu", ['sli']],
  ["sliri", []],
  ["slovo", ['lov', "lo'o"]],
  ["sluji", ['slu']],
  ["sluni", []],
  ["smacu", []],
  ["smadi", []],
  ["smaji", ['sma']],
  ["smaka", []],
  ["smani", []],
  ["smela", []],
  ["smoka", ['smo']],
  ["smuci", ['muc']],
  ["smuni", ['smu', 'mun']],
  ["smusu", []],
  ["snada", ['sad']],
  ["snafu", []],
  ["snanu", ['nan']],
  ["snavi", []],
  ["snidu", ['nid']],
  ["sniju", []],
  ["snime", ["si'e"]],
  ["snipa", ['nip']],
  ["snuji", ['nuj']],
  ["snura", ["nu'a", 'nur']],
  ["snuti", ['nut']],
  ["so", ['soz']],
  ["so'a", ['soj']],
  ["sobde", ['sob', "so'e"]],
  ["socni", []],
  ["sodna", []],
  ["sodva", ['sod']],
  ["so'e", ['sop']],
  ["softo", ['sof']],
  ["so'i", ['sor', "so'i"]],
  ["solji", ['slo']],
  ["solri", ['sol']],
  ["sombo", ['som', "so'o"]],
  ["sonci", ['soi', 'son']],
  ["sondu", []],
  ["so'o", ['sos']],
  ["sorcu", ['soc', 'sro']],
  ["sorgu", ['sog']],
  ["sorni", []],
  ["sorta", []],
  ["so'u", ['sot']],
  ["sovda", ["so'a", 'sov']],
  ["spaji", ['paj']],
  ["spali", []],
  ["spano", ['san']],
  ["spati", ['spa']],
  ["speci", []],
  ["speni", ['spe']],
  ["spero", []],
  ["spisa", ['spi']],
  ["spita", []],
  ["spofu", ['pof', "po'u"]],
  ["spoja", ["po'a", 'poj']],
  ["spuda", ['spu']],
  ["sputu", ["pu'u", 'put']],
  ["sraji", ['raj']],
  ["sraku", ['rak']],
  ["sralo", []],
  ["srana", ["ra'a"]],
  ["srasu", ['sas']],
  ["srate", []],
  ["srera", ['sre']],
  ["srito", []],
  ["sruma", ["ru'a"]],
  ["sruri", ['rur', 'sru']],
  ["stace", ['sac']],
  ["stagi", []],
  ["staku", ['tak']],
  ["stali", ['sta']],
  ["stani", []],
  ["stapa", ['tap']],
  ["stasu", []],
  ["stati", []],
  ["steba", ['seb']],
  ["steci", ['tec', "te'i"]],
  ["stedu", ['sed']],
  ["stela", ['tel']],
  ["stero", ["te'o"]],
  ["stici", ['sic']],
  ["stidi", ["ti'i", 'sid']],
  ["stika", ['tik']],
  ["stima", []],
  ["stizu", ['tiz']],
  ["stodi", ['sto']],
  ["stori", []],
  ["stuna", ['sun']],
  ["stura", ['tur', "su'a"]],
  ["stuzi", ['stu', 'tuz']],
  ["sucta", ['suc']],
  ["sudga", ['sud']],
  ["su'e", ['sup', "su'e"]],
  ["sufti", ['sfu']],
  ["suksa", ['suk']],
  ["sumji", ['suj']],
  ["sumla", []],
  ["sumne", []],
  ["sumro", []],
  ["sumti", ['sum', "su'i"]],
  ["sunga", ['sug']],
  ["sunla", ['sul']],
  ["su'o", ['suz', "su'o"]],
  ["supso", ['sus']],
  ["surla", ['sur']],
  ["sutra", ['sut']],
  ["su'u", ['suv']],
  ["ta", ['taz']],
  ["tabno", ['tab']],
  ["tabra", []],
  ["tadji", []],
  ["tadni", ['tad']],
  ["tagji", ['tag']],
  ["takni", []],
  ["taksi", []],
  ["talko", []],
  ["talsa", ['tal']],
  ["tamca", []],
  ["tamji", ['taj']],
  ["tamle", []],
  ["tamne", []],
  ["tanbo", ["ta'o"]],
  ["tance", ['tac']],
  ["tanjo", []],
  ["tanko", []],
  ["tanru", ['tau']],
  ["tansi", ['tas']],
  ["tanxe", ['tax', "ta'e"]],
  ["tapla", []],
  ["tarbi", []],
  ["tarci", ['tar']],
  ["tarla", []],
  ["tarmi", ['tai', 'tam']],
  ["tarti", ['tra']],
  ["taske", []],
  ["tasmi", []],
  ["tasta", []],
  ["tatpi", ["ta'i"]],
  ["tatru", ['tat']],
  ["tavla", ['tav', "ta'a"]],
  ["taxfu", ['taf', "ta'u"]],
  ["tcaci", ['cac']],
  ["tcadu", ['tca']],
  ["tcana", []],
  ["tcati", []],
  ["tcaxe", []],
  ["tcema", []],
  ["tcemi", []],
  ["tcena", ['ten']],
  ["tcesa", []],
  ["tcese", []],
  ["tcica", ['tic']],
  ["tcidu", ['tid']],
  ["tcika", []],
  ["tcila", ['til']],
  ["tcima", ["ti'a", 'tim']],
  ["tcini", []],
  ["tcipi", []],
  ["tcita", []],
  ["tcivi", []],
  ["tcobi", []],
  ["tcone", []],
  ["tcuti", []],
  ["te", ['ter']],
  ["tekla", []],
  ["temci", ['tei', 'tem']],
  ["temse", []],
  ["tende", ["te'e"]],
  ["tenfa", ['tef']],
  ["tengu", ["te'u", 'teg']],
  ["terdi", ['ted']],
  ["terki", []],
  ["terpa", ['tep', "te'a"]],
  ["terto", ['tet']],
  ["tezda", []],
  ["ti", ['tif']],
  ["tifri", []],
  ["tigni", ['tig']],
  ["tigra", []],
  ["tikpa", ['tip']],
  ["tilju", ['tij']],
  ["timno", []],
  ["tinbe", ['tib']],
  ["tinci", []],
  ["tinri", []],
  ["tinsa", []],
  ["tinto", []],
  ["tipre", []],
  ["tirna", ['tin']],
  ["tirse", ['tir']],
  ["tirxu", []],
  ["tisna", ['tis']],
  ["titla", ['tit']],
  ["tivni", ['tiv']],
  ["tixnu", ["ti'u", 'tix']],
  ["tizva", []],
  ["to'e", ['tol', "to'e"]],
  ["toknu", ['tok']],
  ["toldi", ['tod']],
  ["tolfa", []],
  ["tonga", ["to'a", 'tog']],
  ["tordu", ['tor', "to'u"]],
  ["torni", ['ton', "to'i"]],
  ["torso", []],
  ["torta", []],
  ["tovla", []],
  ["traji", ['rai']],
  ["trano", []],
  ["trati", []],
  ["trene", ['ren', "re'e"]],
  ["tricu", ['ric']],
  ["triga", []],
  ["trina", ['tri']],
  ["trixe", ["ti'e", 'rix']],
  ["troci", ['toi', 'toc']],
  ["tsaba", []],
  ["tsali", ['tsa']],
  ["tsani", ['tan']],
  ["tsapi", []],
  ["tsida", []],
  ["tsiju", ['tsi']],
  ["tsina", ['sin']],
  ["tsuku", []],
  ["tsuli", []],
  ["tu", ['tuf']],
  ["tubnu", ["tu'u"]],
  ["tubra", []],
  ["tugni", ['tug', "tu'i"]],
  ["tujli", ['tuj']],
  ["tulnu", []],
  ["tumla", ["tu'a", 'tum']],
  ["tunba", ['tub']],
  ["tunka", ['tuk']],
  ["tunlo", ["tu'o", 'tul']],
  ["tunta", ['tun']],
  ["tuple", ["tu'e", 'tup']],
  ["turko", []],
  ["turni", ['tru']],
  ["tutci", ['tci']],
  ["tutle", []],
  ["tutra", ['tut']],
  ["va", ['vaz']],
  ["vacri", ['var']],
  ["vajni", ['vaj', 'vai']],
  ["valfa", ['vaf']],
  ["valsi", ['vla', 'val']],
  ["vamgu", []],
  ["vamji", ["va'i", 'vam']],
  ["vamtu", ['vat']],
  ["vanbi", ['vab']],
  ["vanci", ['vac']],
  ["vanju", ['van']],
  ["vasru", ['vau', 'vas']],
  ["vasxu", ["va'u", 'vax']],
  ["ve", ['vel']],
  ["vecnu", ['ven', "ve'u"]],
  ["vedli", ["ve'i"]],
  ["ve'e", ["ve'e"]],
  ["venfu", ['vef']],
  ["vensa", ['ves']],
  ["vente", []],
  ["vepre", []],
  ["verba", ["ve'a", 'ver']],
  ["verjo", []],
  ["vi", ['viz']],
  ["vibna", ['vib']],
  ["vidni", []],
  ["vidru", ['vir']],
  ["vidvi", []],
  ["vifne", ['vif']],
  ["vikmi", ["vi'i", 'vim']],
  ["viknu", ['vik']],
  ["vilco", []],
  ["vimcu", ['vic', "vi'u"]],
  ["vindu", ['vid']],
  ["vinji", ['vij']],
  ["vinpa", []],
  ["vinta", []],
  ["vipsi", ['vip']],
  ["virme", []],
  ["virnu", ['vri']],
  ["viska", ['vis', "vi'a"]],
  ["vitci", ['vit']],
  ["vitke", ["vi'e"]],
  ["vitno", ["vi'o"]],
  ["vlagi", ['lag']],
  ["vlile", ['vil']],
  ["vlina", []],
  ["vlipa", ['vli']],
  ["vo", ['von']],
  ["vofli", ['vol', 'voi']],
  ["voksa", ['vok', "vo'a"]],
  ["volve", []],
  ["vorme", ['vor', 'vro']],
  ["vraga", ['vra']],
  ["vreji", ['rej', 'vei']],
  ["vreta", ['vre']],
  ["vrici", []],
  ["vrude", ['vud', "vu'e"]],
  ["vrusi", ['vus', "vu'i"]],
  ["vu", ['vuz']],
  ["vubla", ['vul']],
  ["vujnu", ["vu'u", 'vuj']],
  ["vukna", []],
  ["vukro", ['vur', "vu'o"]],
  ["xa", ['xav']],
  ["xabju", ["xa'u"]],
  ["xadba", ['xab']],
  ["xadji", []],
  ["xadni", ['xad']],
  ["xagji", []],
  ["xagri", []],
  ["xajmi", ['xam']],
  ["xaksu", ['xak']],
  ["xakto", []],
  ["xalbo", []],
  ["xalda", []],
  ["xalka", ['xal']],
  ["xalni", []],
  ["xamgu", ['xag', 'xau']],
  ["xampo", ['xap', "xa'o"]],
  ["xamsi", ['xas']],
  ["xance", ["xa'e", 'xan']],
  ["xango", []],
  ["xanka", []],
  ["xanmi", []],
  ["xanri", ['xar']],
  ["xansa", []],
  ["xanto", []],
  ["xarci", ["xa'i", 'xac']],
  ["xarju", ['xaj']],
  ["xarnu", []],
  ["xasli", []],
  ["xasne", []],
  ["xatra", ["xa'a"]],
  ["xatsi", ['xat']],
  ["xavli", []],
  ["xaxre", []],
  ["xazdo", ['xaz', 'zdo']],
  ["xe", ['xel']],
  ["xebni", ['xen', 'xei']],
  ["xebro", ['xeb', 'bro']],
  ["xecto", ['cto', 'xet']],
  ["xedja", ['xej', "xe'a"]],
  ["xekce", []],
  ["xekri", ['xek', "xe'i"]],
  ["xelso", ['xes']],
  ["xendo", ["xe'o", 'xed']],
  ["xenru", ["xe'u", 'xer']],
  ["xerno", []],
  ["xexso", ['xex']],
  ["xigzo", ['xig']],
  ["xijra", []],
  ["xilva", ['xiv']],
  ["ximta", []],
  ["xindo", ['xin']],
  ["xinmo", ['xim']],
  ["xinro", []],
  ["xinsi", []],
  ["xirma", ["xi'a", 'xir']],
  ["xislu", ["xi'u", 'xil']],
  ["xispo", ['xip']],
  ["xixli", []],
  ["xixnu", []],
  ["xlali", ['xla']],
  ["xlobi", []],
  ["xlura", ['xlu']],
  ["xonba", []],
  ["xorbo", []],
  ["xorlo", []],
  ["xotli", ['xoi', 'xol']],
  ["xrabo", ['rab']],
  ["xrani", ['xai']],
  ["xriso", ["xi'o", 'xis']],
  ["xroma", []],
  ["xrotu", ['xro']],
  ["xruba", ['xub']],
  ["xruki", ['xuk']],
  ["xrula", ['rul']],
  ["xruti", ['xru']],
  ["xudvu", ["xu'u"]],
  ["xukmi", ['xum', "xu'i"]],
  ["xulta", ['xut']],
  ["xumbe", []],
  ["xunre", ['xun', "xu'e"]],
  ["xurdo", ['xur', "xu'o"]],
  ["xusra", ['xus', "xu'a"]],
  ["xutla", ['xul']],
  ["zabna", ['zan', "za'a"]],
  ["za'i", ['zaz']],
  ["zajba", ['zaj']],
  ["zalvi", ['zal']],
  ["zandi", ['zad']],
  ["zanru", ['zar', 'zau']],
  ["zanxi", []],
  ["za'o", ["za'o"]],
  ["zarci", ['zai', 'zac']],
  ["zargu", ['zag', "za'u"]],
  ["zasni", ['zas']],
  ["zasti", ["za'i", 'zat']],
  ["zbabu", ['bab']],
  ["zbani", []],
  ["zbasu", ['zba']],
  ["zbepi", ['zbe']],
  ["zdani", ['zda']],
  ["zdile", ['zdi']],
  ["ze", ['zel']],
  ["ze'e", ["ze'e"]],
  ["zejvo", []],
  ["zekri", ['zei', 'zer']],
  ["zenba", ['zen', "ze'a"]],
  ["ze'o", ["ze'o", 'zev']],
  ["zepti", ['zep']],
  ["zergi", []],
  ["zetro", ['zet']],
  ["zevla", ['zve']],
  ["zgadi", []],
  ["zgana", ['zga']],
  ["zgike", ['zgi', "gi'e"]],
  ["zguro", []],
  ["zifre", ['zif', "zi'e"]],
  ["zinki", ['zin', "zi'i"]],
  ["zi'o", ['zil']],
  ["zirli", []],
  ["zirpu", ['zir', "zi'u"]],
  ["zivle", ['ziv', 'vle']],
  ["zmadu", ['mau', 'zma']],
  ["zmico", ['zic']],
  ["zmiku", ['zmi']],
  ["zo'a", ['zon', "zo'a"]],
  ["zo'i", ["zo'i", 'zor']],
  ["zorti", []],
  ["zozno", []],
  ["zubra", []],
  ["zucna", ['zuc', "zu'a"]],
  ["zukte", ['zuk', "zu'e"]],
  ["zulna", []],
  ["zumri", ['zmu']],
  ["zungi", ['zug']],
  ["zunle", ['zul']],
  ["zunti", ["zu'i", 'zun']],
  ["zu'o", ['zum']],
  ["zurja", ['zuj']],
  ["zutse", ['zut', 'tse']],
  ["zvati", ['zva']],
  ["zviki", ['zvi']],
  ["zvuzu", []],
  ["xi", ['xix']],
  ["zai'e", ['zam']],
  ["je'ebzi", ['jeb']],
  ["mu'umgu", ['mug']],
  ["va'arga", ["va'a"]],
  ["co'ai", ['cox']],
  ["dau", ['duv']],
  ["fei", ['fel']],
  ["ga'ei", ['gel']],
  ["gai", ['gam']],
  ["jau", ['juz']],
  ["ke'ai", ['ked']],
  ["ke'ei", ['keb']],
  ["ke'ei'a", ['kex']],
  ["kei'ei", ['kim']],
  ["lai'ai", ['lav']],
  ["su'ei", ['sem']],
  ["tau'u", ['tux']],
  ["to'ai", ['toz']],
  ["vai", ['vav']],
  ["vo'ai", ['voz']],
  ["xei", ['xem']],
  ["xo'ai", ['xoz']],
  ["xo'ei", ['xon']],
  ["zei'e", ['zex']],
  ["zei'o", ['zes']],
]);