#![allow(dead_code)]

use std::sync::LazyLock;

pub const RESET: &str = "\x1b[m";
pub const BOLD: &str = "\x1b[1m";
pub const ITALIC: &str = "\x1b[3m";
pub const BLACK: &str = "\x1b[90;m";
pub const RED: &str = "\x1b[91;m";
pub const GREEN: &str = "\x1b[92;m";
pub const YELLOW: &str = "\x1b[93;m";
pub const BLUE: &str = "\x1b[94;m";
pub const PINK: &str = "\x1b[95;m";
pub const CYAN: &str = "\x1b[96;m";
pub const WHITE: &str = "\x1b[97;m";
pub const VERSION: &str = "latkerlo-jvotci v2.7.2601";

pub static CLI_INSTRUCTIONS: LazyLock<String> = LazyLock::new(|| {
    [
        YELLOW,
        BOLD,
        VERSION,
        RESET,
        " ",
        CYAN,
        "cli edition\nusage:",
        RESET,
        " ",
        BOLD,
        "jvotci",
        RESET,
        " (",
        BOLD,
        ITALIC,
        "flags",
        RESET,
        ") (",
        BOLD,
        ITALIC,
        "input",
        RESET,
        "...)\n",
        CYAN,
        "flags:",
        RESET,
        " (",
        GREEN,
        "*",
        RESET,
        " = default)\n  ",
        PINK,
        "modes:",
        RESET,
        "\n    ",
        BOLD,
        "-Z",
        RESET,
        GREEN,
        "* >1 word",
        RESET,
        " convert tanru/rafsi to lujvo\n    ",
        BOLD,
        "-L",
        RESET,
        GREEN,
        "*  1 word",
        RESET,
        " analyze brivla, decompose if possible\n    ",
        BOLD,
        "-h",
        RESET,
        "  print this help text\n  you may need to pass ",
        BOLD,
        "-Z",
        RESET,
        " explicitly if the input starts with a formatted rafsi like {-vla-},\n  since otherwise \
         it will get interpreted as a flag.\n  ",
        PINK,
        "toggles:",
        RESET,
        "\n    ",
        BOLD,
        "-c",
        RESET,
        "  generate a cmevla\n    ",
        BOLD,
        "-r",
        RESET,
        "  allow any cmavo to be a rafsi\n    ",
        BOLD,
        "-g",
        RESET,
        "  treat glides as consonants\n    ",
        BOLD,
        "-z",
        RESET,
        "  allow {mz}\n  ",
        PINK,
        "hyphens:",
        RESET,
        " (up to 1 option allowed)\n    ",
        BOLD,
        "-S",
        RESET,
        GREEN,
        "*",
        RESET,
        " CLL hyphen rules + {'y} etc for zi'evla\n    ",
        BOLD,
        "-A",
        RESET,
        "  allow {'y} etc hyphens in place of {r} or {n}\n    ",
        BOLD,
        "-F",
        RESET,
        "  force {'y} and treat words with {r} or {n} as zi'evla\n  hyphens that are present when \
         they don't need to be are always permitted\n  ",
        PINK,
        "consonants:",
        RESET,
        " (up to 1 option allowed)\n    ",
        BOLD,
        "-C",
        RESET,
        GREEN,
        "*",
        RESET,
        " require a consonant cluster\n    ",
        BOLD,
        "-2",
        RESET,
        "  minimum 2 consonants\n    ",
        BOLD,
        "-1",
        RESET,
        "  minimum 1 consonant\nmultiple flags ",
        ITALIC,
        "must",
        RESET,
        " be grouped together if present, and they can be set in any order, e.g. ",
        BOLD,
        "-Zgc1rA",
        RESET,
        "\n",
        CYAN,
        "input:",
        RESET,
        " a string to do things to\nif it's multiple words they will get concatenated.\nif a \
         rafsi is entered, its selrafsi will be shown, and vice versa.\nif no input is provided, \
         an interactive mode is used. help for that can be printed with ",
        BOLD,
        "/h",
        RESET,
    ]
    .join("")
});

pub static TUI_INSTRUCTIONS: LazyLock<String> = LazyLock::new(|| {
    [
        YELLOW,
        BOLD,
        VERSION,
        RESET,
        " ",
        CYAN,
        "interactive edition\n",
        RESET,
        CYAN,
        "flags:",
        RESET,
        " (",
        GREEN,
        "*",
        RESET,
        " = default)\n  ",
        PINK,
        "modes:",
        RESET,
        "\n    ",
        BOLD,
        "/Z",
        RESET,
        GREEN,
        "*",
        RESET,
        " (",
        CYAN,
        "zbasu",
        RESET,
        ") convert tanru/rafsi to lujvo\n    ",
        BOLD,
        "/L",
        RESET,
        "  (",
        CYAN,
        "lanli",
        RESET,
        ") analyze brivla, decompose if possible\n    ",
        BOLD,
        "/h",
        RESET,
        "  print this help text\n    ",
        BOLD,
        "/q",
        RESET,
        "  quit\n  ",
        PINK,
        "toggles:",
        RESET,
        "\n    ",
        BOLD,
        "/c",
        RESET,
        "  generate a cmevla\n    ",
        BOLD,
        "/r",
        RESET,
        "  allow any cmavo to be a rafsi\n    ",
        BOLD,
        "/g",
        RESET,
        "  treat glides as consonants\n    ",
        BOLD,
        "/z",
        RESET,
        "  allow {mz}\n  ",
        PINK,
        "hyphens:",
        RESET,
        " (up to 1 option allowed)\n    ",
        BOLD,
        "/S",
        RESET,
        GREEN,
        "*",
        RESET,
        " CLL hyphen rules + {'y} etc for zi'evla\n    ",
        BOLD,
        "/A",
        RESET,
        "  allow {'y} etc hyphens in place of {r} or {n}\n    ",
        BOLD,
        "/F",
        RESET,
        "  force {'y} and treat words with {r} or {n} as zi'evla\n  hyphens that are present when \
         they don't need to be are always permitted\n  ",
        PINK,
        "consonants:",
        RESET,
        " (up to 1 option allowed)\n    ",
        BOLD,
        "/C",
        RESET,
        GREEN,
        "*",
        RESET,
        " require a consonant cluster\n    ",
        BOLD,
        "/2",
        RESET,
        "  minimum 2 consonants\n    ",
        BOLD,
        "/1",
        RESET,
        "  minimum 1 consonant\nsingle-character flags only toggle themselves.\nmultiple flags \
         can be set at once and in any order, e.g. ",
        BOLD,
        "/Zgc1rA",
        RESET,
        ".\nto return to the default settings, use ",
        BOLD,
        "/",
        RESET,
    ]
    .join("")
});
