//! Contains the const RAFSI, a map from words to their affixes. docs.rs thinks it's a struct due to `lazy_static!`.
use std::collections::HashMap;
use lazy_static::lazy_static;
lazy_static! {
    pub static ref RAFSI: HashMap<&'static str, &'static[&'static str]> = {
        let mut map = HashMap::new();
        map.insert("babda", &[] as &[&str]);
        map.insert("bablo", &[] as &[&str]);
        map.insert("backi", &[] as &[&str]);
        map.insert("bacru", &["ba'u"]);
        map.insert("badji", &[] as &[&str]);
        map.insert("badna", &[] as &[&str]);
        map.insert("badri", &["dri"]);
        map.insert("bajra", &["baj"]);
        map.insert("bakfu", &["baf"]);
        map.insert("bakni", &["bak"]);
        map.insert("bakri", &[] as &[&str]);
        map.insert("baktu", &[] as &[&str]);
        map.insert("balji", &[] as &[&str]);
        map.insert("balni", &[] as &[&str]);
        map.insert("balre", &["ba'e"]);
        map.insert("balto", &[] as &[&str]);
        map.insert("balvi", &["bav"]);
        map.insert("bambu", &[] as &[&str]);
        map.insert("bancu", &["bac"]);
        map.insert("bandu", &["bad"]);
        map.insert("banfi", &[] as &[&str]);
        map.insert("bangu", &["bau", "ban"]);
        map.insert("banli", &["bal", "ba'i"]);
        map.insert("banro", &["ba'o"]);
        map.insert("banxa", &["bax"]);
        map.insert("banzu", &["baz"]);
        map.insert("bapli", &["bap", "bai"]);
        map.insert("barda", &["bra"]);
        map.insert("bargu", &["bag"]);
        map.insert("barja", &[] as &[&str]);
        map.insert("barna", &["ba'a"]);
        map.insert("bartu", &["bar"]);
        map.insert("basfa", &[] as &[&str]);
        map.insert("basna", &[] as &[&str]);
        map.insert("basti", &["bas"]);
        map.insert("batci", &["bat"]);
        map.insert("batke", &[] as &[&str]);
        map.insert("bavmi", &[] as &[&str]);
        map.insert("bavza", &[] as &[&str]);
        map.insert("baxso", &[] as &[&str]);
        map.insert("bebna", &["beb"]);
        map.insert("bekpi", &[] as &[&str]);
        map.insert("belta", &[] as &[&str]);
        map.insert("bemro", &["be'o", "bem"]);
        map.insert("bende", &["bed", "be'e"]);
        map.insert("bengo", &["beg"]);
        map.insert("benji", &["be'i", "bej"]);
        map.insert("benre", &[] as &[&str]);
        map.insert("benzo", &[] as &[&str]);
        map.insert("bergu", &[] as &[&str]);
        map.insert("bersa", &["be'a", "bes"]);
        map.insert("berti", &["ber"]);
        map.insert("besna", &["ben"]);
        map.insert("besto", &[] as &[&str]);
        map.insert("betfu", &["bef", "be'u"]);
        map.insert("betka", &[] as &[&str]);
        map.insert("betri", &["bet"]);
        map.insert("bevri", &["bev", "bei"]);
        map.insert("bi", &["biv"]);
        map.insert("bidju", &[] as &[&str]);
        map.insert("bifce", &["bic"]);
        map.insert("bi'i", &["biz"]);
        map.insert("bikla", &["bik"]);
        map.insert("bilbo", &[] as &[&str]);
        map.insert("bilga", &["big"]);
        map.insert("bilma", &["bi'a"]);
        map.insert("bilni", &["bil"]);
        map.insert("bindo", &["bid"]);
        map.insert("binra", &[] as &[&str]);
        map.insert("binxo", &["bi'o", "bix"]);
        map.insert("birje", &[] as &[&str]);
        map.insert("birka", &["bir"]);
        map.insert("birti", &["bit"]);
        map.insert("bisli", &["bis"]);
        map.insert("bitmu", &["bi'u", "bim"]);
        map.insert("bitni", &[] as &[&str]);
        map.insert("blabi", &["lab"]);
        map.insert("blaci", &[] as &[&str]);
        map.insert("blanu", &["bla"]);
        map.insert("bliku", &["bli"]);
        map.insert("blina", &[] as &[&str]);
        map.insert("blolo", &[] as &[&str]);
        map.insert("bloti", &["lot", "lo'i", "blo"]);
        map.insert("bluji", &[] as &[&str]);
        map.insert("bo", &["bor"]);
        map.insert("bolci", &["bol", "boi"]);
        map.insert("bongu", &["bog", "bo'u"]);
        map.insert("boske", &[] as &[&str]);
        map.insert("botpi", &["bot", "bo'i"]);
        map.insert("boxfo", &["bo'o", "bof"]);
        map.insert("boxna", &["bon", "bo'a"]);
        map.insert("bradi", &[] as &[&str]);
        map.insert("brano", &[] as &[&str]);
        map.insert("bratu", &[] as &[&str]);
        map.insert("bravi", &[] as &[&str]);
        map.insert("brazo", &["raz"]);
        map.insert("bredi", &["bre", "red"]);
        map.insert("bridi", &["bri"]);
        map.insert("brife", &["bif", "bi'e"]);
        map.insert("briju", &["bij"]);
        map.insert("brito", &["rit"]);
        map.insert("brivo", &[] as &[&str]);
        map.insert("broda", &["rod"]);
        map.insert("brode", &["bo'e"]);
        map.insert("brodi", &[] as &[&str]);
        map.insert("brodo", &[] as &[&str]);
        map.insert("brodu", &[] as &[&str]);
        map.insert("bruna", &["bu'a", "bun"]);
        map.insert("bu", &["bu'i", "bus"]);
        map.insert("bu'a", &["bul"]);
        map.insert("budjo", &["buj", "bu'o"]);
        map.insert("budza", &[] as &[&str]);
        map.insert("bukpu", &["bu'u", "buk"]);
        map.insert("bumru", &["bum"]);
        map.insert("bunda", &["bud"]);
        map.insert("bunre", &["bur", "bu'e"]);
        map.insert("buntu", &[] as &[&str]);
        map.insert("bunxa", &[] as &[&str]);
        map.insert("burcu", &["bru"]);
        map.insert("burka", &[] as &[&str]);
        map.insert("burna", &[] as &[&str]);
        map.insert("buvla", &[] as &[&str]);
        map.insert("ca'a", &["caz"]);
        map.insert("cabna", &["cab"]);
        map.insert("cabra", &["ca'a"]);
        map.insert("cacra", &[] as &[&str]);
        map.insert("cadga", &[] as &[&str]);
        map.insert("cadma", &[] as &[&str]);
        map.insert("cadzu", &["dzu"]);
        map.insert("cafne", &["caf"]);
        map.insert("cagna", &[] as &[&str]);
        map.insert("cajni", &[] as &[&str]);
        map.insert("cakla", &[] as &[&str]);
        map.insert("calku", &["cak"]);
        map.insert("calse", &[] as &[&str]);
        map.insert("campu", &[] as &[&str]);
        map.insert("canci", &[] as &[&str]);
        map.insert("cando", &["cad"]);
        map.insert("cange", &["cag"]);
        map.insert("canja", &["caj"]);
        map.insert("canko", &["ca'o"]);
        map.insert("canlu", &["ca'u", "cal"]);
        map.insert("canma", &[] as &[&str]);
        map.insert("canpa", &["cna"]);
        map.insert("canre", &["can"]);
        map.insert("canti", &[] as &[&str]);
        map.insert("carce", &[] as &[&str]);
        map.insert("carfu", &[] as &[&str]);
        map.insert("carmi", &["cam", "cai"]);
        map.insert("carna", &["car"]);
        map.insert("cartu", &["cat"]);
        map.insert("carvi", &["cav"]);
        map.insert("casnu", &["snu"]);
        map.insert("catke", &["ca'e"]);
        map.insert("catlu", &["cta"]);
        map.insert("catni", &["ca'i"]);
        map.insert("catra", &[] as &[&str]);
        map.insert("caxno", &["cax"]);
        map.insert("ce", &["cec"]);
        map.insert("cecla", &["ce'a", "cel"]);
        map.insert("cecmu", &["ce'u", "cem"]);
        map.insert("cedra", &[] as &[&str]);
        map.insert("ce'i", &["cez"]);
        map.insert("celdi", &["cle"]);
        map.insert("celxa", &[] as &[&str]);
        map.insert("cenba", &["cne"]);
        map.insert("cendo", &[] as &[&str]);
        map.insert("censa", &["ces"]);
        map.insert("centi", &["cen"]);
        map.insert("ce'o", &["ce'o"]);
        map.insert("cerda", &["ced"]);
        map.insert("cerni", &["cer"]);
        map.insert("certu", &["cre"]);
        map.insert("cevni", &["cev", "cei"]);
        map.insert("cfale", &[] as &[&str]);
        map.insert("cfari", &["cfa"]);
        map.insert("cfika", &["fi'a", "fik"]);
        map.insert("cfila", &["cfi"]);
        map.insert("cfine", &[] as &[&str]);
        map.insert("cfipu", &["fi'u"]);
        map.insert("ci", &["cib"]);
        map.insert("ciblu", &["blu"]);
        map.insert("cicna", &[] as &[&str]);
        map.insert("cidja", &["dja"]);
        map.insert("cidni", &["cid"]);
        map.insert("cidro", &["dro"]);
        map.insert("cifnu", &["cif"]);
        map.insert("cigla", &["cig"]);
        map.insert("cikna", &["cik"]);
        map.insert("cikre", &[] as &[&str]);
        map.insert("ciksi", &["cki"]);
        map.insert("cilce", &["cic"]);
        map.insert("cilfu", &[] as &[&str]);
        map.insert("cilmo", &["cim"]);
        map.insert("cilre", &["cli"]);
        map.insert("cilta", &["cil"]);
        map.insert("cimde", &[] as &[&str]);
        map.insert("cimle", &[] as &[&str]);
        map.insert("cimni", &[] as &[&str]);
        map.insert("cinba", &[] as &[&str]);
        map.insert("cindu", &[] as &[&str]);
        map.insert("cinfo", &[] as &[&str]);
        map.insert("cinje", &["cij"]);
        map.insert("cinki", &[] as &[&str]);
        map.insert("cinla", &[] as &[&str]);
        map.insert("cinmo", &["cni"]);
        map.insert("cinri", &["ci'i"]);
        map.insert("cinse", &["cin"]);
        map.insert("cinta", &[] as &[&str]);
        map.insert("cinza", &[] as &[&str]);
        map.insert("cipni", &["cpi"]);
        map.insert("cipra", &["cip"]);
        map.insert("cirko", &["cri"]);
        map.insert("cirla", &[] as &[&str]);
        map.insert("ciska", &["ci'a"]);
        map.insert("cisma", &[] as &[&str]);
        map.insert("cisni", &[] as &[&str]);
        map.insert("ciste", &["ci'e"]);
        map.insert("citka", &["cti"]);
        map.insert("citno", &["cit", "ci'o"]);
        map.insert("citri", &["cir"]);
        map.insert("citsi", &[] as &[&str]);
        map.insert("civla", &["civ"]);
        map.insert("cizra", &["ciz"]);
        map.insert("ckabu", &[] as &[&str]);
        map.insert("ckafi", &["kaf"]);
        map.insert("ckaji", &["kai"]);
        map.insert("ckana", &["cka"]);
        map.insert("ckape", &["cap"]);
        map.insert("ckasu", &["cas"]);
        map.insert("ckeji", &["kej", "cke"]);
        map.insert("ckiku", &["kik"]);
        map.insert("ckilu", &["ci'u"]);
        map.insert("ckini", &["ki'i"]);
        map.insert("ckire", &["kir"]);
        map.insert("ckule", &["kul", "cu'e"]);
        map.insert("ckunu", &["ku'u"]);
        map.insert("cladu", &["lau"]);
        map.insert("clafi", &[] as &[&str]);
        map.insert("clani", &["cla"]);
        map.insert("claxu", &["cau"]);
        map.insert("clenu", &[] as &[&str]);
        map.insert("cletu", &[] as &[&str]);
        map.insert("clika", &[] as &[&str]);
        map.insert("clinu", &[] as &[&str]);
        map.insert("clira", &["lir"]);
        map.insert("clite", &["lit"]);
        map.insert("cliva", &["li'a", "liv"]);
        map.insert("clupa", &["cup"]);
        map.insert("cmaci", &[] as &[&str]);
        map.insert("cmalu", &["cma"]);
        map.insert("cmana", &["ma'a"]);
        map.insert("cmavo", &["ma'o"]);
        map.insert("cmene", &["me'e", "cme"]);
        map.insert("cmeta", &[] as &[&str]);
        map.insert("cmevo", &[] as &[&str]);
        map.insert("cmila", &["mi'a"]);
        map.insert("cmima", &["mim", "cmi"]);
        map.insert("cmoni", &["co'i", "cmo"]);
        map.insert("cnano", &["na'o"]);
        map.insert("cnata", &[] as &[&str]);
        map.insert("cnebo", &["ne'o", "neb"]);
        map.insert("cnemu", &["ne'u", "nem"]);
        map.insert("cnici", &["nic"]);
        map.insert("cnida", &[] as &[&str]);
        map.insert("cnino", &["ni'o", "nin"]);
        map.insert("cnisa", &["nis"]);
        map.insert("cnita", &["nit", "ni'a"]);
        map.insert("co", &["col"]);
        map.insert("co'a", &["co'a"]);
        map.insert("co'e", &["co'e", "com"]);
        map.insert("cokcu", &["cko"]);
        map.insert("cokte", &[] as &[&str]);
        map.insert("condi", &["coi", "cno", "con"]);
        map.insert("conka", &[] as &[&str]);
        map.insert("corci", &["coc"]);
        map.insert("cortu", &["cro", "cor"]);
        map.insert("cotci", &[] as &[&str]);
        map.insert("co'u", &["co'u"]);
        map.insert("cpacu", &["cpa"]);
        map.insert("cpana", &[] as &[&str]);
        map.insert("cpare", &["par"]);
        map.insert("cpedu", &["cpe"]);
        map.insert("cpina", &[] as &[&str]);
        map.insert("cpixa", &[] as &[&str]);
        map.insert("cradi", &[] as &[&str]);
        map.insert("crami", &[] as &[&str]);
        map.insert("crane", &["cra"]);
        map.insert("cravi", &[] as &[&str]);
        map.insert("creka", &["cek"]);
        map.insert("crepu", &["rep"]);
        map.insert("cribe", &["rib"]);
        map.insert("crida", &["rid"]);
        map.insert("crino", &["ri'o"]);
        map.insert("cripu", &["rip"]);
        map.insert("crisa", &["cis"]);
        map.insert("critu", &[] as &[&str]);
        map.insert("ctaru", &[] as &[&str]);
        map.insert("ctebi", &["teb"]);
        map.insert("cteki", &["ce'i", "tek"]);
        map.insert("ctera", &[] as &[&str]);
        map.insert("ctile", &[] as &[&str]);
        map.insert("ctino", &["ti'o"]);
        map.insert("ctuca", &["ctu"]);
        map.insert("cukla", &["cuk"]);
        map.insert("cukre", &[] as &[&str]);
        map.insert("cukta", &["cku"]);
        map.insert("culno", &["clu"]);
        map.insert("cumba", &[] as &[&str]);
        map.insert("cumki", &["cu'i", "cum"]);
        map.insert("cumla", &["cul"]);
        map.insert("cunmi", &[] as &[&str]);
        map.insert("cunso", &["cun", "cu'o"]);
        map.insert("cuntu", &["cu'u"]);
        map.insert("cupra", &["pra"]);
        map.insert("curmi", &["cru"]);
        map.insert("curnu", &["cur"]);
        map.insert("curve", &["cuv"]);
        map.insert("cusku", &["sku", "cus"]);
        map.insert("cusna", &[] as &[&str]);
        map.insert("cutci", &["cuc"]);
        map.insert("cutne", &["cut"]);
        map.insert("cuxna", &["cux", "cu'a"]);
        map.insert("da", &["dav", "dza"]);
        map.insert("da'a", &["daz"]);
        map.insert("dacru", &["dac"]);
        map.insert("dacti", &["dai"]);
        map.insert("dadjo", &["daj"]);
        map.insert("dajbu", &[] as &[&str]);
        map.insert("dajne", &[] as &[&str]);
        map.insert("dakfu", &["dak"]);
        map.insert("dakli", &[] as &[&str]);
        map.insert("damba", &["dab", "da'a"]);
        map.insert("damri", &[] as &[&str]);
        map.insert("danci", &[] as &[&str]);
        map.insert("dandu", &["dad"]);
        map.insert("danfu", &["daf"]);
        map.insert("danke", &[] as &[&str]);
        map.insert("danlu", &["da'u", "dal"]);
        map.insert("danmo", &["dam"]);
        map.insert("danre", &["da'e"]);
        map.insert("dansu", &[] as &[&str]);
        map.insert("danti", &["dan"]);
        map.insert("daplu", &["plu"]);
        map.insert("dapma", &["dap"]);
        map.insert("darca", &[] as &[&str]);
        map.insert("dardu", &[] as &[&str]);
        map.insert("dargu", &["dag"]);
        map.insert("darlu", &["dau"]);
        map.insert("darno", &["da'o", "dar"]);
        map.insert("darsi", &[] as &[&str]);
        map.insert("darxi", &["dax", "da'i"]);
        map.insert("daski", &[] as &[&str]);
        map.insert("dasni", &["das"]);
        map.insert("daspo", &["spo"]);
        map.insert("dasri", &["sri"]);
        map.insert("datca", &[] as &[&str]);
        map.insert("datka", &[] as &[&str]);
        map.insert("datni", &[] as &[&str]);
        map.insert("datro", &[] as &[&str]);
        map.insert("datru", &[] as &[&str]);
        map.insert("datxo", &[] as &[&str]);
        map.insert("decti", &["dec"]);
        map.insert("degji", &["deg"]);
        map.insert("dejni", &["dej"]);
        map.insert("dekpu", &[] as &[&str]);
        map.insert("dekto", &["dek"]);
        map.insert("delca", &[] as &[&str]);
        map.insert("delno", &["de'o", "del"]);
        map.insert("delta", &[] as &[&str]);
        map.insert("dembi", &["deb"]);
        map.insert("denci", &["den", "de'i"]);
        map.insert("dendi", &[] as &[&str]);
        map.insert("denmi", &["dem"]);
        map.insert("denpa", &["dep", "de'a"]);
        map.insert("dertu", &["de'u", "der"]);
        map.insert("derxi", &["dre"]);
        map.insert("desku", &["des"]);
        map.insert("detri", &["det"]);
        map.insert("dicma", &[] as &[&str]);
        map.insert("dicra", &["dir"]);
        map.insert("didni", &[] as &[&str]);
        map.insert("digno", &[] as &[&str]);
        map.insert("dikca", &["dic"]);
        map.insert("diklo", &["klo"]);
        map.insert("dikni", &["dik"]);
        map.insert("dilcu", &[] as &[&str]);
        map.insert("dildo", &[] as &[&str]);
        map.insert("dilma", &[] as &[&str]);
        map.insert("dilnu", &["dil"]);
        map.insert("dimna", &["dim"]);
        map.insert("dindi", &[] as &[&str]);
        map.insert("dinju", &["di'u", "dij"]);
        map.insert("dinko", &["di'o"]);
        map.insert("dinso", &["dis"]);
        map.insert("dinti", &[] as &[&str]);
        map.insert("dirba", &["dib"]);
        map.insert("dirce", &["di'e"]);
        map.insert("dirgo", &["dig"]);
        map.insert("disko", &[] as &[&str]);
        map.insert("ditcu", &["dit"]);
        map.insert("divzi", &[] as &[&str]);
        map.insert("dizlo", &["diz", "dzi"]);
        map.insert("djacu", &["jac", "jau"]);
        map.insert("djedi", &["dje", "dei"]);
        map.insert("djica", &["dji"]);
        map.insert("djika", &[] as &[&str]);
        map.insert("djine", &["jin"]);
        map.insert("djuno", &["ju'o", "jun"]);
        map.insert("do", &["don", "doi"]);
        map.insert("dolna", &["dol"]);
        map.insert("donri", &["dor", "do'i"]);
        map.insert("dotco", &["dot", "do'o"]);
        map.insert("draci", &[] as &[&str]);
        map.insert("drani", &["dra"]);
        map.insert("drata", &["dat"]);
        map.insert("drisu", &[] as &[&str]);
        map.insert("drudi", &["dru", "rud"]);
        map.insert("du", &["dub", "du'o"]);
        map.insert("dugri", &["dug"]);
        map.insert("dukni", &[] as &[&str]);
        map.insert("dukse", &["dus", "du'e"]);
        map.insert("dukti", &["dut"]);
        map.insert("dunda", &["dud", "du'a"]);
        map.insert("dunja", &["duj"]);
        map.insert("dunku", &["du'u", "duk"]);
        map.insert("dunli", &["du'i", "dun"]);
        map.insert("dunra", &["dur"]);
        map.insert("durna", &[] as &[&str]);
        map.insert("dutso", &["tso"]);
        map.insert("du'u", &["dum"]);
        map.insert("dzama", &[] as &[&str]);
        map.insert("dzena", &["dze"]);
        map.insert("dzipo", &["zi'o", "zip"]);
        map.insert("dzoli", &["dzo"]);
        map.insert("facki", &["fak", "fa'i"]);
        map.insert("facni", &[] as &[&str]);
        map.insert("fadni", &["fad"]);
        map.insert("fagri", &["fag"]);
        map.insert("falnu", &["fan"]);
        map.insert("famti", &[] as &[&str]);
        map.insert("fancu", &[] as &[&str]);
        map.insert("fange", &[] as &[&str]);
        map.insert("fanji", &[] as &[&str]);
        map.insert("fanmo", &["fam", "fa'o"]);
        map.insert("fanri", &[] as &[&str]);
        map.insert("fanta", &[] as &[&str]);
        map.insert("fanva", &[] as &[&str]);
        map.insert("fanza", &["faz"]);
        map.insert("fapro", &["pro", "fap"]);
        map.insert("fardu", &[] as &[&str]);
        map.insert("farka", &[] as &[&str]);
        map.insert("farlu", &["fal", "fa'u"]);
        map.insert("farna", &["far", "fa'a"]);
        map.insert("farvi", &["fav"]);
        map.insert("fasnu", &["fau"]);
        map.insert("fatci", &["fac"]);
        map.insert("fatne", &["fa'e", "fat"]);
        map.insert("fatri", &["fai"]);
        map.insert("febvi", &["feb"]);
        map.insert("fegli", &[] as &[&str]);
        map.insert("femti", &["fem"]);
        map.insert("fendi", &["fed"]);
        map.insert("fenfa", &[] as &[&str]);
        map.insert("fengu", &["feg", "fe'u"]);
        map.insert("fenki", &["fek"]);
        map.insert("fenra", &["fer", "fe'a"]);
        map.insert("fenso", &["fe'o", "fen"]);
        map.insert("fepni", &["fei", "fep"]);
        map.insert("fepri", &[] as &[&str]);
        map.insert("ferti", &["fre"]);
        map.insert("festi", &["fes"]);
        map.insert("fetsi", &["fe'i", "fet"]);
        map.insert("fibra", &[] as &[&str]);
        map.insert("fidna", &["fid"]);
        map.insert("figre", &["fig"]);
        map.insert("filso", &["fis"]);
        map.insert("finpe", &["fi'e", "fip"]);
        map.insert("finti", &["fin", "fi'i"]);
        map.insert("firca", &[] as &[&str]);
        map.insert("fisli", &[] as &[&str]);
        map.insert("fizbu", &[] as &[&str]);
        map.insert("fizde", &["fiz"]);
        map.insert("flaci", &[] as &[&str]);
        map.insert("flalu", &["fla"]);
        map.insert("flani", &[] as &[&str]);
        map.insert("flecu", &["fle"]);
        map.insert("flese", &["les"]);
        map.insert("fliba", &["fli"]);
        map.insert("flipo", &[] as &[&str]);
        map.insert("flira", &["fir"]);
        map.insert("fo'a", &["fo'a"]);
        map.insert("fo'e", &["fo'e"]);
        map.insert("fo'i", &["fo'i"]);
        map.insert("foldi", &["flo", "foi"]);
        map.insert("fonmo", &["fom", "fo'o"]);
        map.insert("fonxa", &["fon"]);
        map.insert("forca", &["fro"]);
        map.insert("forse", &[] as &[&str]);
        map.insert("fraso", &["fas"]);
        map.insert("frati", &["fra"]);
        map.insert("fraxu", &["fax"]);
        map.insert("frica", &["fic"]);
        map.insert("friko", &["fi'o"]);
        map.insert("frili", &["fil"]);
        map.insert("frinu", &[] as &[&str]);
        map.insert("friti", &["fit"]);
        map.insert("frumu", &["fru"]);
        map.insert("fugvo", &[] as &[&str]);
        map.insert("fukpi", &["fuk", "fu'i"]);
        map.insert("fulta", &["ful", "flu"]);
        map.insert("funca", &["fun", "fu'a"]);
        map.insert("fusra", &["fur"]);
        map.insert("fuvla", &[] as &[&str]);
        map.insert("fuzme", &["fuz", "fu'e"]);
        map.insert("gacri", &["gai"]);
        map.insert("gadri", &["gad"]);
        map.insert("galfi", &["gaf", "ga'i"]);
        map.insert("galki", &[] as &[&str]);
        map.insert("galtu", &["gal", "ga'u"]);
        map.insert("galxe", &[] as &[&str]);
        map.insert("ganda", &[] as &[&str]);
        map.insert("ganlo", &["ga'o"]);
        map.insert("ganra", &["gan"]);
        map.insert("ganse", &["ga'e", "gas"]);
        map.insert("ganti", &[] as &[&str]);
        map.insert("ganvi", &[] as &[&str]);
        map.insert("ganxo", &["gax"]);
        map.insert("ganzu", &["gaz"]);
        map.insert("gapci", &["gac"]);
        map.insert("gapru", &["gap"]);
        map.insert("garna", &["gar"]);
        map.insert("gasnu", &["gau"]);
        map.insert("gaspo", &[] as &[&str]);
        map.insert("gasta", &["gat"]);
        map.insert("genja", &["gej"]);
        map.insert("gento", &["get", "ge'o"]);
        map.insert("genxu", &["gex"]);
        map.insert("gerku", &["ger", "ge'u"]);
        map.insert("gerna", &["gen", "ge'a"]);
        map.insert("gicmu", &[] as &[&str]);
        map.insert("gidva", &["gid", "gi'a"]);
        map.insert("gigdo", &["gi'o", "gig"]);
        map.insert("ginka", &["gik"]);
        map.insert("girzu", &["gir", "gri"]);
        map.insert("gismu", &["gi'u", "gim"]);
        map.insert("glare", &["gla"]);
        map.insert("gleki", &["gei", "gek"]);
        map.insert("gletu", &["gle", "let"]);
        map.insert("glico", &["gic", "gli"]);
        map.insert("glife", &[] as &[&str]);
        map.insert("glosa", &[] as &[&str]);
        map.insert("gluta", &["glu"]);
        map.insert("gocti", &["goc"]);
        map.insert("gomsi", &[] as &[&str]);
        map.insert("gonte", &[] as &[&str]);
        map.insert("gotro", &["got"]);
        map.insert("gradu", &["rau"]);
        map.insert("grafu", &[] as &[&str]);
        map.insert("grake", &["gra"]);
        map.insert("grame", &[] as &[&str]);
        map.insert("grana", &["ga'a"]);
        map.insert("grasu", &["ras"]);
        map.insert("grava", &["gav"]);
        map.insert("greku", &["rek"]);
        map.insert("grusi", &["rus"]);
        map.insert("grute", &["rut"]);
        map.insert("gubni", &["gub"]);
        map.insert("gugde", &["gu'e", "gug"]);
        map.insert("gugle", &[] as &[&str]);
        map.insert("gumri", &[] as &[&str]);
        map.insert("gundi", &["gud"]);
        map.insert("gunka", &["gun", "gu'a"]);
        map.insert("gunma", &["gum"]);
        map.insert("gunro", &["gu'o", "gur"]);
        map.insert("gunse", &[] as &[&str]);
        map.insert("gunta", &["gut"]);
        map.insert("gurni", &["gru"]);
        map.insert("guska", &["guk"]);
        map.insert("gusni", &["gus", "gu'i"]);
        map.insert("gusta", &[] as &[&str]);
        map.insert("gutci", &["guc"]);
        map.insert("gutra", &[] as &[&str]);
        map.insert("guzme", &["zme", "guz"]);
        map.insert("ja", &["jav"]);
        map.insert("jabre", &[] as &[&str]);
        map.insert("jadni", &["jad", "ja'i"]);
        map.insert("jai", &["jax"]);
        map.insert("jakne", &[] as &[&str]);
        map.insert("jaldi", &[] as &[&str]);
        map.insert("jalge", &["ja'e", "jag"]);
        map.insert("jalna", &[] as &[&str]);
        map.insert("jalra", &[] as &[&str]);
        map.insert("jamfu", &["jaf", "jma"]);
        map.insert("jamna", &["jam"]);
        map.insert("janbe", &["jab"]);
        map.insert("janco", &["jan"]);
        map.insert("janli", &["jal"]);
        map.insert("jansu", &["jas"]);
        map.insert("janta", &["jat"]);
        map.insert("jarbu", &[] as &[&str]);
        map.insert("jarco", &["ja'o"]);
        map.insert("jarki", &["jak"]);
        map.insert("jaspu", &["jap"]);
        map.insert("jatna", &["ja'a"]);
        map.insert("jatsu", &[] as &[&str]);
        map.insert("javni", &["jva"]);
        map.insert("jbama", &["bam"]);
        map.insert("jbari", &["jba"]);
        map.insert("jbena", &["jbe"]);
        map.insert("jbera", &["jer"]);
        map.insert("jbini", &["bin", "bi'i"]);
        map.insert("jbobo", &[] as &[&str]);
        map.insert("jdari", &["jar"]);
        map.insert("jdice", &["jdi"]);
        map.insert("jdika", &[] as &[&str]);
        map.insert("jdima", &["di'a"]);
        map.insert("jdini", &["din", "di'i"]);
        map.insert("jduli", &["jdu", "dul"]);
        map.insert("je", &["jev", "jve"]);
        map.insert("jecta", &["je'a", "jec"]);
        map.insert("jeftu", &["jef"]);
        map.insert("jegvo", &["jeg", "je'o"]);
        map.insert("jei", &["jez"]);
        map.insert("jelca", &["jel"]);
        map.insert("jemna", &["jme"]);
        map.insert("jenca", &["jen"]);
        map.insert("jendu", &["jed"]);
        map.insert("jenje", &[] as &[&str]);
        map.insert("jenmi", &["jei", "jem"]);
        map.insert("jensi", &[] as &[&str]);
        map.insert("jerna", &[] as &[&str]);
        map.insert("jersi", &["je'i"]);
        map.insert("jerxo", &["jex"]);
        map.insert("jesni", &["jes"]);
        map.insert("jetce", &["je'e"]);
        map.insert("jetnu", &["je'u", "jet"]);
        map.insert("jgalu", &["ja'u"]);
        map.insert("jganu", &["jga"]);
        map.insert("jgari", &["jai"]);
        map.insert("jgena", &["jge"]);
        map.insert("jgina", &["gin"]);
        map.insert("jgira", &["jgi"]);
        map.insert("jgita", &["git"]);
        map.insert("jguvi", &[] as &[&str]);
        map.insert("jibni", &["jbi"]);
        map.insert("jibri", &["jib"]);
        map.insert("jicfo", &[] as &[&str]);
        map.insert("jicla", &[] as &[&str]);
        map.insert("jicmu", &["cmu"]);
        map.insert("jidge", &["jid"]);
        map.insert("jijgi", &[] as &[&str]);
        map.insert("jijnu", &["jij"]);
        map.insert("jikca", &["jik"]);
        map.insert("jikfi", &[] as &[&str]);
        map.insert("jikni", &[] as &[&str]);
        map.insert("jikru", &[] as &[&str]);
        map.insert("jilka", &["jil"]);
        map.insert("jilra", &[] as &[&str]);
        map.insert("jimca", &["jic"]);
        map.insert("jimpe", &["jmi"]);
        map.insert("jimte", &["jit"]);
        map.insert("jinci", &[] as &[&str]);
        map.insert("jinda", &[] as &[&str]);
        map.insert("jinga", &["ji'a", "jig"]);
        map.insert("jinku", &[] as &[&str]);
        map.insert("jinme", &["jim"]);
        map.insert("jinru", &["jir"]);
        map.insert("jinsa", &["jis"]);
        map.insert("jinto", &[] as &[&str]);
        map.insert("jinvi", &["ji'i", "jiv"]);
        map.insert("jinzi", &["jiz"]);
        map.insert("jipci", &[] as &[&str]);
        map.insert("jipno", &["jip", "ji'o"]);
        map.insert("jirna", &[] as &[&str]);
        map.insert("jisra", &[] as &[&str]);
        map.insert("jitfa", &["jif"]);
        map.insert("jitni", &[] as &[&str]);
        map.insert("jitro", &["tro"]);
        map.insert("jivbu", &[] as &[&str]);
        map.insert("jivna", &["jvi"]);
        map.insert("jmaji", &["jaj"]);
        map.insert("jmice", &[] as &[&str]);
        map.insert("jmifa", &[] as &[&str]);
        map.insert("jmina", &["min"]);
        map.insert("jmite", &[] as &[&str]);
        map.insert("jmive", &["ji'e", "miv"]);
        map.insert("jo", &["jov"]);
        map.insert("jo'e", &["jom"]);
        map.insert("joi", &["jol", "joi"]);
        map.insert("jonse", &["jos"]);
        map.insert("jordo", &["jor", "jo'o"]);
        map.insert("jorne", &["jo'e", "jon"]);
        map.insert("jo'u", &["jo'u"]);
        map.insert("ju", &["juv"]);
        map.insert("jubme", &["jub", "jbu"]);
        map.insert("judri", &[] as &[&str]);
        map.insert("jufra", &["juf", "ju'a"]);
        map.insert("jukni", &["juk"]);
        map.insert("jukpa", &["jup"]);
        map.insert("julne", &["ju'e"]);
        map.insert("julro", &[] as &[&str]);
        map.insert("jundi", &["jud", "ju'i"]);
        map.insert("jungo", &["jug"]);
        map.insert("junla", &["jul"]);
        map.insert("junri", &["jur"]);
        map.insert("junta", &[] as &[&str]);
        map.insert("jurme", &["jum"]);
        map.insert("jursa", &["jus"]);
        map.insert("jutsi", &["jut"]);
        map.insert("juxre", &["jux"]);
        map.insert("jvinu", &["vin", "ji'u"]);
        map.insert("jviso", &[] as &[&str]);
        map.insert("ka", &["kam"]);
        map.insert("kabri", &[] as &[&str]);
        map.insert("kacma", &[] as &[&str]);
        map.insert("kadno", &[] as &[&str]);
        map.insert("kafke", &[] as &[&str]);
        map.insert("kagni", &["kag"]);
        map.insert("kajde", &["jde"]);
        map.insert("kajna", &[] as &[&str]);
        map.insert("kakne", &["ka'e"]);
        map.insert("kakpa", &[] as &[&str]);
        map.insert("kakti", &[] as &[&str]);
        map.insert("kalci", &[] as &[&str]);
        map.insert("kalri", &["kar"]);
        map.insert("kalsa", &["kas"]);
        map.insert("kalte", &["kat"]);
        map.insert("kamju", &[] as &[&str]);
        map.insert("kamni", &[] as &[&str]);
        map.insert("kampu", &["kau"]);
        map.insert("kamre", &[] as &[&str]);
        map.insert("kamro", &[] as &[&str]);
        map.insert("kanba", &[] as &[&str]);
        map.insert("kancu", &["kac"]);
        map.insert("kandi", &["kad"]);
        map.insert("kanji", &["kaj"]);
        map.insert("kanla", &["kal"]);
        map.insert("kanpe", &[] as &[&str]);
        map.insert("kanro", &["ka'o"]);
        map.insert("kansa", &["kan"]);
        map.insert("kantu", &["ka'u"]);
        map.insert("kanxe", &["kax"]);
        map.insert("kapli", &[] as &[&str]);
        map.insert("kapsi", &[] as &[&str]);
        map.insert("karbi", &["kab"]);
        map.insert("karce", &[] as &[&str]);
        map.insert("karda", &[] as &[&str]);
        map.insert("kargu", &[] as &[&str]);
        map.insert("karli", &[] as &[&str]);
        map.insert("karmo", &[] as &[&str]);
        map.insert("karni", &[] as &[&str]);
        map.insert("karpa", &[] as &[&str]);
        map.insert("katci", &[] as &[&str]);
        map.insert("katna", &["ka'a"]);
        map.insert("katso", &[] as &[&str]);
        map.insert("kavbu", &["kav"]);
        map.insert("kavzi", &[] as &[&str]);
        map.insert("kazmi", &[] as &[&str]);
        map.insert("kazra", &["kaz"]);
        map.insert("ke", &["kem"]);
        map.insert("kebzo", &[] as &[&str]);
        map.insert("kecti", &["kec", "ke'i"]);
        map.insert("ke'e", &["ke'e", "kep"]);
        map.insert("kei", &["kez"]);
        map.insert("kekli", &["kek"]);
        map.insert("kekti", &[] as &[&str]);
        map.insert("kelci", &["kel", "kei"]);
        map.insert("kelto", &[] as &[&str]);
        map.insert("kelvo", &["ke'o"]);
        map.insert("kenka", &[] as &[&str]);
        map.insert("kenra", &["ken"]);
        map.insert("kensa", &["kes"]);
        map.insert("kerfa", &["kre"]);
        map.insert("kerlo", &["ker"]);
        map.insert("kerni", &[] as &[&str]);
        map.insert("kesfi", &[] as &[&str]);
        map.insert("kesri", &[] as &[&str]);
        map.insert("ketco", &["ket", "tco"]);
        map.insert("ketli", &[] as &[&str]);
        map.insert("ketro", &[] as &[&str]);
        map.insert("ketsu", &[] as &[&str]);
        map.insert("kevna", &["ke'a", "kev"]);
        map.insert("kibro", &["kib"]);
        map.insert("kicne", &["ki'e", "kic"]);
        map.insert("kicra", &[] as &[&str]);
        map.insert("kijno", &["kij"]);
        map.insert("kilga", &[] as &[&str]);
        map.insert("kilto", &["ki'o"]);
        map.insert("kinda", &[] as &[&str]);
        map.insert("kinfi", &[] as &[&str]);
        map.insert("kinli", &["kil"]);
        map.insert("kinmu", &[] as &[&str]);
        map.insert("kinra", &[] as &[&str]);
        map.insert("kipsi", &[] as &[&str]);
        map.insert("kisto", &["kis"]);
        map.insert("klaji", &["laj"]);
        map.insert("klaku", &["kak"]);
        map.insert("klama", &["kla"]);
        map.insert("klani", &["lai"]);
        map.insert("klaso", &[] as &[&str]);
        map.insert("klesi", &["lei", "kle"]);
        map.insert("kliki", &[] as &[&str]);
        map.insert("klina", &["kli"]);
        map.insert("kliru", &[] as &[&str]);
        map.insert("kliti", &["kit"]);
        map.insert("kloje", &[] as &[&str]);
        map.insert("klupe", &["lu'e", "lup"]);
        map.insert("kluza", &["luz"]);
        map.insert("kobli", &["kob", "ko'i"]);
        map.insert("kogno", &[] as &[&str]);
        map.insert("kojna", &["koj", "ko'a"]);
        map.insert("kokso", &[] as &[&str]);
        map.insert("kolme", &["ko'e", "kol"]);
        map.insert("komcu", &["kom"]);
        map.insert("konju", &["kon", "ko'u"]);
        map.insert("konve", &[] as &[&str]);
        map.insert("korbi", &["kor", "koi"]);
        map.insert("korcu", &["kro"]);
        map.insert("korka", &["kok"]);
        map.insert("korvo", &[] as &[&str]);
        map.insert("kosmu", &[] as &[&str]);
        map.insert("kosta", &["kos"]);
        map.insert("krali", &[] as &[&str]);
        map.insert("kramu", &[] as &[&str]);
        map.insert("krasi", &["kra"]);
        map.insert("krati", &["ka'i"]);
        map.insert("krefu", &["ref", "ke'u"]);
        map.insert("krici", &["kri"]);
        map.insert("krili", &[] as &[&str]);
        map.insert("krinu", &["rin", "ki'u"]);
        map.insert("krixa", &["ki'a", "kix"]);
        map.insert("kroke", &[] as &[&str]);
        map.insert("kroxo", &[] as &[&str]);
        map.insert("kruca", &["kuc"]);
        map.insert("kruji", &["ruj"]);
        map.insert("kruvi", &["ruv", "kru"]);
        map.insert("ku'a", &["kuz"]);
        map.insert("kubli", &["kub"]);
        map.insert("kucli", &[] as &[&str]);
        map.insert("kufra", &["kuf"]);
        map.insert("kukru", &[] as &[&str]);
        map.insert("kukte", &["kuk"]);
        map.insert("kulnu", &["klu"]);
        map.insert("kumfa", &["ku'a", "kum"]);
        map.insert("kumte", &[] as &[&str]);
        map.insert("kunra", &["kun"]);
        map.insert("kunti", &["kut"]);
        map.insert("kurfa", &["kur"]);
        map.insert("kurji", &["ku'i", "kuj"]);
        map.insert("kurki", &[] as &[&str]);
        map.insert("kurti", &[] as &[&str]);
        map.insert("kuspe", &["kup", "ku'e"]);
        map.insert("kusru", &["kus"]);
        map.insert("labno", &[] as &[&str]);
        map.insert("lacni", &[] as &[&str]);
        map.insert("lacpu", &["lap", "cpu"]);
        map.insert("lacri", &["lac"]);
        map.insert("ladru", &["lad"]);
        map.insert("lafti", &["laf"]);
        map.insert("lakne", &["la'e"]);
        map.insert("lakse", &["lak"]);
        map.insert("laldo", &[] as &[&str]);
        map.insert("lalxu", &["la'u"]);
        map.insert("lamda", &[] as &[&str]);
        map.insert("lamdu", &[] as &[&str]);
        map.insert("lamji", &["la'i", "lam"]);
        map.insert("lanbi", &[] as &[&str]);
        map.insert("lanci", &[] as &[&str]);
        map.insert("landa", &[] as &[&str]);
        map.insert("lanka", &[] as &[&str]);
        map.insert("lanli", &["lal"]);
        map.insert("lanme", &["lan"]);
        map.insert("lanru", &[] as &[&str]);
        map.insert("lante", &[] as &[&str]);
        map.insert("lanxe", &["lax"]);
        map.insert("lanzu", &["laz"]);
        map.insert("larcu", &["lar"]);
        map.insert("larva", &[] as &[&str]);
        map.insert("lasna", &["la'a"]);
        map.insert("lastu", &[] as &[&str]);
        map.insert("latmo", &["la'o"]);
        map.insert("latna", &[] as &[&str]);
        map.insert("laxte", &[] as &[&str]);
        map.insert("lazni", &[] as &[&str]);
        map.insert("lebna", &["le'a", "leb"]);
        map.insert("le'e", &["lem"]);
        map.insert("lelxe", &[] as &[&str]);
        map.insert("lenga", &[] as &[&str]);
        map.insert("lengu", &[] as &[&str]);
        map.insert("lenjo", &["len", "le'o"]);
        map.insert("lenku", &["lek"]);
        map.insert("lerci", &["lec"]);
        map.insert("lerfu", &["le'u", "ler"]);
        map.insert("letci", &[] as &[&str]);
        map.insert("libjo", &["lib"]);
        map.insert("lidne", &["li'e"]);
        map.insert("lifri", &["lif", "fri"]);
        map.insert("ligma", &[] as &[&str]);
        map.insert("li'i", &["liz"]);
        map.insert("lijda", &["jda"]);
        map.insert("likse", &[] as &[&str]);
        map.insert("limfa", &[] as &[&str]);
        map.insert("limna", &["lim"]);
        map.insert("lince", &[] as &[&str]);
        map.insert("lindi", &["lid"]);
        map.insert("linga", &[] as &[&str]);
        map.insert("linji", &["li'i", "lij"]);
        map.insert("linme", &[] as &[&str]);
        map.insert("linsi", &["lin"]);
        map.insert("linto", &["li'o"]);
        map.insert("lisri", &["lis"]);
        map.insert("liste", &["ste"]);
        map.insert("litce", &["lic"]);
        map.insert("litki", &["lik"]);
        map.insert("litru", &["li'u"]);
        map.insert("livga", &[] as &[&str]);
        map.insert("livla", &["lil"]);
        map.insert("lo'e", &["lom"]);
        map.insert("logji", &["loj"]);
        map.insert("loglo", &[] as &[&str]);
        map.insert("lojbo", &["lob", "jbo"]);
        map.insert("lojgo", &[] as &[&str]);
        map.insert("lokra", &[] as &[&str]);
        map.insert("loldi", &["loi", "lol"]);
        map.insert("lorxu", &["lo'u", "lor"]);
        map.insert("losto", &[] as &[&str]);
        map.insert("lubma", &[] as &[&str]);
        map.insert("lubno", &["lu'o"]);
        map.insert("lucpa", &[] as &[&str]);
        map.insert("lujvo", &["luv", "jvo"]);
        map.insert("luksi", &["luk"]);
        map.insert("lumci", &["lu'i", "lum"]);
        map.insert("lunbe", &["lub"]);
        map.insert("lungo", &[] as &[&str]);
        map.insert("lunra", &["lur"]);
        map.insert("lunsa", &["lus"]);
        map.insert("luska", &[] as &[&str]);
        map.insert("lusto", &[] as &[&str]);
        map.insert("mabla", &["mal"]);
        map.insert("mabru", &["mab"]);
        map.insert("macnu", &["cnu"]);
        map.insert("majga", &[] as &[&str]);
        map.insert("majvu", &[] as &[&str]);
        map.insert("makcu", &["ma'u"]);
        map.insert("makfa", &["maf"]);
        map.insert("maksi", &["mak"]);
        map.insert("malsi", &["mas"]);
        map.insert("maltu", &[] as &[&str]);
        map.insert("malve", &[] as &[&str]);
        map.insert("mamta", &["mam"]);
        map.insert("manci", &["mac"]);
        map.insert("manfo", &[] as &[&str]);
        map.insert("mango", &[] as &[&str]);
        map.insert("manku", &["man"]);
        map.insert("manri", &["mar"]);
        map.insert("mansa", &[] as &[&str]);
        map.insert("manti", &[] as &[&str]);
        map.insert("manva", &[] as &[&str]);
        map.insert("mapku", &["map"]);
        map.insert("mapni", &[] as &[&str]);
        map.insert("mapra", &[] as &[&str]);
        map.insert("mapti", &["mat"]);
        map.insert("marbi", &["mra"]);
        map.insert("marce", &["ma'e"]);
        map.insert("marde", &["mad"]);
        map.insert("margu", &["mag"]);
        map.insert("marji", &["maj", "mai"]);
        map.insert("marna", &[] as &[&str]);
        map.insert("marxa", &["max"]);
        map.insert("maska", &[] as &[&str]);
        map.insert("masno", &["sno"]);
        map.insert("masti", &["ma'i"]);
        map.insert("matci", &[] as &[&str]);
        map.insert("matli", &[] as &[&str]);
        map.insert("matne", &[] as &[&str]);
        map.insert("matra", &[] as &[&str]);
        map.insert("matxe", &[] as &[&str]);
        map.insert("mavji", &["mav"]);
        map.insert("maxri", &["xri"]);
        map.insert("mebri", &["meb"]);
        map.insert("medzo", &[] as &[&str]);
        map.insert("megdo", &["meg"]);
        map.insert("mei", &["mem", "mei"]);
        map.insert("mekso", &["me'o", "mek"]);
        map.insert("melbi", &["mle", "mel"]);
        map.insert("meljo", &["mej"]);
        map.insert("melmi", &[] as &[&str]);
        map.insert("menli", &["men"]);
        map.insert("menre", &[] as &[&str]);
        map.insert("mensi", &["me'i", "mes"]);
        map.insert("mentu", &["met", "me'u"]);
        map.insert("merko", &["mer"]);
        map.insert("merli", &["mre"]);
        map.insert("mespo", &[] as &[&str]);
        map.insert("metfo", &[] as &[&str]);
        map.insert("metro", &[] as &[&str]);
        map.insert("mexno", &["mex"]);
        map.insert("mi", &["mib"]);
        map.insert("midju", &["mij"]);
        map.insert("mifra", &["mif"]);
        map.insert("mikce", &["mic"]);
        map.insert("mikri", &["mik"]);
        map.insert("milti", &["mil"]);
        map.insert("milxe", &["mli"]);
        map.insert("mimta", &[] as &[&str]);
        map.insert("minde", &["mi'e", "mid"]);
        map.insert("minji", &["mi'i"]);
        map.insert("minli", &[] as &[&str]);
        map.insert("minra", &["mir"]);
        map.insert("mintu", &["mi'u", "mit"]);
        map.insert("mipri", &["mip"]);
        map.insert("mirli", &[] as &[&str]);
        map.insert("misno", &["mi'o", "mis"]);
        map.insert("misro", &[] as &[&str]);
        map.insert("miste", &[] as &[&str]);
        map.insert("mitre", &["tre"]);
        map.insert("mixre", &["mix", "xre"]);
        map.insert("mlana", &["mla"]);
        map.insert("mlatu", &["lat"]);
        map.insert("mleca", &["mec", "me'a"]);
        map.insert("mledi", &["led"]);
        map.insert("mluni", &["lun"]);
        map.insert("mo'a", &["mob"]);
        map.insert("modju", &[] as &[&str]);
        map.insert("modzi", &[] as &[&str]);
        map.insert("mogle", &[] as &[&str]);
        map.insert("mo'i", &["mov"]);
        map.insert("moi", &["mom", "moi"]);
        map.insert("mokca", &["moc"]);
        map.insert("moklu", &["mo'u", "mol"]);
        map.insert("molki", &["mlo"]);
        map.insert("molro", &["mo'o"]);
        map.insert("morji", &["mo'i", "moj"]);
        map.insert("morko", &["mor"]);
        map.insert("mormo", &[] as &[&str]);
        map.insert("morna", &["mo'a", "mon"]);
        map.insert("morsi", &["mro"]);
        map.insert("mosra", &["mos"]);
        map.insert("moxna", &[] as &[&str]);
        map.insert("mraji", &[] as &[&str]);
        map.insert("mrilu", &["mri"]);
        map.insert("mruli", &["mru"]);
        map.insert("mu", &["mum"]);
        map.insert("mucti", &["mut"]);
        map.insert("mudri", &["mud"]);
        map.insert("mu'e", &["muf"]);
        map.insert("mugle", &[] as &[&str]);
        map.insert("mukti", &["mu'i", "muk"]);
        map.insert("mulno", &["mu'o", "mul"]);
        map.insert("munje", &["mu'e", "muj"]);
        map.insert("mupli", &["mup"]);
        map.insert("murse", &[] as &[&str]);
        map.insert("murta", &["mur", "mu'a"]);
        map.insert("muslo", &["mus"]);
        map.insert("mutce", &["tce"]);
        map.insert("muvdu", &["muv", "mu'u"]);
        map.insert("muzga", &["muz"]);
        map.insert("na", &["nar"]);
        map.insert("nabmi", &["nam"]);
        map.insert("na'e", &["nal"]);
        map.insert("nakni", &["nak"]);
        map.insert("nalci", &["na'i"]);
        map.insert("nalfi", &[] as &[&str]);
        map.insert("nalti", &[] as &[&str]);
        map.insert("namcu", &["nac", "na'u"]);
        map.insert("namra", &[] as &[&str]);
        map.insert("nanba", &["nab"]);
        map.insert("nanca", &["na'a"]);
        map.insert("nandu", &["nad"]);
        map.insert("nanla", &[] as &[&str]);
        map.insert("nanmu", &["nau"]);
        map.insert("nanvi", &["nav"]);
        map.insert("narge", &["nag"]);
        map.insert("narju", &["naj"]);
        map.insert("natfe", &["na'e", "naf"]);
        map.insert("natmi", &["nat", "nai"]);
        map.insert("natsi", &[] as &[&str]);
        map.insert("navni", &[] as &[&str]);
        map.insert("naxle", &["nax", "xle"]);
        map.insert("nazbi", &["zbi", "naz"]);
        map.insert("nedlo", &[] as &[&str]);
        map.insert("nejni", &["nen"]);
        map.insert("nelci", &["nei", "nel"]);
        map.insert("nenmu", &[] as &[&str]);
        map.insert("nenri", &["ne'i", "ner"]);
        map.insert("nerde", &[] as &[&str]);
        map.insert("ni", &["nil"]);
        map.insert("nibli", &["ni'i", "nib"]);
        map.insert("nicfa", &["nif"]);
        map.insert("niclu", &[] as &[&str]);
        map.insert("nicte", &["cte"]);
        map.insert("nikle", &["nik"]);
        map.insert("nilce", &["ni'e"]);
        map.insert("nimre", &[] as &[&str]);
        map.insert("ninja", &[] as &[&str]);
        map.insert("ninmu", &["nim", "ni'u"]);
        map.insert("nirna", &["nir"]);
        map.insert("nitcu", &["tcu"]);
        map.insert("nivji", &["niv"]);
        map.insert("nixli", &["xli", "nix"]);
        map.insert("no", &["non"]);
        map.insert("nobli", &["no'i", "nol"]);
        map.insert("no'e", &["nor", "no'e"]);
        map.insert("nonka", &["nok"]);
        map.insert("nonmu", &[] as &[&str]);
        map.insert("nordo", &[] as &[&str]);
        map.insert("norgo", &[] as &[&str]);
        map.insert("notci", &["not", "noi"]);
        map.insert("nu", &["nun"]);
        map.insert("nudle", &[] as &[&str]);
        map.insert("nukni", &["nuk"]);
        map.insert("nuktu", &[] as &[&str]);
        map.insert("nulpa", &[] as &[&str]);
        map.insert("numje", &[] as &[&str]);
        map.insert("nunmu", &[] as &[&str]);
        map.insert("nu'o", &["nu'o"]);
        map.insert("nupre", &["nup", "nu'e"]);
        map.insert("nurma", &["num"]);
        map.insert("nusna", &[] as &[&str]);
        map.insert("nutka", &[] as &[&str]);
        map.insert("nutko", &[] as &[&str]);
        map.insert("nutli", &["nul", "nu'i"]);
        map.insert("nuzba", &["nuz"]);
        map.insert("nuzlo", &[] as &[&str]);
        map.insert("pa", &["pav"]);
        map.insert("pacna", &["pa'a"]);
        map.insert("pagbu", &["pau", "pag"]);
        map.insert("pagre", &["gre"]);
        map.insert("pagzu", &[] as &[&str]);
        map.insert("pajni", &["pai"]);
        map.insert("palci", &["pac"]);
        map.insert("palku", &["pak"]);
        map.insert("palma", &[] as &[&str]);
        map.insert("palne", &[] as &[&str]);
        map.insert("palpi", &[] as &[&str]);
        map.insert("palta", &[] as &[&str]);
        map.insert("pambe", &[] as &[&str]);
        map.insert("pamga", &[] as &[&str]);
        map.insert("panci", &["pan"]);
        map.insert("pandi", &["pad"]);
        map.insert("panje", &[] as &[&str]);
        map.insert("panka", &[] as &[&str]);
        map.insert("panlo", &["pa'o"]);
        map.insert("panpi", &["pap"]);
        map.insert("panra", &[] as &[&str]);
        map.insert("pante", &["pat"]);
        map.insert("panzi", &["paz"]);
        map.insert("papri", &[] as &[&str]);
        map.insert("parbi", &["pab"]);
        map.insert("pardu", &[] as &[&str]);
        map.insert("parji", &[] as &[&str]);
        map.insert("paska", &[] as &[&str]);
        map.insert("pastu", &["pas"]);
        map.insert("patfu", &["paf", "pa'u"]);
        map.insert("patlu", &[] as &[&str]);
        map.insert("patxu", &["pax"]);
        map.insert("paxra", &[] as &[&str]);
        map.insert("paznu", &[] as &[&str]);
        map.insert("pe'a", &["pev"]);
        map.insert("pegva", &["peg"]);
        map.insert("pelji", &["ple"]);
        map.insert("pelxu", &["pel"]);
        map.insert("pemci", &["pem"]);
        map.insert("penbi", &["peb"]);
        map.insert("pencu", &["pe'u", "pec"]);
        map.insert("pendo", &["ped", "pe'o"]);
        map.insert("penka", &[] as &[&str]);
        map.insert("penki", &[] as &[&str]);
        map.insert("penmi", &["pen", "pe'i"]);
        map.insert("pensi", &["pei", "pes"]);
        map.insert("pentu", &[] as &[&str]);
        map.insert("pepsi", &[] as &[&str]);
        map.insert("perli", &["per"]);
        map.insert("pesxu", &["pex"]);
        map.insert("petso", &["pet"]);
        map.insert("pevna", &[] as &[&str]);
        map.insert("pezli", &["pez"]);
        map.insert("pi", &["piz"]);
        map.insert("picti", &["pic"]);
        map.insert("pijne", &[] as &[&str]);
        map.insert("pikci", &[] as &[&str]);
        map.insert("pikpi", &[] as &[&str]);
        map.insert("pikta", &[] as &[&str]);
        map.insert("pilda", &[] as &[&str]);
        map.insert("pilji", &["pi'i"]);
        map.insert("pilka", &["pil", "pi'a"]);
        map.insert("pilno", &["pli"]);
        map.insert("pimlu", &["pim", "pi'u"]);
        map.insert("pinca", &[] as &[&str]);
        map.insert("pindi", &["pid"]);
        map.insert("pinfu", &["pif"]);
        map.insert("Pingo", &[] as &[&str]);
        map.insert("pinji", &[] as &[&str]);
        map.insert("pinka", &["pik"]);
        map.insert("pinsi", &["pis"]);
        map.insert("pinta", &["pin"]);
        map.insert("pinxe", &["pix"]);
        map.insert("pipno", &["pi'o"]);
        map.insert("pirxo", &[] as &[&str]);
        map.insert("pitsa", &[] as &[&str]);
        map.insert("pi'u", &["piv"]);
        map.insert("pixra", &["xra", "pir"]);
        map.insert("plana", &[] as &[&str]);
        map.insert("platu", &["pla"]);
        map.insert("pleji", &["le'i", "lej"]);
        map.insert("plibu", &["pib"]);
        map.insert("plini", &[] as &[&str]);
        map.insert("plipe", &["pi'e", "pip"]);
        map.insert("plise", &[] as &[&str]);
        map.insert("plita", &["pit"]);
        map.insert("plixa", &["lix"]);
        map.insert("pluja", &["luj"]);
        map.insert("pluka", &["pu'a", "puk"]);
        map.insert("pluna", &[] as &[&str]);
        map.insert("pluta", &["lut", "lu'a"]);
        map.insert("pocli", &[] as &[&str]);
        map.insert("polje", &["plo"]);
        map.insert("polno", &["pol"]);
        map.insert("ponjo", &["pon", "po'o"]);
        map.insert("ponse", &["po'e", "pos"]);
        map.insert("poplu", &[] as &[&str]);
        map.insert("porno", &[] as &[&str]);
        map.insert("porpi", &["pop", "po'i"]);
        map.insert("porsi", &["poi", "por"]);
        map.insert("porto", &["pot"]);
        map.insert("prali", &["pal"]);
        map.insert("prami", &["pa'i", "pam"]);
        map.insert("prane", &["pa'e"]);
        map.insert("predi", &[] as &[&str]);
        map.insert("preja", &["pej", "pe'a"]);
        map.insert("premi", &[] as &[&str]);
        map.insert("prenu", &["pre"]);
        map.insert("preri", &[] as &[&str]);
        map.insert("preti", &["ret", "rei"]);
        map.insert("prije", &["pij"]);
        map.insert("prina", &["pri"]);
        map.insert("pritu", &[] as &[&str]);
        map.insert("proga", &["pog"]);
        map.insert("proji", &[] as &[&str]);
        map.insert("prosa", &["ros", "ro'a"]);
        map.insert("pruce", &["ru'e", "ruc"]);
        map.insert("pruni", &["pun"]);
        map.insert("pruri", &[] as &[&str]);
        map.insert("pruxi", &["ru'i", "rux"]);
        map.insert("pu'i", &["pus"]);
        map.insert("pulce", &["puc", "pu'e"]);
        map.insert("pulji", &[] as &[&str]);
        map.insert("pulni", &[] as &[&str]);
        map.insert("punji", &["pu'i", "puj"]);
        map.insert("punli", &["pul"]);
        map.insert("pupsu", &["pup"]);
        map.insert("purci", &["pur", "pru"]);
        map.insert("purdi", &["pud"]);
        map.insert("purmo", &["pum", "pu'o"]);
        map.insert("purni", &[] as &[&str]);
        map.insert("pu'u", &["puv"]);
        map.insert("puvza", &[] as &[&str]);
        map.insert("racli", &[] as &[&str]);
        map.insert("ractu", &[] as &[&str]);
        map.insert("radno", &["ra'o"]);
        map.insert("rafsi", &["raf"]);
        map.insert("ragbi", &[] as &[&str]);
        map.insert("ragve", &["rav"]);
        map.insert("rakle", &[] as &[&str]);
        map.insert("rakso", &[] as &[&str]);
        map.insert("raktu", &["ra'u"]);
        map.insert("ralci", &["rac"]);
        map.insert("ralju", &["ral"]);
        map.insert("ralte", &["ra'e"]);
        map.insert("randa", &["rad"]);
        map.insert("rango", &["rag"]);
        map.insert("ranji", &["ra'i"]);
        map.insert("ranlu", &[] as &[&str]);
        map.insert("ranmi", &["ram"]);
        map.insert("ransu", &[] as &[&str]);
        map.insert("ranti", &["ran"]);
        map.insert("ranxi", &["rax"]);
        map.insert("rapli", &["rap"]);
        map.insert("rarna", &["rar"]);
        map.insert("ratcu", &[] as &[&str]);
        map.insert("ratma", &[] as &[&str]);
        map.insert("ratni", &["rat"]);
        map.insert("re", &["rel"]);
        map.insert("rebla", &["reb"]);
        map.insert("rectu", &["rec", "re'u"]);
        map.insert("reksa", &[] as &[&str]);
        map.insert("rekto", &[] as &[&str]);
        map.insert("remna", &["rem", "re'a"]);
        map.insert("renro", &["rer", "re'o"]);
        map.insert("renvi", &["re'i", "rev"]);
        map.insert("respa", &["res"]);
        map.insert("rexsa", &["rex"]);
        map.insert("ribga", &[] as &[&str]);
        map.insert("ricfu", &["rif", "cfu"]);
        map.insert("rigni", &["rig"]);
        map.insert("rijno", &["rij"]);
        map.insert("rikro", &[] as &[&str]);
        map.insert("rilti", &["ril"]);
        map.insert("rimni", &["rim"]);
        map.insert("rinci", &[] as &[&str]);
        map.insert("rindo", &[] as &[&str]);
        map.insert("rinju", &["ri'u"]);
        map.insert("rinka", &["ri'a", "rik"]);
        map.insert("rinsa", &[] as &[&str]);
        map.insert("ripto", &[] as &[&str]);
        map.insert("rirci", &[] as &[&str]);
        map.insert("rirli", &[] as &[&str]);
        map.insert("rirni", &["rir"]);
        map.insert("rirxe", &["ri'e"]);
        map.insert("rismi", &["ris"]);
        map.insert("risna", &[] as &[&str]);
        map.insert("ritli", &["ri'i"]);
        map.insert("rivbi", &["riv"]);
        map.insert("ro", &["rol"]);
        map.insert("roi", &["rom", "roi"]);
        map.insert("rokci", &["rok", "ro'i"]);
        map.insert("romge", &["rog"]);
        map.insert("romlo", &[] as &[&str]);
        map.insert("ronci", &["roc"]);
        map.insert("ronro", &[] as &[&str]);
        map.insert("ronsa", &[] as &[&str]);
        map.insert("ronte", &[] as &[&str]);
        map.insert("ronti", &[] as &[&str]);
        map.insert("ropno", &["ron", "ro'o"]);
        map.insert("rorci", &["ror"]);
        map.insert("rotsu", &["ro'u", "rot", "tsu"]);
        map.insert("rozgu", &["roz", "zgu"]);
        map.insert("ruble", &["ble", "rub"]);
        map.insert("rucni", &[] as &[&str]);
        map.insert("rufsu", &["ruf"]);
        map.insert("runme", &["rum"]);
        map.insert("runta", &[] as &[&str]);
        map.insert("rupnu", &["rup", "ru'u"]);
        map.insert("rusko", &["ru'o", "ruk"]);
        map.insert("rutni", &["run"]);
        map.insert("sabji", &["sab"]);
        map.insert("sabnu", &[] as &[&str]);
        map.insert("sacki", &[] as &[&str]);
        map.insert("saclu", &[] as &[&str]);
        map.insert("sacni", &[] as &[&str]);
        map.insert("sadjo", &["djo"]);
        map.insert("sakci", &["sak"]);
        map.insert("sakli", &["sal"]);
        map.insert("sakta", &["sat"]);
        map.insert("salci", &["sla"]);
        map.insert("salmo", &[] as &[&str]);
        map.insert("salni", &[] as &[&str]);
        map.insert("salpo", &["sa'o"]);
        map.insert("salri", &[] as &[&str]);
        map.insert("salta", &[] as &[&str]);
        map.insert("samcu", &[] as &[&str]);
        map.insert("sampu", &["sap"]);
        map.insert("sanbu", &[] as &[&str]);
        map.insert("sance", &["sna"]);
        map.insert("sanga", &["sa'a", "sag"]);
        map.insert("sanji", &["saj"]);
        map.insert("sanli", &["sa'i"]);
        map.insert("sanmi", &["sai"]);
        map.insert("sanra", &[] as &[&str]);
        map.insert("sanso", &[] as &[&str]);
        map.insert("santa", &[] as &[&str]);
        map.insert("sarcu", &["sa'u"]);
        map.insert("sarji", &["sra"]);
        map.insert("sarlu", &[] as &[&str]);
        map.insert("sarni", &[] as &[&str]);
        map.insert("sarxe", &["sax"]);
        map.insert("saske", &["ske"]);
        map.insert("satci", &[] as &[&str]);
        map.insert("satre", &["sa'e"]);
        map.insert("savru", &["vru", "sav"]);
        map.insert("sazri", &["saz"]);
        map.insert("se", &["sel"]);
        map.insert("sefsi", &[] as &[&str]);
        map.insert("sefta", &["sfe"]);
        map.insert("sekre", &[] as &[&str]);
        map.insert("selci", &["sle"]);
        map.insert("selfu", &["se'u", "sef"]);
        map.insert("semto", &["sme"]);
        map.insert("senci", &["sec"]);
        map.insert("sengi", &[] as &[&str]);
        map.insert("senpi", &["sen"]);
        map.insert("senta", &["set"]);
        map.insert("senva", &["sne", "sev"]);
        map.insert("sepli", &["sep", "sei"]);
        map.insert("sepre", &[] as &[&str]);
        map.insert("serti", &["ser"]);
        map.insert("sesre", &[] as &[&str]);
        map.insert("setca", &["se'a"]);
        map.insert("sevzi", &["se'i", "sez"]);
        map.insert("sezni", &[] as &[&str]);
        map.insert("sfani", &[] as &[&str]);
        map.insert("sfasa", &["sfa"]);
        map.insert("sfero", &[] as &[&str]);
        map.insert("sfite", &["sfi"]);
        map.insert("sfofa", &["sfo"]);
        map.insert("sfopu", &["fop", "fo'u"]);
        map.insert("sfubu", &["sub", "su'u"]);
        map.insert("sibli", &[] as &[&str]);
        map.insert("siclu", &["sil"]);
        map.insert("sicni", &["si'i"]);
        map.insert("sicpi", &[] as &[&str]);
        map.insert("sidbo", &["si'o", "sib"]);
        map.insert("sidju", &["dju"]);
        map.insert("sigda", &[] as &[&str]);
        map.insert("sigja", &["sig"]);
        map.insert("sigma", &[] as &[&str]);
        map.insert("sikta", &[] as &[&str]);
        map.insert("silja", &[] as &[&str]);
        map.insert("silka", &["sik"]);
        map.insert("silna", &[] as &[&str]);
        map.insert("silru", &[] as &[&str]);
        map.insert("simlu", &["mlu"]);
        map.insert("simsa", &["smi"]);
        map.insert("simxu", &["si'u", "sim"]);
        map.insert("since", &[] as &[&str]);
        map.insert("sinma", &["si'a"]);
        map.insert("sinso", &[] as &[&str]);
        map.insert("sinxa", &["sni"]);
        map.insert("si'o", &["siz"]);
        map.insert("sipna", &["sip"]);
        map.insert("sirji", &["sir"]);
        map.insert("sirxo", &["six"]);
        map.insert("sisku", &["sis"]);
        map.insert("sisti", &["sti"]);
        map.insert("sitla", &[] as &[&str]);
        map.insert("sitna", &["sit"]);
        map.insert("sivni", &["siv"]);
        map.insert("sizgo", &[] as &[&str]);
        map.insert("skaci", &[] as &[&str]);
        map.insert("skami", &["sam"]);
        map.insert("skano", &[] as &[&str]);
        map.insert("skapi", &["kap"]);
        map.insert("skari", &["ska"]);
        map.insert("skicu", &["ski"]);
        map.insert("skifa", &[] as &[&str]);
        map.insert("skiji", &["sij"]);
        map.insert("skina", &["kin"]);
        map.insert("skori", &["sko"]);
        map.insert("skoto", &["ko'o", "kot"]);
        map.insert("skuba", &[] as &[&str]);
        map.insert("skudi", &[] as &[&str]);
        map.insert("skuna", &[] as &[&str]);
        map.insert("skuro", &["ku'o"]);
        map.insert("slabu", &["sau"]);
        map.insert("slaka", &[] as &[&str]);
        map.insert("slami", &[] as &[&str]);
        map.insert("slanu", &[] as &[&str]);
        map.insert("slari", &["sar"]);
        map.insert("slasi", &["las"]);
        map.insert("sligu", &["lig"]);
        map.insert("slilu", &["sli"]);
        map.insert("sliri", &[] as &[&str]);
        map.insert("slovo", &["lo'o", "lov"]);
        map.insert("sluji", &["slu"]);
        map.insert("sluni", &[] as &[&str]);
        map.insert("smacu", &[] as &[&str]);
        map.insert("smadi", &[] as &[&str]);
        map.insert("smaji", &["sma"]);
        map.insert("smaka", &[] as &[&str]);
        map.insert("smani", &[] as &[&str]);
        map.insert("smela", &[] as &[&str]);
        map.insert("smoka", &["smo"]);
        map.insert("smuci", &["muc"]);
        map.insert("smuni", &["smu", "mun"]);
        map.insert("smusu", &[] as &[&str]);
        map.insert("snada", &["sad"]);
        map.insert("snafu", &[] as &[&str]);
        map.insert("snanu", &["nan"]);
        map.insert("snavi", &[] as &[&str]);
        map.insert("snidu", &["nid"]);
        map.insert("sniju", &[] as &[&str]);
        map.insert("snime", &["si'e"]);
        map.insert("snipa", &["nip"]);
        map.insert("snuji", &["nuj"]);
        map.insert("snura", &["nu'a", "nur"]);
        map.insert("snuti", &["nut"]);
        map.insert("so", &["soz"]);
        map.insert("so'a", &["soj"]);
        map.insert("sobde", &["so'e", "sob"]);
        map.insert("socni", &[] as &[&str]);
        map.insert("sodna", &[] as &[&str]);
        map.insert("sodva", &["sod"]);
        map.insert("so'e", &["sop"]);
        map.insert("softo", &["sof"]);
        map.insert("so'i", &["so'i", "sor"]);
        map.insert("solji", &["slo"]);
        map.insert("solri", &["sol"]);
        map.insert("sombo", &["som", "so'o"]);
        map.insert("sonci", &["soi", "son"]);
        map.insert("sondu", &[] as &[&str]);
        map.insert("so'o", &["sos"]);
        map.insert("sorcu", &["sro", "soc"]);
        map.insert("sorgu", &["sog"]);
        map.insert("sorni", &[] as &[&str]);
        map.insert("sorta", &[] as &[&str]);
        map.insert("so'u", &["sot"]);
        map.insert("sovda", &["so'a", "sov"]);
        map.insert("spaji", &["paj"]);
        map.insert("spali", &[] as &[&str]);
        map.insert("spano", &["san"]);
        map.insert("spati", &["spa"]);
        map.insert("speci", &[] as &[&str]);
        map.insert("speni", &["spe"]);
        map.insert("spero", &[] as &[&str]);
        map.insert("spisa", &["spi"]);
        map.insert("spita", &[] as &[&str]);
        map.insert("spofu", &["po'u", "pof"]);
        map.insert("spoja", &["poj", "po'a"]);
        map.insert("spuda", &["spu"]);
        map.insert("spupi", &[] as &[&str]);
        map.insert("sputu", &["pu'u", "put"]);
        map.insert("sraji", &["raj"]);
        map.insert("sraku", &["rak"]);
        map.insert("sralo", &[] as &[&str]);
        map.insert("srana", &["ra'a"]);
        map.insert("srasu", &["sas"]);
        map.insert("srate", &[] as &[&str]);
        map.insert("srera", &["sre"]);
        map.insert("srito", &[] as &[&str]);
        map.insert("sruma", &["ru'a"]);
        map.insert("sruri", &["rur", "sru"]);
        map.insert("stace", &["sac"]);
        map.insert("stagi", &[] as &[&str]);
        map.insert("staku", &["tak"]);
        map.insert("stali", &["sta"]);
        map.insert("stani", &[] as &[&str]);
        map.insert("stapa", &["tap"]);
        map.insert("stasu", &[] as &[&str]);
        map.insert("stati", &[] as &[&str]);
        map.insert("steba", &["seb"]);
        map.insert("steci", &["tec", "te'i"]);
        map.insert("stedu", &["sed"]);
        map.insert("stela", &["tel"]);
        map.insert("stero", &["te'o"]);
        map.insert("stici", &["sic"]);
        map.insert("stidi", &["sid", "ti'i"]);
        map.insert("stika", &["tik"]);
        map.insert("stima", &[] as &[&str]);
        map.insert("stizu", &["tiz"]);
        map.insert("stodi", &["sto"]);
        map.insert("stori", &[] as &[&str]);
        map.insert("stuna", &["sun"]);
        map.insert("stura", &["su'a", "tur"]);
        map.insert("stuzi", &["tuz", "stu"]);
        map.insert("sucta", &["suc"]);
        map.insert("sudga", &["sud"]);
        map.insert("su'e", &["sup", "su'e"]);
        map.insert("sufti", &["sfu"]);
        map.insert("suksa", &["suk"]);
        map.insert("sumji", &["suj"]);
        map.insert("sumla", &[] as &[&str]);
        map.insert("sumne", &[] as &[&str]);
        map.insert("sumro", &[] as &[&str]);
        map.insert("sumti", &["su'i", "sum"]);
        map.insert("sunga", &["sug"]);
        map.insert("sunla", &["sul"]);
        map.insert("su'o", &["suz", "su'o"]);
        map.insert("supso", &["sus"]);
        map.insert("surla", &["sur"]);
        map.insert("sutra", &["sut"]);
        map.insert("su'u", &["suv"]);
        map.insert("ta", &["taz"]);
        map.insert("tabno", &["tab"]);
        map.insert("tabra", &[] as &[&str]);
        map.insert("tadji", &[] as &[&str]);
        map.insert("tadni", &["tad"]);
        map.insert("tagji", &["tag"]);
        map.insert("takni", &[] as &[&str]);
        map.insert("taksi", &[] as &[&str]);
        map.insert("talko", &[] as &[&str]);
        map.insert("talsa", &["tal"]);
        map.insert("tamca", &[] as &[&str]);
        map.insert("tamji", &["taj"]);
        map.insert("tamle", &[] as &[&str]);
        map.insert("tamne", &[] as &[&str]);
        map.insert("tanbo", &["ta'o"]);
        map.insert("tance", &["tac"]);
        map.insert("tanjo", &[] as &[&str]);
        map.insert("tanko", &[] as &[&str]);
        map.insert("tanru", &["tau"]);
        map.insert("tansi", &["tas"]);
        map.insert("tanxe", &["ta'e", "tax"]);
        map.insert("tapla", &[] as &[&str]);
        map.insert("tarbi", &[] as &[&str]);
        map.insert("tarci", &["tar"]);
        map.insert("tarla", &[] as &[&str]);
        map.insert("tarmi", &["tai", "tam"]);
        map.insert("tarti", &["tra"]);
        map.insert("taske", &[] as &[&str]);
        map.insert("tasmi", &[] as &[&str]);
        map.insert("tasta", &[] as &[&str]);
        map.insert("tatpi", &["ta'i"]);
        map.insert("tatru", &["tat"]);
        map.insert("tavla", &["tav", "ta'a"]);
        map.insert("taxfu", &["ta'u", "taf"]);
        map.insert("tcaci", &["cac"]);
        map.insert("tcadu", &["tca"]);
        map.insert("tcana", &[] as &[&str]);
        map.insert("tcati", &[] as &[&str]);
        map.insert("tcaxe", &[] as &[&str]);
        map.insert("tcema", &[] as &[&str]);
        map.insert("tcemi", &[] as &[&str]);
        map.insert("tcena", &["ten"]);
        map.insert("tcesa", &[] as &[&str]);
        map.insert("tcese", &[] as &[&str]);
        map.insert("tceta", &[] as &[&str]);
        map.insert("tcica", &["tic"]);
        map.insert("tcidu", &["tid"]);
        map.insert("tcika", &[] as &[&str]);
        map.insert("tcila", &["til"]);
        map.insert("tcima", &["ti'a", "tim"]);
        map.insert("tcini", &[] as &[&str]);
        map.insert("tcipi", &[] as &[&str]);
        map.insert("tcita", &[] as &[&str]);
        map.insert("tcivi", &[] as &[&str]);
        map.insert("tcobi", &[] as &[&str]);
        map.insert("tcone", &[] as &[&str]);
        map.insert("tcuti", &[] as &[&str]);
        map.insert("te", &["ter"]);
        map.insert("tekla", &[] as &[&str]);
        map.insert("temci", &["tem", "tei"]);
        map.insert("temse", &[] as &[&str]);
        map.insert("tende", &["te'e"]);
        map.insert("tendo", &[] as &[&str]);
        map.insert("tenfa", &["tef"]);
        map.insert("tengu", &["te'u", "teg"]);
        map.insert("terdi", &["ted"]);
        map.insert("terki", &[] as &[&str]);
        map.insert("terpa", &["tep", "te'a"]);
        map.insert("terto", &["tet"]);
        map.insert("tezda", &[] as &[&str]);
        map.insert("ti", &["tif"]);
        map.insert("tifri", &[] as &[&str]);
        map.insert("tigni", &["tig"]);
        map.insert("tigra", &[] as &[&str]);
        map.insert("tikpa", &["tip"]);
        map.insert("tilju", &["tij"]);
        map.insert("timno", &[] as &[&str]);
        map.insert("tinbe", &["tib"]);
        map.insert("tinci", &[] as &[&str]);
        map.insert("tinri", &[] as &[&str]);
        map.insert("tinsa", &[] as &[&str]);
        map.insert("tinto", &[] as &[&str]);
        map.insert("tipre", &[] as &[&str]);
        map.insert("tirna", &["tin"]);
        map.insert("tirse", &["tir"]);
        map.insert("tirxu", &[] as &[&str]);
        map.insert("tisna", &["tis"]);
        map.insert("titla", &["tit"]);
        map.insert("tivni", &["tiv"]);
        map.insert("tixnu", &["tix", "ti'u"]);
        map.insert("tizva", &[] as &[&str]);
        map.insert("to'e", &["to'e", "tol"]);
        map.insert("toknu", &["tok"]);
        map.insert("toldi", &["tod"]);
        map.insert("tolfa", &[] as &[&str]);
        map.insert("tonga", &["to'a", "tog"]);
        map.insert("tordu", &["to'u", "tor"]);
        map.insert("torni", &["ton", "to'i"]);
        map.insert("torso", &[] as &[&str]);
        map.insert("torta", &[] as &[&str]);
        map.insert("tovla", &[] as &[&str]);
        map.insert("traji", &["rai"]);
        map.insert("trano", &[] as &[&str]);
        map.insert("trati", &[] as &[&str]);
        map.insert("trene", &["ren", "re'e"]);
        map.insert("tricu", &["ric"]);
        map.insert("triga", &[] as &[&str]);
        map.insert("trina", &["tri"]);
        map.insert("trixe", &["ti'e", "rix"]);
        map.insert("troci", &["toc", "toi"]);
        map.insert("tsaba", &[] as &[&str]);
        map.insert("tsali", &["tsa"]);
        map.insert("tsani", &["tan"]);
        map.insert("tsapi", &[] as &[&str]);
        map.insert("tsida", &[] as &[&str]);
        map.insert("tsiju", &["tsi"]);
        map.insert("tsina", &["sin"]);
        map.insert("tsuku", &[] as &[&str]);
        map.insert("tsuli", &[] as &[&str]);
        map.insert("tu", &["tuf"]);
        map.insert("tubnu", &["tu'u"]);
        map.insert("tubra", &[] as &[&str]);
        map.insert("tugni", &["tug", "tu'i"]);
        map.insert("tujli", &["tuj"]);
        map.insert("tulnu", &[] as &[&str]);
        map.insert("tumla", &["tu'a", "tum"]);
        map.insert("tunba", &["tub"]);
        map.insert("tunka", &["tuk"]);
        map.insert("tunlo", &["tul", "tu'o"]);
        map.insert("tunta", &["tun"]);
        map.insert("tuple", &["tu'e", "tup"]);
        map.insert("turko", &[] as &[&str]);
        map.insert("turni", &["tru"]);
        map.insert("tutci", &["tci"]);
        map.insert("tutle", &[] as &[&str]);
        map.insert("tutra", &["tut"]);
        map.insert("va", &["vaz"]);
        map.insert("vacri", &["var"]);
        map.insert("vajni", &["vai", "vaj"]);
        map.insert("valfa", &["vaf"]);
        map.insert("valsi", &["val", "vla"]);
        map.insert("vamgu", &[] as &[&str]);
        map.insert("vamji", &["vam", "va'i"]);
        map.insert("vamtu", &["vat"]);
        map.insert("vanbi", &["vab"]);
        map.insert("vanci", &["vac"]);
        map.insert("vanju", &["van"]);
        map.insert("vasru", &["vas", "vau"]);
        map.insert("vasxu", &["va'u", "vax"]);
        map.insert("ve", &["vel"]);
        map.insert("vecnu", &["ve'u", "ven"]);
        map.insert("vedli", &["ve'i"]);
        map.insert("ve'e", &["ve'e"]);
        map.insert("venfu", &["vef"]);
        map.insert("vensa", &["ves"]);
        map.insert("vente", &[] as &[&str]);
        map.insert("vepre", &[] as &[&str]);
        map.insert("verba", &["ver", "ve'a"]);
        map.insert("verjo", &[] as &[&str]);
        map.insert("vi", &["viz"]);
        map.insert("vibna", &["vib"]);
        map.insert("vidni", &[] as &[&str]);
        map.insert("vidru", &["vir"]);
        map.insert("vidvi", &[] as &[&str]);
        map.insert("vifne", &["vif"]);
        map.insert("vikmi", &["vi'i", "vim"]);
        map.insert("viknu", &["vik"]);
        map.insert("vilco", &[] as &[&str]);
        map.insert("vimcu", &["vic", "vi'u"]);
        map.insert("vindu", &["vid"]);
        map.insert("vinji", &["vij"]);
        map.insert("vinpa", &[] as &[&str]);
        map.insert("vinta", &[] as &[&str]);
        map.insert("vipsi", &["vip"]);
        map.insert("virme", &[] as &[&str]);
        map.insert("virnu", &["vri"]);
        map.insert("viska", &["vis", "vi'a"]);
        map.insert("vitci", &["vit"]);
        map.insert("vitke", &["vi'e"]);
        map.insert("vitno", &["vi'o"]);
        map.insert("vlagi", &["lag"]);
        map.insert("vlile", &["vil"]);
        map.insert("vlina", &[] as &[&str]);
        map.insert("vlipa", &["vli"]);
        map.insert("vo", &["von"]);
        map.insert("vofli", &["voi", "vol"]);
        map.insert("voksa", &["vo'a", "vok"]);
        map.insert("volve", &[] as &[&str]);
        map.insert("vorme", &["vor", "vro"]);
        map.insert("vraga", &["vra"]);
        map.insert("vreji", &["rej", "vei"]);
        map.insert("vreta", &["vre"]);
        map.insert("vrici", &[] as &[&str]);
        map.insert("vrude", &["vud", "vu'e"]);
        map.insert("vrusi", &["vus", "vu'i"]);
        map.insert("vu", &["vuz"]);
        map.insert("vubla", &["vul"]);
        map.insert("vujnu", &["vuj", "vu'u"]);
        map.insert("vukna", &[] as &[&str]);
        map.insert("vukro", &["vu'o", "vur"]);
        map.insert("xa", &["xav"]);
        map.insert("xabju", &["xa'u"]);
        map.insert("xadba", &["xab"]);
        map.insert("xadji", &[] as &[&str]);
        map.insert("xadni", &["xad"]);
        map.insert("xagji", &[] as &[&str]);
        map.insert("xagri", &[] as &[&str]);
        map.insert("xajmi", &["xam"]);
        map.insert("xaksu", &["xak"]);
        map.insert("xakto", &[] as &[&str]);
        map.insert("xalbo", &[] as &[&str]);
        map.insert("xalda", &[] as &[&str]);
        map.insert("xalka", &["xal"]);
        map.insert("xalni", &[] as &[&str]);
        map.insert("xamgu", &["xau", "xag"]);
        map.insert("xampo", &["xa'o", "xap"]);
        map.insert("xamsi", &["xas"]);
        map.insert("xance", &["xa'e", "xan"]);
        map.insert("xango", &[] as &[&str]);
        map.insert("xanka", &[] as &[&str]);
        map.insert("xanmi", &[] as &[&str]);
        map.insert("xanri", &["xar"]);
        map.insert("xansa", &[] as &[&str]);
        map.insert("xanto", &[] as &[&str]);
        map.insert("xarci", &["xa'i", "xac"]);
        map.insert("xarju", &["xaj"]);
        map.insert("xarnu", &[] as &[&str]);
        map.insert("xasli", &[] as &[&str]);
        map.insert("xasne", &[] as &[&str]);
        map.insert("xatra", &["xa'a"]);
        map.insert("xatsi", &["xat"]);
        map.insert("xavli", &[] as &[&str]);
        map.insert("xaxre", &[] as &[&str]);
        map.insert("xazdo", &["zdo", "xaz"]);
        map.insert("xe", &["xel"]);
        map.insert("xebni", &["xen", "xei"]);
        map.insert("xebro", &["bro", "xeb"]);
        map.insert("xecto", &["xet", "cto"]);
        map.insert("xedja", &["xej", "xe'a"]);
        map.insert("xekce", &[] as &[&str]);
        map.insert("xekri", &["xe'i", "xek"]);
        map.insert("xelso", &["xes"]);
        map.insert("xendo", &["xed", "xe'o"]);
        map.insert("xenru", &["xer", "xe'u"]);
        map.insert("xerno", &[] as &[&str]);
        map.insert("xexso", &["xex"]);
        map.insert("xigzo", &["xig"]);
        map.insert("xijra", &[] as &[&str]);
        map.insert("xilva", &["xiv"]);
        map.insert("ximta", &[] as &[&str]);
        map.insert("xindo", &["xin"]);
        map.insert("xinmo", &["xim"]);
        map.insert("xinro", &[] as &[&str]);
        map.insert("xinsi", &[] as &[&str]);
        map.insert("xirma", &["xir", "xi'a"]);
        map.insert("xislu", &["xi'u", "xil"]);
        map.insert("xispo", &["xip"]);
        map.insert("xixli", &[] as &[&str]);
        map.insert("xixnu", &[] as &[&str]);
        map.insert("xlali", &["xla"]);
        map.insert("xlobi", &[] as &[&str]);
        map.insert("xlura", &["xlu"]);
        map.insert("xonba", &[] as &[&str]);
        map.insert("xorbo", &[] as &[&str]);
        map.insert("xorlo", &[] as &[&str]);
        map.insert("xotli", &["xol", "xoi"]);
        map.insert("xrabo", &["rab"]);
        map.insert("xrani", &["xai"]);
        map.insert("xriso", &["xi'o", "xis"]);
        map.insert("xroma", &[] as &[&str]);
        map.insert("xrotu", &["xro"]);
        map.insert("xruba", &["xub"]);
        map.insert("xruki", &["xuk"]);
        map.insert("xrula", &["rul"]);
        map.insert("xruti", &["xru"]);
        map.insert("xudvu", &["xu'u"]);
        map.insert("xukmi", &["xu'i", "xum"]);
        map.insert("xulta", &["xut"]);
        map.insert("xumbe", &[] as &[&str]);
        map.insert("xunre", &["xun", "xu'e"]);
        map.insert("xurdo", &["xu'o", "xur"]);
        map.insert("xusra", &["xu'a", "xus"]);
        map.insert("xutla", &["xul"]);
        map.insert("zabna", &["zan", "za'a"]);
        map.insert("za'i", &["zaz"]);
        map.insert("zajba", &["zaj"]);
        map.insert("zalvi", &["zal"]);
        map.insert("zandi", &["zad"]);
        map.insert("zanru", &["zau", "zar"]);
        map.insert("zanxi", &[] as &[&str]);
        map.insert("za'o", &["za'o"]);
        map.insert("zarci", &["zai", "zac"]);
        map.insert("zargu", &["zag", "za'u"]);
        map.insert("zasni", &["zas"]);
        map.insert("zasti", &["zat", "za'i"]);
        map.insert("zbabu", &["bab"]);
        map.insert("zbani", &[] as &[&str]);
        map.insert("zbasu", &["zba"]);
        map.insert("zbepi", &["zbe"]);
        map.insert("zdani", &["zda"]);
        map.insert("zdile", &["zdi"]);
        map.insert("ze", &["zel"]);
        map.insert("ze'e", &["ze'e"]);
        map.insert("zejvo", &[] as &[&str]);
        map.insert("zekri", &["zei", "zer"]);
        map.insert("zenba", &["ze'a", "zen"]);
        map.insert("ze'o", &["zev", "ze'o"]);
        map.insert("zepti", &["zep"]);
        map.insert("zergi", &[] as &[&str]);
        map.insert("zetro", &["zet"]);
        map.insert("zevla", &["zve"]);
        map.insert("zgadi", &[] as &[&str]);
        map.insert("zgana", &["zga"]);
        map.insert("zgike", &["zgi", "gi'e"]);
        map.insert("zguro", &[] as &[&str]);
        map.insert("zifre", &["zif", "zi'e"]);
        map.insert("zinki", &["zi'i", "zin"]);
        map.insert("zi'o", &["zil"]);
        map.insert("zirli", &[] as &[&str]);
        map.insert("zirpu", &["zir", "zi'u"]);
        map.insert("zivle", &["ziv", "vle"]);
        map.insert("zmadu", &["zma", "mau"]);
        map.insert("zmase", &[] as &[&str]);
        map.insert("zmico", &["zic"]);
        map.insert("zmiku", &["zmi"]);
        map.insert("zo'a", &["zon", "zo'a"]);
        map.insert("zo'i", &["zor", "zo'i"]);
        map.insert("zorti", &[] as &[&str]);
        map.insert("zozno", &[] as &[&str]);
        map.insert("zubra", &[] as &[&str]);
        map.insert("zucna", &["zu'a", "zuc"]);
        map.insert("zukte", &["zuk", "zu'e"]);
        map.insert("zulna", &[] as &[&str]);
        map.insert("zumri", &["zmu"]);
        map.insert("zungi", &["zug"]);
        map.insert("zunle", &["zul"]);
        map.insert("zunti", &["zu'i", "zun"]);
        map.insert("zu'o", &["zum"]);
        map.insert("zurja", &["zuj"]);
        map.insert("zutse", &["zut", "tse"]);
        map.insert("zvati", &["zva"]);
        map.insert("zviki", &["zvi"]);
        map.insert("zvuzu", &[] as &[&str]);
        map.insert("xi", &["xix"]);
        map.insert("zai'e", &["zam"]);
        map.insert("gelse", &["ge'e", "ges"]);
        map.insert("je'ebzi", &["jeb"]);
        map.insert("mu'umgu", &["mug"]);
        map.insert("va'arga", &["va'a"]);
        map.insert("co'ai", &["cox"]);
        map.insert("dau", &["duv"]);
        map.insert("fei", &["fel"]);
        map.insert("ga'ei", &["gel"]);
        map.insert("gai", &["gam"]);
        map.insert("jau", &["juz"]);
        map.insert("ke'ai", &["ked"]);
        map.insert("ke'ei", &["keb"]);
        map.insert("ke'ei'a", &["kex"]);
        map.insert("kei'ei", &["kim"]);
        map.insert("lai'ai", &["lav"]);
        map.insert("su'ei", &["sem"]);
        map.insert("tau'u", &["tux"]);
        map.insert("to'ai", &["toz"]);
        map.insert("vai", &["vav"]);
        map.insert("vo'a", &["vob"]);
        map.insert("vo'ai", &["voz"]);
        map.insert("xei", &["xem"]);
        map.insert("xo'ai", &["xoz"]);
        map.insert("xo'ei", &["xon"]);
        map.insert("zei'e", &["zex"]);
        map.insert("zei'o", &["zes"]);
        map
    };
}