//! Contains the const RAFSI, a map from words to their affixes. docs.rs thinks it's a struct due to `lazy_static!`.
use lazy_static::lazy_static;
use std::collections::HashMap;
lazy_static! {
    pub static ref RAFSI: HashMap<&'static str, Vec<String>> = HashMap::from([
        ("babda", vec![]),
        ("bablo", vec![]),
        ("backi", vec![]),
        ("bacru", vec!["ba'u".to_string()]),
        ("badji", vec![]),
        ("badna", vec![]),
        ("badri", vec!["dri".to_string()]),
        ("bajra", vec!["baj".to_string()]),
        ("bakfu", vec!["baf".to_string()]),
        ("bakni", vec!["bak".to_string()]),
        ("bakri", vec![]),
        ("baktu", vec![]),
        ("balji", vec![]),
        ("balni", vec![]),
        ("balre", vec!["ba'e".to_string()]),
        ("balto", vec![]),
        ("balvi", vec!["bav".to_string()]),
        ("bambu", vec![]),
        ("bancu", vec!["bac".to_string()]),
        ("bandu", vec!["bad".to_string()]),
        ("banfi", vec![]),
        ("bangu", vec!["ban".to_string(), "bau".to_string()]),
        ("banli", vec!["bal".to_string(), "ba'i".to_string()]),
        ("banro", vec!["ba'o".to_string()]),
        ("banxa", vec!["bax".to_string()]),
        ("banzu", vec!["baz".to_string()]),
        ("bapli", vec!["bap".to_string(), "bai".to_string()]),
        ("barda", vec!["bra".to_string()]),
        ("bargu", vec!["bag".to_string()]),
        ("barja", vec![]),
        ("barna", vec!["ba'a".to_string()]),
        ("bartu", vec!["bar".to_string()]),
        ("basfa", vec![]),
        ("basna", vec![]),
        ("basti", vec!["bas".to_string()]),
        ("batci", vec!["bat".to_string()]),
        ("batke", vec![]),
        ("bavmi", vec![]),
        ("bavza", vec![]),
        ("baxso", vec![]),
        ("bebna", vec!["beb".to_string()]),
        ("bekpi", vec![]),
        ("belta", vec![]),
        ("bemro", vec!["bem".to_string(), "be'o".to_string()]),
        ("bende", vec!["bed".to_string(), "be'e".to_string()]),
        ("bengo", vec!["beg".to_string()]),
        ("benji", vec!["bej".to_string(), "be'i".to_string()]),
        ("benre", vec![]),
        ("benzo", vec![]),
        ("bergu", vec![]),
        ("bersa", vec!["bes".to_string(), "be'a".to_string()]),
        ("berti", vec!["ber".to_string()]),
        ("besna", vec!["ben".to_string()]),
        ("besto", vec![]),
        ("betfu", vec!["bef".to_string(), "be'u".to_string()]),
        ("betka", vec![]),
        ("betri", vec!["bet".to_string()]),
        ("bevri", vec!["bev".to_string(), "bei".to_string()]),
        ("bi", vec!["biv".to_string()]),
        ("bidju", vec![]),
        ("bifce", vec!["bic".to_string()]),
        ("bi'i", vec!["biz".to_string()]),
        ("bikla", vec!["bik".to_string()]),
        ("bilbo", vec![]),
        ("bilga", vec!["big".to_string()]),
        ("bilma", vec!["bi'a".to_string()]),
        ("bilni", vec!["bil".to_string()]),
        ("bindo", vec!["bid".to_string()]),
        ("binra", vec![]),
        ("binxo", vec!["bix".to_string(), "bi'o".to_string()]),
        ("birje", vec![]),
        ("birka", vec!["bir".to_string()]),
        ("birti", vec!["bit".to_string()]),
        ("bisli", vec!["bis".to_string()]),
        ("bitmu", vec!["bim".to_string(), "bi'u".to_string()]),
        ("bitni", vec![]),
        ("blabi", vec!["lab".to_string()]),
        ("blaci", vec![]),
        ("blanu", vec!["bla".to_string()]),
        ("bliku", vec!["bli".to_string()]),
        ("blina", vec![]),
        ("blolo", vec![]),
        (
            "bloti",
            vec!["lot".to_string(), "lo'i".to_string(), "blo".to_string()]
        ),
        ("bluji", vec![]),
        ("bo", vec!["bor".to_string()]),
        ("bolci", vec!["bol".to_string(), "boi".to_string()]),
        ("bongu", vec!["bog".to_string(), "bo'u".to_string()]),
        ("boske", vec![]),
        ("botpi", vec!["bot".to_string(), "bo'i".to_string()]),
        ("boxfo", vec!["bof".to_string(), "bo'o".to_string()]),
        ("boxna", vec!["bon".to_string(), "bo'a".to_string()]),
        ("bradi", vec![]),
        ("brano", vec![]),
        ("bratu", vec![]),
        ("bravi", vec![]),
        ("brazo", vec!["raz".to_string()]),
        ("bredi", vec!["red".to_string(), "bre".to_string()]),
        ("bridi", vec!["bri".to_string()]),
        ("brife", vec!["bif".to_string(), "bi'e".to_string()]),
        ("briju", vec!["bij".to_string()]),
        ("brito", vec!["rit".to_string()]),
        ("brivo", vec![]),
        ("broda", vec!["rod".to_string()]),
        ("brode", vec!["bo'e".to_string()]),
        ("brodi", vec![]),
        ("brodo", vec![]),
        ("brodu", vec![]),
        ("bruna", vec!["bun".to_string(), "bu'a".to_string()]),
        ("bu", vec!["bus".to_string(), "bu'i".to_string()]),
        ("bu'a", vec!["bul".to_string()]),
        ("budjo", vec!["buj".to_string(), "bu'o".to_string()]),
        ("budza", vec![]),
        ("bukpu", vec!["buk".to_string(), "bu'u".to_string()]),
        ("bumru", vec!["bum".to_string()]),
        ("bunda", vec!["bud".to_string()]),
        ("bunre", vec!["bur".to_string(), "bu'e".to_string()]),
        ("buntu", vec![]),
        ("bunxa", vec![]),
        ("burcu", vec!["bru".to_string()]),
        ("burka", vec![]),
        ("burna", vec![]),
        ("buvla", vec![]),
        ("ca'a", vec!["caz".to_string()]),
        ("cabna", vec!["cab".to_string()]),
        ("cabra", vec!["ca'a".to_string()]),
        ("cacra", vec![]),
        ("cadga", vec![]),
        ("cadma", vec![]),
        ("cadzu", vec!["dzu".to_string()]),
        ("cafne", vec!["caf".to_string()]),
        ("cagna", vec![]),
        ("cajni", vec![]),
        ("cakla", vec![]),
        ("calku", vec!["cak".to_string()]),
        ("calse", vec![]),
        ("campu", vec![]),
        ("canci", vec![]),
        ("cando", vec!["cad".to_string()]),
        ("cange", vec!["cag".to_string()]),
        ("canja", vec!["caj".to_string()]),
        ("canko", vec!["ca'o".to_string()]),
        ("canlu", vec!["cal".to_string(), "ca'u".to_string()]),
        ("canma", vec![]),
        ("canpa", vec!["cna".to_string()]),
        ("canre", vec!["can".to_string()]),
        ("canti", vec![]),
        ("carce", vec![]),
        ("carfu", vec![]),
        ("carmi", vec!["cam".to_string(), "cai".to_string()]),
        ("carna", vec!["car".to_string()]),
        ("cartu", vec!["cat".to_string()]),
        ("carvi", vec!["cav".to_string()]),
        ("casnu", vec!["snu".to_string()]),
        ("catke", vec!["ca'e".to_string()]),
        ("catlu", vec!["cta".to_string()]),
        ("catni", vec!["ca'i".to_string()]),
        ("catra", vec![]),
        ("caxno", vec!["cax".to_string()]),
        ("ce", vec!["cec".to_string()]),
        ("cecla", vec!["cel".to_string(), "ce'a".to_string()]),
        ("cecmu", vec!["cem".to_string(), "ce'u".to_string()]),
        ("cedra", vec![]),
        ("ce'i", vec!["cez".to_string()]),
        ("celdi", vec!["cle".to_string()]),
        ("celxa", vec![]),
        ("cenba", vec!["cne".to_string()]),
        ("cendo", vec![]),
        ("censa", vec!["ces".to_string()]),
        ("centi", vec!["cen".to_string()]),
        ("ce'o", vec!["ce'o".to_string()]),
        ("cerda", vec!["ced".to_string()]),
        ("cerni", vec!["cer".to_string()]),
        ("certu", vec!["cre".to_string()]),
        ("cevni", vec!["cev".to_string(), "cei".to_string()]),
        ("cfale", vec![]),
        ("cfari", vec!["cfa".to_string()]),
        ("cfika", vec!["fik".to_string(), "fi'a".to_string()]),
        ("cfila", vec!["cfi".to_string()]),
        ("cfine", vec![]),
        ("cfipu", vec!["fi'u".to_string()]),
        ("ci", vec!["cib".to_string()]),
        ("ciblu", vec!["blu".to_string()]),
        ("cicna", vec![]),
        ("cidja", vec!["dja".to_string()]),
        ("cidni", vec!["cid".to_string()]),
        ("cidro", vec!["dro".to_string()]),
        ("cifnu", vec!["cif".to_string()]),
        ("cigla", vec!["cig".to_string()]),
        ("cikna", vec!["cik".to_string()]),
        ("cikre", vec![]),
        ("ciksi", vec!["cki".to_string()]),
        ("cilce", vec!["cic".to_string()]),
        ("cilfu", vec![]),
        ("cilmo", vec!["cim".to_string()]),
        ("cilre", vec!["cli".to_string()]),
        ("cilta", vec!["cil".to_string()]),
        ("cimde", vec![]),
        ("cimle", vec![]),
        ("cimni", vec![]),
        ("cinba", vec![]),
        ("cindu", vec![]),
        ("cinfo", vec![]),
        ("cinje", vec!["cij".to_string()]),
        ("cinki", vec![]),
        ("cinla", vec![]),
        ("cinmo", vec!["cni".to_string()]),
        ("cinri", vec!["ci'i".to_string()]),
        ("cinse", vec!["cin".to_string()]),
        ("cinta", vec![]),
        ("cinza", vec![]),
        ("cipni", vec!["cpi".to_string()]),
        ("cipra", vec!["cip".to_string()]),
        ("cirko", vec!["cri".to_string()]),
        ("cirla", vec![]),
        ("ciska", vec!["ci'a".to_string()]),
        ("cisma", vec![]),
        ("cisni", vec![]),
        ("ciste", vec!["ci'e".to_string()]),
        ("citka", vec!["cti".to_string()]),
        ("citno", vec!["cit".to_string(), "ci'o".to_string()]),
        ("citri", vec!["cir".to_string()]),
        ("citsi", vec![]),
        ("civla", vec!["civ".to_string()]),
        ("cizra", vec!["ciz".to_string()]),
        ("ckabu", vec![]),
        ("ckafi", vec!["kaf".to_string()]),
        ("ckaji", vec!["kai".to_string()]),
        ("ckana", vec!["cka".to_string()]),
        ("ckape", vec!["cap".to_string()]),
        ("ckasu", vec!["cas".to_string()]),
        ("ckeji", vec!["kej".to_string(), "cke".to_string()]),
        ("ckiku", vec!["kik".to_string()]),
        ("ckilu", vec!["ci'u".to_string()]),
        ("ckini", vec!["ki'i".to_string()]),
        ("ckire", vec!["kir".to_string()]),
        ("ckule", vec!["kul".to_string(), "cu'e".to_string()]),
        ("ckunu", vec!["ku'u".to_string()]),
        ("cladu", vec!["lau".to_string()]),
        ("clafi", vec![]),
        ("clani", vec!["cla".to_string()]),
        ("claxu", vec!["cau".to_string()]),
        ("clenu", vec![]),
        ("cletu", vec![]),
        ("clika", vec![]),
        ("clinu", vec![]),
        ("clira", vec!["lir".to_string()]),
        ("clite", vec!["lit".to_string()]),
        ("cliva", vec!["liv".to_string(), "li'a".to_string()]),
        ("clupa", vec!["cup".to_string()]),
        ("cmaci", vec![]),
        ("cmalu", vec!["cma".to_string()]),
        ("cmana", vec!["ma'a".to_string()]),
        ("cmavo", vec!["ma'o".to_string()]),
        ("cmene", vec!["me'e".to_string(), "cme".to_string()]),
        ("cmeta", vec![]),
        ("cmevo", vec![]),
        ("cmila", vec!["mi'a".to_string()]),
        ("cmima", vec!["mim".to_string(), "cmi".to_string()]),
        ("cmoni", vec!["co'i".to_string(), "cmo".to_string()]),
        ("cnano", vec!["na'o".to_string()]),
        ("cnata", vec![]),
        ("cnebo", vec!["neb".to_string(), "ne'o".to_string()]),
        ("cnemu", vec!["nem".to_string(), "ne'u".to_string()]),
        ("cnici", vec!["nic".to_string()]),
        ("cnida", vec![]),
        ("cnino", vec!["nin".to_string(), "ni'o".to_string()]),
        ("cnisa", vec!["nis".to_string()]),
        ("cnita", vec!["nit".to_string(), "ni'a".to_string()]),
        ("co", vec!["col".to_string()]),
        ("co'a", vec!["co'a".to_string()]),
        ("co'e", vec!["com".to_string(), "co'e".to_string()]),
        ("cokcu", vec!["cko".to_string()]),
        ("cokte", vec![]),
        (
            "condi",
            vec!["con".to_string(), "cno".to_string(), "coi".to_string()]
        ),
        ("conka", vec![]),
        ("corci", vec!["coc".to_string()]),
        ("cortu", vec!["cor".to_string(), "cro".to_string()]),
        ("cotci", vec![]),
        ("co'u", vec!["co'u".to_string()]),
        ("cpacu", vec!["cpa".to_string()]),
        ("cpana", vec![]),
        ("cpare", vec!["par".to_string()]),
        ("cpedu", vec!["cpe".to_string()]),
        ("cpina", vec![]),
        ("cpixa", vec![]),
        ("cradi", vec![]),
        ("crami", vec![]),
        ("crane", vec!["cra".to_string()]),
        ("cravi", vec![]),
        ("creka", vec!["cek".to_string()]),
        ("crepu", vec!["rep".to_string()]),
        ("cribe", vec!["rib".to_string()]),
        ("crida", vec!["rid".to_string()]),
        ("crino", vec!["ri'o".to_string()]),
        ("cripu", vec!["rip".to_string()]),
        ("crisa", vec!["cis".to_string()]),
        ("critu", vec![]),
        ("ctaru", vec![]),
        ("ctebi", vec!["teb".to_string()]),
        ("cteki", vec!["tek".to_string(), "ce'i".to_string()]),
        ("ctera", vec![]),
        ("ctile", vec![]),
        ("ctino", vec!["ti'o".to_string()]),
        ("ctuca", vec!["ctu".to_string()]),
        ("cukla", vec!["cuk".to_string()]),
        ("cukre", vec![]),
        ("cukta", vec!["cku".to_string()]),
        ("culno", vec!["clu".to_string()]),
        ("cumba", vec![]),
        ("cumki", vec!["cum".to_string(), "cu'i".to_string()]),
        ("cumla", vec!["cul".to_string()]),
        ("cunmi", vec![]),
        ("cunso", vec!["cun".to_string(), "cu'o".to_string()]),
        ("cuntu", vec!["cu'u".to_string()]),
        ("cupra", vec!["pra".to_string()]),
        ("curmi", vec!["cru".to_string()]),
        ("curnu", vec!["cur".to_string()]),
        ("curve", vec!["cuv".to_string()]),
        ("cusku", vec!["cus".to_string(), "sku".to_string()]),
        ("cusna", vec![]),
        ("cutci", vec!["cuc".to_string()]),
        ("cutne", vec!["cut".to_string()]),
        ("cuxna", vec!["cux".to_string(), "cu'a".to_string()]),
        ("da", vec!["dav".to_string(), "dza".to_string()]),
        ("da'a", vec!["daz".to_string()]),
        ("dacru", vec!["dac".to_string()]),
        ("dacti", vec!["dai".to_string()]),
        ("dadjo", vec!["daj".to_string()]),
        ("dajbu", vec![]),
        ("dajne", vec![]),
        ("dakfu", vec!["dak".to_string()]),
        ("dakli", vec![]),
        ("damba", vec!["dab".to_string(), "da'a".to_string()]),
        ("damri", vec![]),
        ("danci", vec![]),
        ("dandu", vec!["dad".to_string()]),
        ("danfu", vec!["daf".to_string()]),
        ("danke", vec![]),
        ("danlu", vec!["dal".to_string(), "da'u".to_string()]),
        ("danmo", vec!["dam".to_string()]),
        ("danre", vec!["da'e".to_string()]),
        ("dansu", vec![]),
        ("danti", vec!["dan".to_string()]),
        ("daplu", vec!["plu".to_string()]),
        ("dapma", vec!["dap".to_string()]),
        ("darca", vec![]),
        ("dardu", vec![]),
        ("dargu", vec!["dag".to_string()]),
        ("darlu", vec!["dau".to_string()]),
        ("darno", vec!["dar".to_string(), "da'o".to_string()]),
        ("darsi", vec![]),
        ("darxi", vec!["dax".to_string(), "da'i".to_string()]),
        ("daski", vec![]),
        ("dasni", vec!["das".to_string()]),
        ("daspo", vec!["spo".to_string()]),
        ("dasri", vec!["sri".to_string()]),
        ("datca", vec![]),
        ("datka", vec![]),
        ("datni", vec![]),
        ("datro", vec![]),
        ("datru", vec![]),
        ("datxo", vec![]),
        ("decti", vec!["dec".to_string()]),
        ("degji", vec!["deg".to_string()]),
        ("dejni", vec!["dej".to_string()]),
        ("dekpu", vec![]),
        ("dekto", vec!["dek".to_string()]),
        ("delca", vec![]),
        ("delno", vec!["del".to_string(), "de'o".to_string()]),
        ("delta", vec![]),
        ("dembi", vec!["deb".to_string()]),
        ("denci", vec!["den".to_string(), "de'i".to_string()]),
        ("dendi", vec![]),
        ("denmi", vec!["dem".to_string()]),
        ("denpa", vec!["dep".to_string(), "de'a".to_string()]),
        ("dertu", vec!["der".to_string(), "de'u".to_string()]),
        ("derxi", vec!["dre".to_string()]),
        ("desku", vec!["des".to_string()]),
        ("detri", vec!["det".to_string()]),
        ("dicma", vec![]),
        ("dicra", vec!["dir".to_string()]),
        ("didni", vec![]),
        ("digno", vec![]),
        ("dikca", vec!["dic".to_string()]),
        ("diklo", vec!["klo".to_string()]),
        ("dikni", vec!["dik".to_string()]),
        ("dilcu", vec![]),
        ("dildo", vec![]),
        ("dilma", vec![]),
        ("dilnu", vec!["dil".to_string()]),
        ("dimna", vec!["dim".to_string()]),
        ("dindi", vec![]),
        ("dinju", vec!["dij".to_string(), "di'u".to_string()]),
        ("dinko", vec!["di'o".to_string()]),
        ("dinso", vec!["dis".to_string()]),
        ("dinti", vec![]),
        ("dirba", vec!["dib".to_string()]),
        ("dirce", vec!["di'e".to_string()]),
        ("dirgo", vec!["dig".to_string()]),
        ("disko", vec![]),
        ("ditcu", vec!["dit".to_string()]),
        ("divzi", vec![]),
        ("dizlo", vec!["diz".to_string(), "dzi".to_string()]),
        ("djacu", vec!["jac".to_string(), "jau".to_string()]),
        ("djedi", vec!["dje".to_string(), "dei".to_string()]),
        ("djica", vec!["dji".to_string()]),
        ("djika", vec![]),
        ("djine", vec!["jin".to_string()]),
        ("djuno", vec!["jun".to_string(), "ju'o".to_string()]),
        ("do", vec!["don".to_string(), "doi".to_string()]),
        ("dolna", vec!["dol".to_string()]),
        ("donri", vec!["dor".to_string(), "do'i".to_string()]),
        ("dotco", vec!["dot".to_string(), "do'o".to_string()]),
        ("draci", vec![]),
        ("drani", vec!["dra".to_string()]),
        ("drata", vec!["dat".to_string()]),
        ("drisu", vec![]),
        ("drudi", vec!["rud".to_string(), "dru".to_string()]),
        ("du", vec!["dub".to_string(), "du'o".to_string()]),
        ("dugri", vec!["dug".to_string()]),
        ("dukni", vec![]),
        ("dukse", vec!["dus".to_string(), "du'e".to_string()]),
        ("dukti", vec!["dut".to_string()]),
        ("dunda", vec!["dud".to_string(), "du'a".to_string()]),
        ("dunja", vec!["duj".to_string()]),
        ("dunku", vec!["duk".to_string(), "du'u".to_string()]),
        ("dunli", vec!["dun".to_string(), "du'i".to_string()]),
        ("dunra", vec!["dur".to_string()]),
        ("durna", vec![]),
        ("dutso", vec!["tso".to_string()]),
        ("du'u", vec!["dum".to_string()]),
        ("dzama", vec![]),
        ("dzena", vec!["dze".to_string()]),
        ("dzipo", vec!["zip".to_string(), "zi'o".to_string()]),
        ("dzoli", vec!["dzo".to_string()]),
        ("facki", vec!["fak".to_string(), "fa'i".to_string()]),
        ("facni", vec![]),
        ("fadni", vec!["fad".to_string()]),
        ("fagri", vec!["fag".to_string()]),
        ("falnu", vec!["fan".to_string()]),
        ("famti", vec![]),
        ("fancu", vec![]),
        ("fange", vec![]),
        ("fanji", vec![]),
        ("fanmo", vec!["fam".to_string(), "fa'o".to_string()]),
        ("fanri", vec![]),
        ("fanta", vec![]),
        ("fanva", vec![]),
        ("fanza", vec!["faz".to_string()]),
        ("fapro", vec!["fap".to_string(), "pro".to_string()]),
        ("fardu", vec![]),
        ("farka", vec![]),
        ("farlu", vec!["fal".to_string(), "fa'u".to_string()]),
        ("farna", vec!["far".to_string(), "fa'a".to_string()]),
        ("farvi", vec!["fav".to_string()]),
        ("fasnu", vec!["fau".to_string()]),
        ("fatci", vec!["fac".to_string()]),
        ("fatne", vec!["fat".to_string(), "fa'e".to_string()]),
        ("fatri", vec!["fai".to_string()]),
        ("febvi", vec!["feb".to_string()]),
        ("fegli", vec![]),
        ("femti", vec!["fem".to_string()]),
        ("fendi", vec!["fed".to_string()]),
        ("fenfa", vec![]),
        ("fengu", vec!["feg".to_string(), "fe'u".to_string()]),
        ("fenki", vec!["fek".to_string()]),
        ("fenra", vec!["fer".to_string(), "fe'a".to_string()]),
        ("fenso", vec!["fen".to_string(), "fe'o".to_string()]),
        ("fepni", vec!["fep".to_string(), "fei".to_string()]),
        ("fepri", vec![]),
        ("ferti", vec!["fre".to_string()]),
        ("festi", vec!["fes".to_string()]),
        ("fetsi", vec!["fet".to_string(), "fe'i".to_string()]),
        ("fibra", vec![]),
        ("fidna", vec!["fid".to_string()]),
        ("figre", vec!["fig".to_string()]),
        ("filso", vec!["fis".to_string()]),
        ("finpe", vec!["fip".to_string(), "fi'e".to_string()]),
        ("finti", vec!["fin".to_string(), "fi'i".to_string()]),
        ("firca", vec![]),
        ("fisli", vec![]),
        ("fizbu", vec![]),
        ("fizde", vec!["fiz".to_string()]),
        ("flaci", vec![]),
        ("flalu", vec!["fla".to_string()]),
        ("flani", vec![]),
        ("flecu", vec!["fle".to_string()]),
        ("flese", vec!["les".to_string()]),
        ("fliba", vec!["fli".to_string()]),
        ("flipo", vec![]),
        ("flira", vec!["fir".to_string()]),
        ("fo'a", vec!["fo'a".to_string()]),
        ("fo'e", vec!["fo'e".to_string()]),
        ("fo'i", vec!["fo'i".to_string()]),
        ("foldi", vec!["flo".to_string(), "foi".to_string()]),
        ("fonmo", vec!["fom".to_string(), "fo'o".to_string()]),
        ("fonxa", vec!["fon".to_string()]),
        ("forca", vec!["fro".to_string()]),
        ("forse", vec![]),
        ("fraso", vec!["fas".to_string()]),
        ("frati", vec!["fra".to_string()]),
        ("fraxu", vec!["fax".to_string()]),
        ("frica", vec!["fic".to_string()]),
        ("friko", vec!["fi'o".to_string()]),
        ("frili", vec!["fil".to_string()]),
        ("frinu", vec![]),
        ("friti", vec!["fit".to_string()]),
        ("frumu", vec!["fru".to_string()]),
        ("fugvo", vec![]),
        ("fukpi", vec!["fuk".to_string(), "fu'i".to_string()]),
        ("fulta", vec!["ful".to_string(), "flu".to_string()]),
        ("funca", vec!["fun".to_string(), "fu'a".to_string()]),
        ("fusra", vec!["fur".to_string()]),
        ("fuvla", vec![]),
        ("fuzme", vec!["fuz".to_string(), "fu'e".to_string()]),
        ("gacri", vec!["gai".to_string()]),
        ("gadri", vec!["gad".to_string()]),
        ("galfi", vec!["gaf".to_string(), "ga'i".to_string()]),
        ("galki", vec![]),
        ("galtu", vec!["gal".to_string(), "ga'u".to_string()]),
        ("galxe", vec![]),
        ("ganda", vec![]),
        ("ganlo", vec!["ga'o".to_string()]),
        ("ganra", vec!["gan".to_string()]),
        ("ganse", vec!["gas".to_string(), "ga'e".to_string()]),
        ("ganti", vec![]),
        ("ganvi", vec![]),
        ("ganxo", vec!["gax".to_string()]),
        ("ganzu", vec!["gaz".to_string()]),
        ("gapci", vec!["gac".to_string()]),
        ("gapru", vec!["gap".to_string()]),
        ("garna", vec!["gar".to_string()]),
        ("gasnu", vec!["gau".to_string()]),
        ("gaspo", vec![]),
        ("gasta", vec!["gat".to_string()]),
        ("genja", vec!["gej".to_string()]),
        ("gento", vec!["get".to_string(), "ge'o".to_string()]),
        ("genxu", vec!["gex".to_string()]),
        ("gerku", vec!["ger".to_string(), "ge'u".to_string()]),
        ("gerna", vec!["gen".to_string(), "ge'a".to_string()]),
        ("gicmu", vec![]),
        ("gidva", vec!["gid".to_string(), "gi'a".to_string()]),
        ("gigdo", vec!["gig".to_string(), "gi'o".to_string()]),
        ("ginka", vec!["gik".to_string()]),
        ("girzu", vec!["gir".to_string(), "gri".to_string()]),
        ("gismu", vec!["gim".to_string(), "gi'u".to_string()]),
        ("glare", vec!["gla".to_string()]),
        ("gleki", vec!["gek".to_string(), "gei".to_string()]),
        ("gletu", vec!["let".to_string(), "gle".to_string()]),
        ("glico", vec!["gic".to_string(), "gli".to_string()]),
        ("glife", vec![]),
        ("glosa", vec![]),
        ("gluta", vec!["glu".to_string()]),
        ("gocti", vec!["goc".to_string()]),
        ("gomsi", vec![]),
        ("gonte", vec![]),
        ("gotro", vec!["got".to_string()]),
        ("gradu", vec!["rau".to_string()]),
        ("grafu", vec![]),
        ("grake", vec!["gra".to_string()]),
        ("grame", vec![]),
        ("grana", vec!["ga'a".to_string()]),
        ("grasu", vec!["ras".to_string()]),
        ("grava", vec!["gav".to_string()]),
        ("greku", vec!["rek".to_string()]),
        ("grusi", vec!["rus".to_string()]),
        ("grute", vec!["rut".to_string()]),
        ("gubni", vec!["gub".to_string()]),
        ("gugde", vec!["gug".to_string(), "gu'e".to_string()]),
        ("gugle", vec![]),
        ("gumri", vec![]),
        ("gundi", vec!["gud".to_string()]),
        ("gunka", vec!["gun".to_string(), "gu'a".to_string()]),
        ("gunma", vec!["gum".to_string()]),
        ("gunro", vec!["gur".to_string(), "gu'o".to_string()]),
        ("gunse", vec![]),
        ("gunta", vec!["gut".to_string()]),
        ("gurni", vec!["gru".to_string()]),
        ("guska", vec!["guk".to_string()]),
        ("gusni", vec!["gus".to_string(), "gu'i".to_string()]),
        ("gusta", vec![]),
        ("gutci", vec!["guc".to_string()]),
        ("gutra", vec![]),
        ("guzme", vec!["guz".to_string(), "zme".to_string()]),
        ("ja", vec!["jav".to_string()]),
        ("jabre", vec![]),
        ("jadni", vec!["jad".to_string(), "ja'i".to_string()]),
        ("jai", vec!["jax".to_string()]),
        ("jakne", vec![]),
        ("jaldi", vec![]),
        ("jalge", vec!["jag".to_string(), "ja'e".to_string()]),
        ("jalna", vec![]),
        ("jalra", vec![]),
        ("jamfu", vec!["jaf".to_string(), "jma".to_string()]),
        ("jamna", vec!["jam".to_string()]),
        ("janbe", vec!["jab".to_string()]),
        ("janco", vec!["jan".to_string()]),
        ("janli", vec!["jal".to_string()]),
        ("jansu", vec!["jas".to_string()]),
        ("janta", vec!["jat".to_string()]),
        ("jarbu", vec![]),
        ("jarco", vec!["ja'o".to_string()]),
        ("jarki", vec!["jak".to_string()]),
        ("jaspu", vec!["jap".to_string()]),
        ("jatna", vec!["ja'a".to_string()]),
        ("jatsu", vec![]),
        ("javni", vec!["jva".to_string()]),
        ("jbama", vec!["bam".to_string()]),
        ("jbari", vec!["jba".to_string()]),
        ("jbena", vec!["jbe".to_string()]),
        ("jbera", vec!["jer".to_string()]),
        ("jbini", vec!["bin".to_string(), "bi'i".to_string()]),
        ("jbobo", vec![]),
        ("jdari", vec!["jar".to_string()]),
        ("jdice", vec!["jdi".to_string()]),
        ("jdika", vec![]),
        ("jdima", vec!["di'a".to_string()]),
        ("jdini", vec!["din".to_string(), "di'i".to_string()]),
        ("jduli", vec!["dul".to_string(), "jdu".to_string()]),
        ("je", vec!["jev".to_string(), "jve".to_string()]),
        ("jecta", vec!["jec".to_string(), "je'a".to_string()]),
        ("jeftu", vec!["jef".to_string()]),
        ("jegvo", vec!["jeg".to_string(), "je'o".to_string()]),
        ("jei", vec!["jez".to_string()]),
        ("jelca", vec!["jel".to_string()]),
        ("jemna", vec!["jme".to_string()]),
        ("jenca", vec!["jen".to_string()]),
        ("jendu", vec!["jed".to_string()]),
        ("jenje", vec![]),
        ("jenmi", vec!["jem".to_string(), "jei".to_string()]),
        ("jensi", vec![]),
        ("jerna", vec![]),
        ("jersi", vec!["je'i".to_string()]),
        ("jerxo", vec!["jex".to_string()]),
        ("jesni", vec!["jes".to_string()]),
        ("jetce", vec!["je'e".to_string()]),
        ("jetnu", vec!["jet".to_string(), "je'u".to_string()]),
        ("jgalu", vec!["ja'u".to_string()]),
        ("jganu", vec!["jga".to_string()]),
        ("jgari", vec!["jai".to_string()]),
        ("jgena", vec!["jge".to_string()]),
        ("jgina", vec!["gin".to_string()]),
        ("jgira", vec!["jgi".to_string()]),
        ("jgita", vec!["git".to_string()]),
        ("jguvi", vec![]),
        ("jibni", vec!["jbi".to_string()]),
        ("jibri", vec!["jib".to_string()]),
        ("jicfo", vec![]),
        ("jicla", vec![]),
        ("jicmu", vec!["cmu".to_string()]),
        ("jidge", vec!["jid".to_string()]),
        ("jijgi", vec![]),
        ("jijnu", vec!["jij".to_string()]),
        ("jikca", vec!["jik".to_string()]),
        ("jikfi", vec![]),
        ("jikni", vec![]),
        ("jikru", vec![]),
        ("jilka", vec!["jil".to_string()]),
        ("jilra", vec![]),
        ("jimca", vec!["jic".to_string()]),
        ("jimpe", vec!["jmi".to_string()]),
        ("jimte", vec!["jit".to_string()]),
        ("jinci", vec![]),
        ("jinda", vec![]),
        ("jinga", vec!["jig".to_string(), "ji'a".to_string()]),
        ("jinku", vec![]),
        ("jinme", vec!["jim".to_string()]),
        ("jinru", vec!["jir".to_string()]),
        ("jinsa", vec!["jis".to_string()]),
        ("jinto", vec![]),
        ("jinvi", vec!["jiv".to_string(), "ji'i".to_string()]),
        ("jinzi", vec!["jiz".to_string()]),
        ("jipci", vec![]),
        ("jipno", vec!["jip".to_string(), "ji'o".to_string()]),
        ("jirna", vec![]),
        ("jisra", vec![]),
        ("jitfa", vec!["jif".to_string()]),
        ("jitni", vec![]),
        ("jitro", vec!["tro".to_string()]),
        ("jivbu", vec![]),
        ("jivna", vec!["jvi".to_string()]),
        ("jmaji", vec!["jaj".to_string()]),
        ("jmice", vec![]),
        ("jmifa", vec![]),
        ("jmina", vec!["min".to_string()]),
        ("jmite", vec![]),
        ("jmive", vec!["miv".to_string(), "ji'e".to_string()]),
        ("jo", vec!["jov".to_string()]),
        ("jo'e", vec!["jom".to_string()]),
        ("joi", vec!["jol".to_string(), "joi".to_string()]),
        ("jonse", vec!["jos".to_string()]),
        ("jordo", vec!["jor".to_string(), "jo'o".to_string()]),
        ("jorne", vec!["jon".to_string(), "jo'e".to_string()]),
        ("jo'u", vec!["jo'u".to_string()]),
        ("ju", vec!["juv".to_string()]),
        ("jubme", vec!["jub".to_string(), "jbu".to_string()]),
        ("judri", vec![]),
        ("jufra", vec!["juf".to_string(), "ju'a".to_string()]),
        ("jukni", vec!["juk".to_string()]),
        ("jukpa", vec!["jup".to_string()]),
        ("julne", vec!["ju'e".to_string()]),
        ("julro", vec![]),
        ("jundi", vec!["jud".to_string(), "ju'i".to_string()]),
        ("jungo", vec!["jug".to_string()]),
        ("junla", vec!["jul".to_string()]),
        ("junri", vec!["jur".to_string()]),
        ("junta", vec![]),
        ("jurme", vec!["jum".to_string()]),
        ("jursa", vec!["jus".to_string()]),
        ("jutsi", vec!["jut".to_string()]),
        ("juxre", vec!["jux".to_string()]),
        ("jvinu", vec!["vin".to_string(), "ji'u".to_string()]),
        ("jviso", vec![]),
        ("ka", vec!["kam".to_string()]),
        ("kabri", vec![]),
        ("kacma", vec![]),
        ("kadno", vec![]),
        ("kafke", vec![]),
        ("kagni", vec!["kag".to_string()]),
        ("kajde", vec!["jde".to_string()]),
        ("kajna", vec![]),
        ("kakne", vec!["ka'e".to_string()]),
        ("kakpa", vec![]),
        ("kakti", vec![]),
        ("kalci", vec![]),
        ("kalri", vec!["kar".to_string()]),
        ("kalsa", vec!["kas".to_string()]),
        ("kalte", vec!["kat".to_string()]),
        ("kamju", vec![]),
        ("kamni", vec![]),
        ("kampu", vec!["kau".to_string()]),
        ("kamre", vec![]),
        ("kamro", vec![]),
        ("kanba", vec![]),
        ("kancu", vec!["kac".to_string()]),
        ("kandi", vec!["kad".to_string()]),
        ("kanji", vec!["kaj".to_string()]),
        ("kanla", vec!["kal".to_string()]),
        ("kanpe", vec![]),
        ("kanro", vec!["ka'o".to_string()]),
        ("kansa", vec!["kan".to_string()]),
        ("kantu", vec!["ka'u".to_string()]),
        ("kanxe", vec!["kax".to_string()]),
        ("kapli", vec![]),
        ("kapsi", vec![]),
        ("karbi", vec!["kab".to_string()]),
        ("karce", vec![]),
        ("karda", vec![]),
        ("kargu", vec![]),
        ("karli", vec![]),
        ("karmo", vec![]),
        ("karni", vec![]),
        ("karpa", vec![]),
        ("katci", vec![]),
        ("katna", vec!["ka'a".to_string()]),
        ("katso", vec![]),
        ("kavbu", vec!["kav".to_string()]),
        ("kavzi", vec![]),
        ("kazmi", vec![]),
        ("kazra", vec!["kaz".to_string()]),
        ("ke", vec!["kem".to_string()]),
        ("kebzo", vec![]),
        ("kecti", vec!["kec".to_string(), "ke'i".to_string()]),
        ("ke'e", vec!["kep".to_string(), "ke'e".to_string()]),
        ("kei", vec!["kez".to_string()]),
        ("kekli", vec!["kek".to_string()]),
        ("kekti", vec![]),
        ("kelci", vec!["kel".to_string(), "kei".to_string()]),
        ("kelto", vec![]),
        ("kelvo", vec!["ke'o".to_string()]),
        ("kenka", vec![]),
        ("kenra", vec!["ken".to_string()]),
        ("kensa", vec!["kes".to_string()]),
        ("kerfa", vec!["kre".to_string()]),
        ("kerlo", vec!["ker".to_string()]),
        ("kerni", vec![]),
        ("kesfi", vec![]),
        ("kesri", vec![]),
        ("ketco", vec!["ket".to_string(), "tco".to_string()]),
        ("ketli", vec![]),
        ("ketro", vec![]),
        ("ketsu", vec![]),
        ("kevna", vec!["kev".to_string(), "ke'a".to_string()]),
        ("kibro", vec!["kib".to_string()]),
        ("kicne", vec!["kic".to_string(), "ki'e".to_string()]),
        ("kicra", vec![]),
        ("kijno", vec!["kij".to_string()]),
        ("kilga", vec![]),
        ("kilto", vec!["ki'o".to_string()]),
        ("kinda", vec![]),
        ("kinfi", vec![]),
        ("kinli", vec!["kil".to_string()]),
        ("kinmu", vec![]),
        ("kinra", vec![]),
        ("kipsi", vec![]),
        ("kisto", vec!["kis".to_string()]),
        ("klaji", vec!["laj".to_string()]),
        ("klaku", vec!["kak".to_string()]),
        ("klama", vec!["kla".to_string()]),
        ("klani", vec!["lai".to_string()]),
        ("klaso", vec![]),
        ("klesi", vec!["kle".to_string(), "lei".to_string()]),
        ("kliki", vec![]),
        ("klina", vec!["kli".to_string()]),
        ("kliru", vec![]),
        ("kliti", vec!["kit".to_string()]),
        ("kloje", vec![]),
        ("klupe", vec!["lup".to_string(), "lu'e".to_string()]),
        ("kluza", vec!["luz".to_string()]),
        ("kobli", vec!["kob".to_string(), "ko'i".to_string()]),
        ("kogno", vec![]),
        ("kojna", vec!["koj".to_string(), "ko'a".to_string()]),
        ("kokso", vec![]),
        ("kolme", vec!["kol".to_string(), "ko'e".to_string()]),
        ("komcu", vec!["kom".to_string()]),
        ("konju", vec!["kon".to_string(), "ko'u".to_string()]),
        ("konve", vec![]),
        ("korbi", vec!["kor".to_string(), "koi".to_string()]),
        ("korcu", vec!["kro".to_string()]),
        ("korka", vec!["kok".to_string()]),
        ("korvo", vec![]),
        ("kosmu", vec![]),
        ("kosta", vec!["kos".to_string()]),
        ("krali", vec![]),
        ("kramu", vec![]),
        ("krasi", vec!["kra".to_string()]),
        ("krati", vec!["ka'i".to_string()]),
        ("krefu", vec!["ref".to_string(), "ke'u".to_string()]),
        ("krici", vec!["kri".to_string()]),
        ("krili", vec![]),
        ("krinu", vec!["rin".to_string(), "ki'u".to_string()]),
        ("krixa", vec!["kix".to_string(), "ki'a".to_string()]),
        ("kroke", vec![]),
        ("kroxo", vec![]),
        ("kruca", vec!["kuc".to_string()]),
        ("kruji", vec!["ruj".to_string()]),
        ("kruvi", vec!["ruv".to_string(), "kru".to_string()]),
        ("ku'a", vec!["kuz".to_string()]),
        ("kubli", vec!["kub".to_string()]),
        ("kucli", vec![]),
        ("kufra", vec!["kuf".to_string()]),
        ("kukru", vec![]),
        ("kukte", vec!["kuk".to_string()]),
        ("kulnu", vec!["klu".to_string()]),
        ("kumfa", vec!["kum".to_string(), "ku'a".to_string()]),
        ("kumte", vec![]),
        ("kunra", vec!["kun".to_string()]),
        ("kunti", vec!["kut".to_string()]),
        ("kurfa", vec!["kur".to_string()]),
        ("kurji", vec!["kuj".to_string(), "ku'i".to_string()]),
        ("kurki", vec![]),
        ("kurti", vec![]),
        ("kuspe", vec!["kup".to_string(), "ku'e".to_string()]),
        ("kusru", vec!["kus".to_string()]),
        ("labno", vec![]),
        ("lacni", vec![]),
        ("lacpu", vec!["lap".to_string(), "cpu".to_string()]),
        ("lacri", vec!["lac".to_string()]),
        ("ladru", vec!["lad".to_string()]),
        ("lafti", vec!["laf".to_string()]),
        ("lakne", vec!["la'e".to_string()]),
        ("lakse", vec!["lak".to_string()]),
        ("laldo", vec![]),
        ("lalxu", vec!["la'u".to_string()]),
        ("lamda", vec![]),
        ("lamdu", vec![]),
        ("lamji", vec!["lam".to_string(), "la'i".to_string()]),
        ("lanbi", vec![]),
        ("lanci", vec![]),
        ("landa", vec![]),
        ("lanka", vec![]),
        ("lanli", vec!["lal".to_string()]),
        ("lanme", vec!["lan".to_string()]),
        ("lanru", vec![]),
        ("lante", vec![]),
        ("lanxe", vec!["lax".to_string()]),
        ("lanzu", vec!["laz".to_string()]),
        ("larcu", vec!["lar".to_string()]),
        ("larva", vec![]),
        ("lasna", vec!["la'a".to_string()]),
        ("lastu", vec![]),
        ("latmo", vec!["la'o".to_string()]),
        ("latna", vec![]),
        ("laxte", vec![]),
        ("lazni", vec![]),
        ("lebna", vec!["leb".to_string(), "le'a".to_string()]),
        ("le'e", vec!["lem".to_string()]),
        ("lelxe", vec![]),
        ("lenga", vec![]),
        ("lengu", vec![]),
        ("lenjo", vec!["len".to_string(), "le'o".to_string()]),
        ("lenku", vec!["lek".to_string()]),
        ("lerci", vec!["lec".to_string()]),
        ("lerfu", vec!["ler".to_string(), "le'u".to_string()]),
        ("letci", vec![]),
        ("libjo", vec!["lib".to_string()]),
        ("lidne", vec!["li'e".to_string()]),
        ("lifri", vec!["lif".to_string(), "fri".to_string()]),
        ("ligma", vec![]),
        ("li'i", vec!["liz".to_string()]),
        ("lijda", vec!["jda".to_string()]),
        ("likse", vec![]),
        ("limfa", vec![]),
        ("limna", vec!["lim".to_string()]),
        ("lince", vec![]),
        ("lindi", vec!["lid".to_string()]),
        ("linga", vec![]),
        ("linji", vec!["lij".to_string(), "li'i".to_string()]),
        ("linme", vec![]),
        ("linsi", vec!["lin".to_string()]),
        ("linto", vec!["li'o".to_string()]),
        ("lisri", vec!["lis".to_string()]),
        ("liste", vec!["ste".to_string()]),
        ("litce", vec!["lic".to_string()]),
        ("litki", vec!["lik".to_string()]),
        ("litru", vec!["li'u".to_string()]),
        ("livga", vec![]),
        ("livla", vec!["lil".to_string()]),
        ("lo'e", vec!["lom".to_string()]),
        ("logji", vec!["loj".to_string()]),
        ("loglo", vec![]),
        ("lojbo", vec!["lob".to_string(), "jbo".to_string()]),
        ("lojgo", vec![]),
        ("lokra", vec![]),
        ("loldi", vec!["lol".to_string(), "loi".to_string()]),
        ("lorxu", vec!["lor".to_string(), "lo'u".to_string()]),
        ("losto", vec![]),
        ("lubma", vec![]),
        ("lubno", vec!["lu'o".to_string()]),
        ("lucpa", vec![]),
        ("lujvo", vec!["luv".to_string(), "jvo".to_string()]),
        ("luksi", vec!["luk".to_string()]),
        ("lumci", vec!["lum".to_string(), "lu'i".to_string()]),
        ("lunbe", vec!["lub".to_string()]),
        ("lungo", vec![]),
        ("lunra", vec!["lur".to_string()]),
        ("lunsa", vec!["lus".to_string()]),
        ("luska", vec![]),
        ("lusto", vec![]),
        ("mabla", vec!["mal".to_string()]),
        ("mabru", vec!["mab".to_string()]),
        ("macnu", vec!["cnu".to_string()]),
        ("majga", vec![]),
        ("majvu", vec![]),
        ("makcu", vec!["ma'u".to_string()]),
        ("makfa", vec!["maf".to_string()]),
        ("maksi", vec!["mak".to_string()]),
        ("malsi", vec!["mas".to_string()]),
        ("maltu", vec![]),
        ("malve", vec![]),
        ("mamta", vec!["mam".to_string()]),
        ("manci", vec!["mac".to_string()]),
        ("manfo", vec![]),
        ("mango", vec![]),
        ("manku", vec!["man".to_string()]),
        ("manri", vec!["mar".to_string()]),
        ("mansa", vec![]),
        ("manti", vec![]),
        ("manva", vec![]),
        ("mapku", vec!["map".to_string()]),
        ("mapni", vec![]),
        ("mapra", vec![]),
        ("mapti", vec!["mat".to_string()]),
        ("marbi", vec!["mra".to_string()]),
        ("marce", vec!["ma'e".to_string()]),
        ("marde", vec!["mad".to_string()]),
        ("margu", vec!["mag".to_string()]),
        ("marji", vec!["maj".to_string(), "mai".to_string()]),
        ("marna", vec![]),
        ("marxa", vec!["max".to_string()]),
        ("maska", vec![]),
        ("masno", vec!["sno".to_string()]),
        ("masti", vec!["ma'i".to_string()]),
        ("matci", vec![]),
        ("matli", vec![]),
        ("matne", vec![]),
        ("matra", vec![]),
        ("matxe", vec![]),
        ("mavji", vec!["mav".to_string()]),
        ("maxri", vec!["xri".to_string()]),
        ("mebri", vec!["meb".to_string()]),
        ("medzo", vec![]),
        ("megdo", vec!["meg".to_string()]),
        ("mei", vec!["mem".to_string(), "mei".to_string()]),
        ("mekso", vec!["mek".to_string(), "me'o".to_string()]),
        ("melbi", vec!["mel".to_string(), "mle".to_string()]),
        ("meljo", vec!["mej".to_string()]),
        ("melmi", vec![]),
        ("menli", vec!["men".to_string()]),
        ("menre", vec![]),
        ("mensi", vec!["mes".to_string(), "me'i".to_string()]),
        ("mentu", vec!["met".to_string(), "me'u".to_string()]),
        ("merko", vec!["mer".to_string()]),
        ("merli", vec!["mre".to_string()]),
        ("mespo", vec![]),
        ("metfo", vec![]),
        ("metro", vec![]),
        ("mexno", vec!["mex".to_string()]),
        ("mi", vec!["mib".to_string()]),
        ("midju", vec!["mij".to_string()]),
        ("mifra", vec!["mif".to_string()]),
        ("mikce", vec!["mic".to_string()]),
        ("mikri", vec!["mik".to_string()]),
        ("milti", vec!["mil".to_string()]),
        ("milxe", vec!["mli".to_string()]),
        ("mimta", vec![]),
        ("minde", vec!["mid".to_string(), "mi'e".to_string()]),
        ("minji", vec!["mi'i".to_string()]),
        ("minli", vec![]),
        ("minra", vec!["mir".to_string()]),
        ("mintu", vec!["mit".to_string(), "mi'u".to_string()]),
        ("mipri", vec!["mip".to_string()]),
        ("mirli", vec![]),
        ("misno", vec!["mis".to_string(), "mi'o".to_string()]),
        ("misro", vec![]),
        ("miste", vec![]),
        ("mitre", vec!["tre".to_string()]),
        ("mixre", vec!["mix".to_string(), "xre".to_string()]),
        ("mlana", vec!["mla".to_string()]),
        ("mlatu", vec!["lat".to_string()]),
        ("mleca", vec!["mec".to_string(), "me'a".to_string()]),
        ("mledi", vec!["led".to_string()]),
        ("mluni", vec!["lun".to_string()]),
        ("mo'a", vec!["mob".to_string()]),
        ("modju", vec![]),
        ("modzi", vec![]),
        ("mogle", vec![]),
        ("mo'i", vec!["mov".to_string()]),
        ("moi", vec!["mom".to_string(), "moi".to_string()]),
        ("mokca", vec!["moc".to_string()]),
        ("moklu", vec!["mol".to_string(), "mo'u".to_string()]),
        ("molki", vec!["mlo".to_string()]),
        ("molro", vec!["mo'o".to_string()]),
        ("morji", vec!["moj".to_string(), "mo'i".to_string()]),
        ("morko", vec!["mor".to_string()]),
        ("mormo", vec![]),
        ("morna", vec!["mon".to_string(), "mo'a".to_string()]),
        ("morsi", vec!["mro".to_string()]),
        ("mosra", vec!["mos".to_string()]),
        ("moxna", vec![]),
        ("mraji", vec![]),
        ("mrilu", vec!["mri".to_string()]),
        ("mruli", vec!["mru".to_string()]),
        ("mu", vec!["mum".to_string()]),
        ("mucti", vec!["mut".to_string()]),
        ("mudri", vec!["mud".to_string()]),
        ("mu'e", vec!["muf".to_string()]),
        ("mugle", vec![]),
        ("mukti", vec!["muk".to_string(), "mu'i".to_string()]),
        ("mulno", vec!["mul".to_string(), "mu'o".to_string()]),
        ("munje", vec!["muj".to_string(), "mu'e".to_string()]),
        ("mupli", vec!["mup".to_string()]),
        ("murse", vec![]),
        ("murta", vec!["mur".to_string(), "mu'a".to_string()]),
        ("muslo", vec!["mus".to_string()]),
        ("mutce", vec!["tce".to_string()]),
        ("muvdu", vec!["muv".to_string(), "mu'u".to_string()]),
        ("muzga", vec!["muz".to_string()]),
        ("na", vec!["nar".to_string()]),
        ("nabmi", vec!["nam".to_string()]),
        ("na'e", vec!["nal".to_string()]),
        ("nakni", vec!["nak".to_string()]),
        ("nalci", vec!["na'i".to_string()]),
        ("nalfi", vec![]),
        ("nalti", vec![]),
        ("namcu", vec!["nac".to_string(), "na'u".to_string()]),
        ("namra", vec![]),
        ("nanba", vec!["nab".to_string()]),
        ("nanca", vec!["na'a".to_string()]),
        ("nandu", vec!["nad".to_string()]),
        ("nanla", vec![]),
        ("nanmu", vec!["nau".to_string()]),
        ("nanvi", vec!["nav".to_string()]),
        ("narge", vec!["nag".to_string()]),
        ("narju", vec!["naj".to_string()]),
        ("natfe", vec!["naf".to_string(), "na'e".to_string()]),
        ("natmi", vec!["nat".to_string(), "nai".to_string()]),
        ("natsi", vec![]),
        ("navni", vec![]),
        ("naxle", vec!["nax".to_string(), "xle".to_string()]),
        ("nazbi", vec!["naz".to_string(), "zbi".to_string()]),
        ("nedlo", vec![]),
        ("nejni", vec!["nen".to_string()]),
        ("nelci", vec!["nel".to_string(), "nei".to_string()]),
        ("nenmu", vec![]),
        ("nenri", vec!["ner".to_string(), "ne'i".to_string()]),
        ("nerde", vec![]),
        ("ni", vec!["nil".to_string()]),
        ("nibli", vec!["nib".to_string(), "ni'i".to_string()]),
        ("nicfa", vec!["nif".to_string()]),
        ("niclu", vec![]),
        ("nicte", vec!["cte".to_string()]),
        ("nikle", vec!["nik".to_string()]),
        ("nilce", vec!["ni'e".to_string()]),
        ("nimre", vec![]),
        ("ninja", vec![]),
        ("ninmu", vec!["nim".to_string(), "ni'u".to_string()]),
        ("nirna", vec!["nir".to_string()]),
        ("nitcu", vec!["tcu".to_string()]),
        ("nivji", vec!["niv".to_string()]),
        ("nixli", vec!["nix".to_string(), "xli".to_string()]),
        ("no", vec!["non".to_string()]),
        ("nobli", vec!["nol".to_string(), "no'i".to_string()]),
        ("no'e", vec!["nor".to_string(), "no'e".to_string()]),
        ("nonka", vec!["nok".to_string()]),
        ("nonmu", vec![]),
        ("nordo", vec![]),
        ("norgo", vec![]),
        ("notci", vec!["not".to_string(), "noi".to_string()]),
        ("nu", vec!["nun".to_string()]),
        ("nudle", vec![]),
        ("nukni", vec!["nuk".to_string()]),
        ("nuktu", vec![]),
        ("nulpa", vec![]),
        ("numje", vec![]),
        ("nunmu", vec![]),
        ("nu'o", vec!["nu'o".to_string()]),
        ("nupre", vec!["nup".to_string(), "nu'e".to_string()]),
        ("nurma", vec!["num".to_string()]),
        ("nusna", vec![]),
        ("nutka", vec![]),
        ("nutko", vec![]),
        ("nutli", vec!["nul".to_string(), "nu'i".to_string()]),
        ("nuzba", vec!["nuz".to_string()]),
        ("nuzlo", vec![]),
        ("pa", vec!["pav".to_string()]),
        ("pacna", vec!["pa'a".to_string()]),
        ("pagbu", vec!["pag".to_string(), "pau".to_string()]),
        ("pagre", vec!["gre".to_string()]),
        ("pagzu", vec![]),
        ("pajni", vec!["pai".to_string()]),
        ("palci", vec!["pac".to_string()]),
        ("palku", vec!["pak".to_string()]),
        ("palma", vec![]),
        ("palne", vec![]),
        ("palpi", vec![]),
        ("palta", vec![]),
        ("pambe", vec![]),
        ("pamga", vec![]),
        ("panci", vec!["pan".to_string()]),
        ("pandi", vec!["pad".to_string()]),
        ("panje", vec![]),
        ("panka", vec![]),
        ("panlo", vec!["pa'o".to_string()]),
        ("panpi", vec!["pap".to_string()]),
        ("panra", vec![]),
        ("pante", vec!["pat".to_string()]),
        ("panzi", vec!["paz".to_string()]),
        ("papri", vec![]),
        ("parbi", vec!["pab".to_string()]),
        ("pardu", vec![]),
        ("parji", vec![]),
        ("paska", vec![]),
        ("pastu", vec!["pas".to_string()]),
        ("patfu", vec!["paf".to_string(), "pa'u".to_string()]),
        ("patlu", vec![]),
        ("patxu", vec!["pax".to_string()]),
        ("paxra", vec![]),
        ("paznu", vec![]),
        ("pe'a", vec!["pev".to_string()]),
        ("pegva", vec!["peg".to_string()]),
        ("pelji", vec!["ple".to_string()]),
        ("pelxu", vec!["pel".to_string()]),
        ("pemci", vec!["pem".to_string()]),
        ("penbi", vec!["peb".to_string()]),
        ("pencu", vec!["pec".to_string(), "pe'u".to_string()]),
        ("pendo", vec!["ped".to_string(), "pe'o".to_string()]),
        ("penka", vec![]),
        ("penki", vec![]),
        ("penmi", vec!["pen".to_string(), "pe'i".to_string()]),
        ("pensi", vec!["pes".to_string(), "pei".to_string()]),
        ("pentu", vec![]),
        ("pepsi", vec![]),
        ("perli", vec!["per".to_string()]),
        ("pesxu", vec!["pex".to_string()]),
        ("petso", vec!["pet".to_string()]),
        ("pevna", vec![]),
        ("pezli", vec!["pez".to_string()]),
        ("pi", vec!["piz".to_string()]),
        ("picti", vec!["pic".to_string()]),
        ("pijne", vec![]),
        ("pikci", vec![]),
        ("pikpi", vec![]),
        ("pikta", vec![]),
        ("pilda", vec![]),
        ("pilji", vec!["pi'i".to_string()]),
        ("pilka", vec!["pil".to_string(), "pi'a".to_string()]),
        ("pilno", vec!["pli".to_string()]),
        ("pimlu", vec!["pim".to_string(), "pi'u".to_string()]),
        ("pinca", vec![]),
        ("pindi", vec!["pid".to_string()]),
        ("pinfu", vec!["pif".to_string()]),
        ("Pingo", vec![]),
        ("pinji", vec![]),
        ("pinka", vec!["pik".to_string()]),
        ("pinsi", vec!["pis".to_string()]),
        ("pinta", vec!["pin".to_string()]),
        ("pinxe", vec!["pix".to_string()]),
        ("pipno", vec!["pi'o".to_string()]),
        ("pirxo", vec![]),
        ("pitsa", vec![]),
        ("pi'u", vec!["piv".to_string()]),
        ("pixra", vec!["pir".to_string(), "xra".to_string()]),
        ("plana", vec![]),
        ("platu", vec!["pla".to_string()]),
        ("pleji", vec!["lej".to_string(), "le'i".to_string()]),
        ("plibu", vec!["pib".to_string()]),
        ("plini", vec![]),
        ("plipe", vec!["pip".to_string(), "pi'e".to_string()]),
        ("plise", vec![]),
        ("plita", vec!["pit".to_string()]),
        ("plixa", vec!["lix".to_string()]),
        ("pluja", vec!["luj".to_string()]),
        ("pluka", vec!["puk".to_string(), "pu'a".to_string()]),
        ("pluna", vec![]),
        ("pluta", vec!["lut".to_string(), "lu'a".to_string()]),
        ("pocli", vec![]),
        ("polje", vec!["plo".to_string()]),
        ("polno", vec!["pol".to_string()]),
        ("ponjo", vec!["pon".to_string(), "po'o".to_string()]),
        ("ponse", vec!["pos".to_string(), "po'e".to_string()]),
        ("poplu", vec![]),
        ("porno", vec![]),
        ("porpi", vec!["pop".to_string(), "po'i".to_string()]),
        ("porsi", vec!["por".to_string(), "poi".to_string()]),
        ("porto", vec!["pot".to_string()]),
        ("prali", vec!["pal".to_string()]),
        ("prami", vec!["pam".to_string(), "pa'i".to_string()]),
        ("prane", vec!["pa'e".to_string()]),
        ("predi", vec![]),
        ("preja", vec!["pej".to_string(), "pe'a".to_string()]),
        ("premi", vec![]),
        ("prenu", vec!["pre".to_string()]),
        ("preri", vec![]),
        ("preti", vec!["ret".to_string(), "rei".to_string()]),
        ("prije", vec!["pij".to_string()]),
        ("prina", vec!["pri".to_string()]),
        ("pritu", vec![]),
        ("proga", vec!["pog".to_string()]),
        ("proji", vec![]),
        ("prosa", vec!["ros".to_string(), "ro'a".to_string()]),
        ("pruce", vec!["ruc".to_string(), "ru'e".to_string()]),
        ("pruni", vec!["pun".to_string()]),
        ("pruri", vec![]),
        ("pruxi", vec!["rux".to_string(), "ru'i".to_string()]),
        ("pu'i", vec!["pus".to_string()]),
        ("pulce", vec!["puc".to_string(), "pu'e".to_string()]),
        ("pulji", vec![]),
        ("pulni", vec![]),
        ("punji", vec!["puj".to_string(), "pu'i".to_string()]),
        ("punli", vec!["pul".to_string()]),
        ("pupsu", vec!["pup".to_string()]),
        ("purci", vec!["pur".to_string(), "pru".to_string()]),
        ("purdi", vec!["pud".to_string()]),
        ("purmo", vec!["pum".to_string(), "pu'o".to_string()]),
        ("purni", vec![]),
        ("pu'u", vec!["puv".to_string()]),
        ("puvza", vec![]),
        ("racli", vec![]),
        ("ractu", vec![]),
        ("radno", vec!["ra'o".to_string()]),
        ("rafsi", vec!["raf".to_string()]),
        ("ragbi", vec![]),
        ("ragve", vec!["rav".to_string()]),
        ("rakle", vec![]),
        ("rakso", vec![]),
        ("raktu", vec!["ra'u".to_string()]),
        ("ralci", vec!["rac".to_string()]),
        ("ralju", vec!["ral".to_string()]),
        ("ralte", vec!["ra'e".to_string()]),
        ("randa", vec!["rad".to_string()]),
        ("rango", vec!["rag".to_string()]),
        ("ranji", vec!["ra'i".to_string()]),
        ("ranlu", vec![]),
        ("ranmi", vec!["ram".to_string()]),
        ("ransu", vec![]),
        ("ranti", vec!["ran".to_string()]),
        ("ranxi", vec!["rax".to_string()]),
        ("rapli", vec!["rap".to_string()]),
        ("rarna", vec!["rar".to_string()]),
        ("ratcu", vec![]),
        ("ratma", vec![]),
        ("ratni", vec!["rat".to_string()]),
        ("re", vec!["rel".to_string()]),
        ("rebla", vec!["reb".to_string()]),
        ("rectu", vec!["rec".to_string(), "re'u".to_string()]),
        ("reksa", vec![]),
        ("rekto", vec![]),
        ("remna", vec!["rem".to_string(), "re'a".to_string()]),
        ("renro", vec!["rer".to_string(), "re'o".to_string()]),
        ("renvi", vec!["rev".to_string(), "re'i".to_string()]),
        ("respa", vec!["res".to_string()]),
        ("rexsa", vec!["rex".to_string()]),
        ("ribga", vec![]),
        ("ricfu", vec!["rif".to_string(), "cfu".to_string()]),
        ("rigni", vec!["rig".to_string()]),
        ("rijno", vec!["rij".to_string()]),
        ("rikro", vec![]),
        ("rilti", vec!["ril".to_string()]),
        ("rimni", vec!["rim".to_string()]),
        ("rinci", vec![]),
        ("rindo", vec![]),
        ("rinju", vec!["ri'u".to_string()]),
        ("rinka", vec!["rik".to_string(), "ri'a".to_string()]),
        ("rinsa", vec![]),
        ("ripto", vec![]),
        ("rirci", vec![]),
        ("rirli", vec![]),
        ("rirni", vec!["rir".to_string()]),
        ("rirxe", vec!["ri'e".to_string()]),
        ("rismi", vec!["ris".to_string()]),
        ("risna", vec![]),
        ("ritli", vec!["ri'i".to_string()]),
        ("rivbi", vec!["riv".to_string()]),
        ("ro", vec!["rol".to_string()]),
        ("roi", vec!["rom".to_string(), "roi".to_string()]),
        ("rokci", vec!["rok".to_string(), "ro'i".to_string()]),
        ("romge", vec!["rog".to_string()]),
        ("romlo", vec![]),
        ("ronci", vec!["roc".to_string()]),
        ("ronro", vec![]),
        ("ronsa", vec![]),
        ("ronte", vec![]),
        ("ronti", vec![]),
        ("ropno", vec!["ron".to_string(), "ro'o".to_string()]),
        ("rorci", vec!["ror".to_string()]),
        (
            "rotsu",
            vec!["rot".to_string(), "ro'u".to_string(), "tsu".to_string()]
        ),
        ("rozgu", vec!["roz".to_string(), "zgu".to_string()]),
        ("ruble", vec!["rub".to_string(), "ble".to_string()]),
        ("rucni", vec![]),
        ("rufsu", vec!["ruf".to_string()]),
        ("runme", vec!["rum".to_string()]),
        ("runta", vec![]),
        ("rupnu", vec!["rup".to_string(), "ru'u".to_string()]),
        ("rusko", vec!["ruk".to_string(), "ru'o".to_string()]),
        ("rutni", vec!["run".to_string()]),
        ("sabji", vec!["sab".to_string()]),
        ("sabnu", vec![]),
        ("sacki", vec![]),
        ("saclu", vec![]),
        ("sacni", vec![]),
        ("sadjo", vec!["djo".to_string()]),
        ("sakci", vec!["sak".to_string()]),
        ("sakli", vec!["sal".to_string()]),
        ("sakta", vec!["sat".to_string()]),
        ("salci", vec!["sla".to_string()]),
        ("salmo", vec![]),
        ("salni", vec![]),
        ("salpo", vec!["sa'o".to_string()]),
        ("salri", vec![]),
        ("salta", vec![]),
        ("samcu", vec![]),
        ("sampu", vec!["sap".to_string()]),
        ("sanbu", vec![]),
        ("sance", vec!["sna".to_string()]),
        ("sanga", vec!["sag".to_string(), "sa'a".to_string()]),
        ("sanji", vec!["saj".to_string()]),
        ("sanli", vec!["sa'i".to_string()]),
        ("sanmi", vec!["sai".to_string()]),
        ("sanra", vec![]),
        ("sanso", vec![]),
        ("santa", vec![]),
        ("sarcu", vec!["sa'u".to_string()]),
        ("sarji", vec!["sra".to_string()]),
        ("sarlu", vec![]),
        ("sarni", vec![]),
        ("sarxe", vec!["sax".to_string()]),
        ("saske", vec!["ske".to_string()]),
        ("satci", vec![]),
        ("satre", vec!["sa'e".to_string()]),
        ("savru", vec!["sav".to_string(), "vru".to_string()]),
        ("sazri", vec!["saz".to_string()]),
        ("se", vec!["sel".to_string()]),
        ("sefsi", vec![]),
        ("sefta", vec!["sfe".to_string()]),
        ("sekre", vec![]),
        ("selci", vec!["sle".to_string()]),
        ("selfu", vec!["sef".to_string(), "se'u".to_string()]),
        ("semto", vec!["sme".to_string()]),
        ("senci", vec!["sec".to_string()]),
        ("sengi", vec![]),
        ("senpi", vec!["sen".to_string()]),
        ("senta", vec!["set".to_string()]),
        ("senva", vec!["sev".to_string(), "sne".to_string()]),
        ("sepli", vec!["sep".to_string(), "sei".to_string()]),
        ("sepre", vec![]),
        ("serti", vec!["ser".to_string()]),
        ("sesre", vec![]),
        ("setca", vec!["se'a".to_string()]),
        ("sevzi", vec!["sez".to_string(), "se'i".to_string()]),
        ("sezni", vec![]),
        ("sfani", vec![]),
        ("sfasa", vec!["sfa".to_string()]),
        ("sfero", vec![]),
        ("sfite", vec!["sfi".to_string()]),
        ("sfofa", vec!["sfo".to_string()]),
        ("sfopu", vec!["fop".to_string(), "fo'u".to_string()]),
        ("sfubu", vec!["sub".to_string(), "su'u".to_string()]),
        ("sibli", vec![]),
        ("siclu", vec!["sil".to_string()]),
        ("sicni", vec!["si'i".to_string()]),
        ("sicpi", vec![]),
        ("sidbo", vec!["sib".to_string(), "si'o".to_string()]),
        ("sidju", vec!["dju".to_string()]),
        ("sigda", vec![]),
        ("sigja", vec!["sig".to_string()]),
        ("sigma", vec![]),
        ("sikta", vec![]),
        ("silja", vec![]),
        ("silka", vec!["sik".to_string()]),
        ("silna", vec![]),
        ("silru", vec![]),
        ("simlu", vec!["mlu".to_string()]),
        ("simsa", vec!["smi".to_string()]),
        ("simxu", vec!["sim".to_string(), "si'u".to_string()]),
        ("since", vec![]),
        ("sinma", vec!["si'a".to_string()]),
        ("sinso", vec![]),
        ("sinxa", vec!["sni".to_string()]),
        ("si'o", vec!["siz".to_string()]),
        ("sipna", vec!["sip".to_string()]),
        ("sirji", vec!["sir".to_string()]),
        ("sirxo", vec!["six".to_string()]),
        ("sisku", vec!["sis".to_string()]),
        ("sisti", vec!["sti".to_string()]),
        ("sitla", vec![]),
        ("sitna", vec!["sit".to_string()]),
        ("sivni", vec!["siv".to_string()]),
        ("sizgo", vec![]),
        ("skaci", vec![]),
        ("skami", vec!["sam".to_string()]),
        ("skano", vec![]),
        ("skapi", vec!["kap".to_string()]),
        ("skari", vec!["ska".to_string()]),
        ("skicu", vec!["ski".to_string()]),
        ("skifa", vec![]),
        ("skiji", vec!["sij".to_string()]),
        ("skina", vec!["kin".to_string()]),
        ("skori", vec!["sko".to_string()]),
        ("skoto", vec!["kot".to_string(), "ko'o".to_string()]),
        ("skuba", vec![]),
        ("skudi", vec![]),
        ("skuna", vec![]),
        ("skuro", vec!["ku'o".to_string()]),
        ("slabu", vec!["sau".to_string()]),
        ("slaka", vec![]),
        ("slami", vec![]),
        ("slanu", vec![]),
        ("slari", vec!["sar".to_string()]),
        ("slasi", vec!["las".to_string()]),
        ("sligu", vec!["lig".to_string()]),
        ("slilu", vec!["sli".to_string()]),
        ("sliri", vec![]),
        ("slovo", vec!["lov".to_string(), "lo'o".to_string()]),
        ("sluji", vec!["slu".to_string()]),
        ("sluni", vec![]),
        ("smacu", vec![]),
        ("smadi", vec![]),
        ("smaji", vec!["sma".to_string()]),
        ("smaka", vec![]),
        ("smani", vec![]),
        ("smela", vec![]),
        ("smoka", vec!["smo".to_string()]),
        ("smuci", vec!["muc".to_string()]),
        ("smuni", vec!["mun".to_string(), "smu".to_string()]),
        ("smusu", vec![]),
        ("snada", vec!["sad".to_string()]),
        ("snafu", vec![]),
        ("snanu", vec!["nan".to_string()]),
        ("snavi", vec![]),
        ("snidu", vec!["nid".to_string()]),
        ("sniju", vec![]),
        ("snime", vec!["si'e".to_string()]),
        ("snipa", vec!["nip".to_string()]),
        ("snuji", vec!["nuj".to_string()]),
        ("snura", vec!["nur".to_string(), "nu'a".to_string()]),
        ("snuti", vec!["nut".to_string()]),
        ("so", vec!["soz".to_string()]),
        ("so'a", vec!["soj".to_string()]),
        ("sobde", vec!["sob".to_string(), "so'e".to_string()]),
        ("socni", vec![]),
        ("sodna", vec![]),
        ("sodva", vec!["sod".to_string()]),
        ("so'e", vec!["sop".to_string()]),
        ("softo", vec!["sof".to_string()]),
        ("so'i", vec!["sor".to_string(), "so'i".to_string()]),
        ("solji", vec!["slo".to_string()]),
        ("solri", vec!["sol".to_string()]),
        ("sombo", vec!["som".to_string(), "so'o".to_string()]),
        ("sonci", vec!["son".to_string(), "soi".to_string()]),
        ("sondu", vec![]),
        ("so'o", vec!["sos".to_string()]),
        ("sorcu", vec!["soc".to_string(), "sro".to_string()]),
        ("sorgu", vec!["sog".to_string()]),
        ("sorni", vec![]),
        ("sorta", vec![]),
        ("so'u", vec!["sot".to_string()]),
        ("sovda", vec!["sov".to_string(), "so'a".to_string()]),
        ("spaji", vec!["paj".to_string()]),
        ("spali", vec![]),
        ("spano", vec!["san".to_string()]),
        ("spati", vec!["spa".to_string()]),
        ("speci", vec![]),
        ("speni", vec!["spe".to_string()]),
        ("spero", vec![]),
        ("spisa", vec!["spi".to_string()]),
        ("spita", vec![]),
        ("spofu", vec!["pof".to_string(), "po'u".to_string()]),
        ("spoja", vec!["poj".to_string(), "po'a".to_string()]),
        ("spuda", vec!["spu".to_string()]),
        ("spupi", vec![]),
        ("sputu", vec!["put".to_string(), "pu'u".to_string()]),
        ("sraji", vec!["raj".to_string()]),
        ("sraku", vec!["rak".to_string()]),
        ("sralo", vec![]),
        ("srana", vec!["ra'a".to_string()]),
        ("srasu", vec!["sas".to_string()]),
        ("srate", vec![]),
        ("srera", vec!["sre".to_string()]),
        ("srito", vec![]),
        ("sruma", vec!["ru'a".to_string()]),
        ("sruri", vec!["rur".to_string(), "sru".to_string()]),
        ("stace", vec!["sac".to_string()]),
        ("stagi", vec![]),
        ("staku", vec!["tak".to_string()]),
        ("stali", vec!["sta".to_string()]),
        ("stani", vec![]),
        ("stapa", vec!["tap".to_string()]),
        ("stasu", vec![]),
        ("stati", vec![]),
        ("steba", vec!["seb".to_string()]),
        ("steci", vec!["tec".to_string(), "te'i".to_string()]),
        ("stedu", vec!["sed".to_string()]),
        ("stela", vec!["tel".to_string()]),
        ("stero", vec!["te'o".to_string()]),
        ("stici", vec!["sic".to_string()]),
        ("stidi", vec!["sid".to_string(), "ti'i".to_string()]),
        ("stika", vec!["tik".to_string()]),
        ("stima", vec![]),
        ("stizu", vec!["tiz".to_string()]),
        ("stodi", vec!["sto".to_string()]),
        ("stori", vec![]),
        ("stuna", vec!["sun".to_string()]),
        ("stura", vec!["tur".to_string(), "su'a".to_string()]),
        ("stuzi", vec!["tuz".to_string(), "stu".to_string()]),
        ("sucta", vec!["suc".to_string()]),
        ("sudga", vec!["sud".to_string()]),
        ("su'e", vec!["sup".to_string(), "su'e".to_string()]),
        ("sufti", vec!["sfu".to_string()]),
        ("suksa", vec!["suk".to_string()]),
        ("sumji", vec!["suj".to_string()]),
        ("sumla", vec![]),
        ("sumne", vec![]),
        ("sumro", vec![]),
        ("sumti", vec!["sum".to_string(), "su'i".to_string()]),
        ("sunga", vec!["sug".to_string()]),
        ("sunla", vec!["sul".to_string()]),
        ("su'o", vec!["suz".to_string(), "su'o".to_string()]),
        ("supso", vec!["sus".to_string()]),
        ("surla", vec!["sur".to_string()]),
        ("sutra", vec!["sut".to_string()]),
        ("su'u", vec!["suv".to_string()]),
        ("ta", vec!["taz".to_string()]),
        ("tabno", vec!["tab".to_string()]),
        ("tabra", vec![]),
        ("tadji", vec![]),
        ("tadni", vec!["tad".to_string()]),
        ("tagji", vec!["tag".to_string()]),
        ("takni", vec![]),
        ("taksi", vec![]),
        ("talko", vec![]),
        ("talsa", vec!["tal".to_string()]),
        ("tamca", vec![]),
        ("tamji", vec!["taj".to_string()]),
        ("tamle", vec![]),
        ("tamne", vec![]),
        ("tanbo", vec!["ta'o".to_string()]),
        ("tance", vec!["tac".to_string()]),
        ("tanjo", vec![]),
        ("tanko", vec![]),
        ("tanru", vec!["tau".to_string()]),
        ("tansi", vec!["tas".to_string()]),
        ("tanxe", vec!["tax".to_string(), "ta'e".to_string()]),
        ("tapla", vec![]),
        ("tarbi", vec![]),
        ("tarci", vec!["tar".to_string()]),
        ("tarla", vec![]),
        ("tarmi", vec!["tam".to_string(), "tai".to_string()]),
        ("tarti", vec!["tra".to_string()]),
        ("taske", vec![]),
        ("tasmi", vec![]),
        ("tasta", vec![]),
        ("tatpi", vec!["ta'i".to_string()]),
        ("tatru", vec!["tat".to_string()]),
        ("tavla", vec!["tav".to_string(), "ta'a".to_string()]),
        ("taxfu", vec!["taf".to_string(), "ta'u".to_string()]),
        ("tcaci", vec!["cac".to_string()]),
        ("tcadu", vec!["tca".to_string()]),
        ("tcana", vec![]),
        ("tcati", vec![]),
        ("tcaxe", vec![]),
        ("tcema", vec![]),
        ("tcemi", vec![]),
        ("tcena", vec!["ten".to_string()]),
        ("tcesa", vec![]),
        ("tcese", vec![]),
        ("tceta", vec![]),
        ("tcica", vec!["tic".to_string()]),
        ("tcidu", vec!["tid".to_string()]),
        ("tcika", vec![]),
        ("tcila", vec!["til".to_string()]),
        ("tcima", vec!["tim".to_string(), "ti'a".to_string()]),
        ("tcini", vec![]),
        ("tcipi", vec![]),
        ("tcita", vec![]),
        ("tcivi", vec![]),
        ("tcobi", vec![]),
        ("tcone", vec![]),
        ("tcuti", vec![]),
        ("te", vec!["ter".to_string()]),
        ("tekla", vec![]),
        ("temci", vec!["tem".to_string(), "tei".to_string()]),
        ("temse", vec![]),
        ("tende", vec!["te'e".to_string()]),
        ("tendo", vec![]),
        ("tenfa", vec!["tef".to_string()]),
        ("tengu", vec!["teg".to_string(), "te'u".to_string()]),
        ("terdi", vec!["ted".to_string()]),
        ("terki", vec![]),
        ("terpa", vec!["tep".to_string(), "te'a".to_string()]),
        ("terto", vec!["tet".to_string()]),
        ("tezda", vec![]),
        ("ti", vec!["tif".to_string()]),
        ("tifri", vec![]),
        ("tigni", vec!["tig".to_string()]),
        ("tigra", vec![]),
        ("tikpa", vec!["tip".to_string()]),
        ("tilju", vec!["tij".to_string()]),
        ("timno", vec![]),
        ("tinbe", vec!["tib".to_string()]),
        ("tinci", vec![]),
        ("tinri", vec![]),
        ("tinsa", vec![]),
        ("tinto", vec![]),
        ("tipre", vec![]),
        ("tirna", vec!["tin".to_string()]),
        ("tirse", vec!["tir".to_string()]),
        ("tirxu", vec![]),
        ("tisna", vec!["tis".to_string()]),
        ("titla", vec!["tit".to_string()]),
        ("tivni", vec!["tiv".to_string()]),
        ("tixnu", vec!["tix".to_string(), "ti'u".to_string()]),
        ("tizva", vec![]),
        ("to'e", vec!["tol".to_string(), "to'e".to_string()]),
        ("toknu", vec!["tok".to_string()]),
        ("toldi", vec!["tod".to_string()]),
        ("tolfa", vec![]),
        ("tonga", vec!["tog".to_string(), "to'a".to_string()]),
        ("tordu", vec!["tor".to_string(), "to'u".to_string()]),
        ("torni", vec!["ton".to_string(), "to'i".to_string()]),
        ("torso", vec![]),
        ("torta", vec![]),
        ("tovla", vec![]),
        ("traji", vec!["rai".to_string()]),
        ("trano", vec![]),
        ("trati", vec![]),
        ("trene", vec!["ren".to_string(), "re'e".to_string()]),
        ("tricu", vec!["ric".to_string()]),
        ("triga", vec![]),
        ("trina", vec!["tri".to_string()]),
        ("trixe", vec!["rix".to_string(), "ti'e".to_string()]),
        ("troci", vec!["toc".to_string(), "toi".to_string()]),
        ("tsaba", vec![]),
        ("tsali", vec!["tsa".to_string()]),
        ("tsani", vec!["tan".to_string()]),
        ("tsapi", vec![]),
        ("tsida", vec![]),
        ("tsiju", vec!["tsi".to_string()]),
        ("tsina", vec!["sin".to_string()]),
        ("tsuku", vec![]),
        ("tsuli", vec![]),
        ("tu", vec!["tuf".to_string()]),
        ("tubnu", vec!["tu'u".to_string()]),
        ("tubra", vec![]),
        ("tugni", vec!["tug".to_string(), "tu'i".to_string()]),
        ("tujli", vec!["tuj".to_string()]),
        ("tulnu", vec![]),
        ("tumla", vec!["tum".to_string(), "tu'a".to_string()]),
        ("tunba", vec!["tub".to_string()]),
        ("tunka", vec!["tuk".to_string()]),
        ("tunlo", vec!["tul".to_string(), "tu'o".to_string()]),
        ("tunta", vec!["tun".to_string()]),
        ("tuple", vec!["tup".to_string(), "tu'e".to_string()]),
        ("turko", vec![]),
        ("turni", vec!["tru".to_string()]),
        ("tutci", vec!["tci".to_string()]),
        ("tutle", vec![]),
        ("tutra", vec!["tut".to_string()]),
        ("va", vec!["vaz".to_string()]),
        ("vacri", vec!["var".to_string()]),
        ("vajni", vec!["vaj".to_string(), "vai".to_string()]),
        ("valfa", vec!["vaf".to_string()]),
        ("valsi", vec!["val".to_string(), "vla".to_string()]),
        ("vamgu", vec![]),
        ("vamji", vec!["vam".to_string(), "va'i".to_string()]),
        ("vamtu", vec!["vat".to_string()]),
        ("vanbi", vec!["vab".to_string()]),
        ("vanci", vec!["vac".to_string()]),
        ("vanju", vec!["van".to_string()]),
        ("vasru", vec!["vas".to_string(), "vau".to_string()]),
        ("vasxu", vec!["vax".to_string(), "va'u".to_string()]),
        ("ve", vec!["vel".to_string()]),
        ("vecnu", vec!["ven".to_string(), "ve'u".to_string()]),
        ("vedli", vec!["ve'i".to_string()]),
        ("ve'e", vec!["ve'e".to_string()]),
        ("venfu", vec!["vef".to_string()]),
        ("vensa", vec!["ves".to_string()]),
        ("vente", vec![]),
        ("vepre", vec![]),
        ("verba", vec!["ver".to_string(), "ve'a".to_string()]),
        ("verjo", vec![]),
        ("vi", vec!["viz".to_string()]),
        ("vibna", vec!["vib".to_string()]),
        ("vidni", vec![]),
        ("vidru", vec!["vir".to_string()]),
        ("vidvi", vec![]),
        ("vifne", vec!["vif".to_string()]),
        ("vikmi", vec!["vim".to_string(), "vi'i".to_string()]),
        ("viknu", vec!["vik".to_string()]),
        ("vilco", vec![]),
        ("vimcu", vec!["vic".to_string(), "vi'u".to_string()]),
        ("vindu", vec!["vid".to_string()]),
        ("vinji", vec!["vij".to_string()]),
        ("vinpa", vec![]),
        ("vinta", vec![]),
        ("vipsi", vec!["vip".to_string()]),
        ("virme", vec![]),
        ("virnu", vec!["vri".to_string()]),
        ("viska", vec!["vis".to_string(), "vi'a".to_string()]),
        ("vitci", vec!["vit".to_string()]),
        ("vitke", vec!["vi'e".to_string()]),
        ("vitno", vec!["vi'o".to_string()]),
        ("vlagi", vec!["lag".to_string()]),
        ("vlile", vec!["vil".to_string()]),
        ("vlina", vec![]),
        ("vlipa", vec!["vli".to_string()]),
        ("vo", vec!["von".to_string()]),
        ("vofli", vec!["vol".to_string(), "voi".to_string()]),
        ("voksa", vec!["vok".to_string(), "vo'a".to_string()]),
        ("volve", vec![]),
        ("vorme", vec!["vor".to_string(), "vro".to_string()]),
        ("vraga", vec!["vra".to_string()]),
        ("vreji", vec!["rej".to_string(), "vei".to_string()]),
        ("vreta", vec!["vre".to_string()]),
        ("vrici", vec![]),
        ("vrude", vec!["vud".to_string(), "vu'e".to_string()]),
        ("vrusi", vec!["vus".to_string(), "vu'i".to_string()]),
        ("vu", vec!["vuz".to_string()]),
        ("vubla", vec!["vul".to_string()]),
        ("vujnu", vec!["vuj".to_string(), "vu'u".to_string()]),
        ("vukna", vec![]),
        ("vukro", vec!["vur".to_string(), "vu'o".to_string()]),
        ("xa", vec!["xav".to_string()]),
        ("xabju", vec!["xa'u".to_string()]),
        ("xadba", vec!["xab".to_string()]),
        ("xadji", vec![]),
        ("xadni", vec!["xad".to_string()]),
        ("xagji", vec![]),
        ("xagri", vec![]),
        ("xajmi", vec!["xam".to_string()]),
        ("xaksu", vec!["xak".to_string()]),
        ("xakto", vec![]),
        ("xalbo", vec![]),
        ("xalda", vec![]),
        ("xalka", vec!["xal".to_string()]),
        ("xalni", vec![]),
        ("xamgu", vec!["xag".to_string(), "xau".to_string()]),
        ("xampo", vec!["xap".to_string(), "xa'o".to_string()]),
        ("xamsi", vec!["xas".to_string()]),
        ("xance", vec!["xan".to_string(), "xa'e".to_string()]),
        ("xango", vec![]),
        ("xanka", vec![]),
        ("xanmi", vec![]),
        ("xanri", vec!["xar".to_string()]),
        ("xansa", vec![]),
        ("xanto", vec![]),
        ("xarci", vec!["xac".to_string(), "xa'i".to_string()]),
        ("xarju", vec!["xaj".to_string()]),
        ("xarnu", vec![]),
        ("xasli", vec![]),
        ("xasne", vec![]),
        ("xatra", vec!["xa'a".to_string()]),
        ("xatsi", vec!["xat".to_string()]),
        ("xavli", vec![]),
        ("xaxre", vec![]),
        ("xazdo", vec!["xaz".to_string(), "zdo".to_string()]),
        ("xe", vec!["xel".to_string()]),
        ("xebni", vec!["xen".to_string(), "xei".to_string()]),
        ("xebro", vec!["xeb".to_string(), "bro".to_string()]),
        ("xecto", vec!["xet".to_string(), "cto".to_string()]),
        ("xedja", vec!["xej".to_string(), "xe'a".to_string()]),
        ("xekce", vec![]),
        ("xekri", vec!["xek".to_string(), "xe'i".to_string()]),
        ("xelso", vec!["xes".to_string()]),
        ("xendo", vec!["xed".to_string(), "xe'o".to_string()]),
        ("xenru", vec!["xer".to_string(), "xe'u".to_string()]),
        ("xerno", vec![]),
        ("xexso", vec!["xex".to_string()]),
        ("xigzo", vec!["xig".to_string()]),
        ("xijra", vec![]),
        ("xilva", vec!["xiv".to_string()]),
        ("ximta", vec![]),
        ("xindo", vec!["xin".to_string()]),
        ("xinmo", vec!["xim".to_string()]),
        ("xinro", vec![]),
        ("xinsi", vec![]),
        ("xirma", vec!["xir".to_string(), "xi'a".to_string()]),
        ("xislu", vec!["xil".to_string(), "xi'u".to_string()]),
        ("xispo", vec!["xip".to_string()]),
        ("xixli", vec![]),
        ("xixnu", vec![]),
        ("xlali", vec!["xla".to_string()]),
        ("xlobi", vec![]),
        ("xlura", vec!["xlu".to_string()]),
        ("xonba", vec![]),
        ("xorbo", vec![]),
        ("xorlo", vec![]),
        ("xotli", vec!["xol".to_string(), "xoi".to_string()]),
        ("xrabo", vec!["rab".to_string()]),
        ("xrani", vec!["xai".to_string()]),
        ("xriso", vec!["xis".to_string(), "xi'o".to_string()]),
        ("xroma", vec![]),
        ("xrotu", vec!["xro".to_string()]),
        ("xruba", vec!["xub".to_string()]),
        ("xruki", vec!["xuk".to_string()]),
        ("xrula", vec!["rul".to_string()]),
        ("xruti", vec!["xru".to_string()]),
        ("xudvu", vec!["xu'u".to_string()]),
        ("xukmi", vec!["xum".to_string(), "xu'i".to_string()]),
        ("xulta", vec!["xut".to_string()]),
        ("xumbe", vec![]),
        ("xunre", vec!["xun".to_string(), "xu'e".to_string()]),
        ("xurdo", vec!["xur".to_string(), "xu'o".to_string()]),
        ("xusra", vec!["xus".to_string(), "xu'a".to_string()]),
        ("xutla", vec!["xul".to_string()]),
        ("zabna", vec!["zan".to_string(), "za'a".to_string()]),
        ("za'i", vec!["zaz".to_string()]),
        ("zajba", vec!["zaj".to_string()]),
        ("zalvi", vec!["zal".to_string()]),
        ("zandi", vec!["zad".to_string()]),
        ("zanru", vec!["zar".to_string(), "zau".to_string()]),
        ("zanxi", vec![]),
        ("za'o", vec!["za'o".to_string()]),
        ("zarci", vec!["zac".to_string(), "zai".to_string()]),
        ("zargu", vec!["zag".to_string(), "za'u".to_string()]),
        ("zasni", vec!["zas".to_string()]),
        ("zasti", vec!["zat".to_string(), "za'i".to_string()]),
        ("zbabu", vec!["bab".to_string()]),
        ("zbani", vec![]),
        ("zbasu", vec!["zba".to_string()]),
        ("zbepi", vec!["zbe".to_string()]),
        ("zdani", vec!["zda".to_string()]),
        ("zdile", vec!["zdi".to_string()]),
        ("ze", vec!["zel".to_string()]),
        ("ze'e", vec!["ze'e".to_string()]),
        ("zejvo", vec![]),
        ("zekri", vec!["zer".to_string(), "zei".to_string()]),
        ("zenba", vec!["zen".to_string(), "ze'a".to_string()]),
        ("ze'o", vec!["zev".to_string(), "ze'o".to_string()]),
        ("zepti", vec!["zep".to_string()]),
        ("zergi", vec![]),
        ("zetro", vec!["zet".to_string()]),
        ("zevla", vec!["zve".to_string()]),
        ("zgadi", vec![]),
        ("zgana", vec!["zga".to_string()]),
        ("zgike", vec!["gi'e".to_string(), "zgi".to_string()]),
        ("zguro", vec![]),
        ("zifre", vec!["zif".to_string(), "zi'e".to_string()]),
        ("zinki", vec!["zin".to_string(), "zi'i".to_string()]),
        ("zi'o", vec!["zil".to_string()]),
        ("zirli", vec![]),
        ("zirpu", vec!["zir".to_string(), "zi'u".to_string()]),
        ("zivle", vec!["ziv".to_string(), "vle".to_string()]),
        ("zmadu", vec!["zma".to_string(), "mau".to_string()]),
        ("zmase", vec![]),
        ("zmico", vec!["zic".to_string()]),
        ("zmiku", vec!["zmi".to_string()]),
        ("zo'a", vec!["zon".to_string(), "zo'a".to_string()]),
        ("zo'i", vec!["zor".to_string(), "zo'i".to_string()]),
        ("zorti", vec![]),
        ("zozno", vec![]),
        ("zubra", vec![]),
        ("zucna", vec!["zuc".to_string(), "zu'a".to_string()]),
        ("zukte", vec!["zuk".to_string(), "zu'e".to_string()]),
        ("zulna", vec![]),
        ("zumri", vec!["zmu".to_string()]),
        ("zungi", vec!["zug".to_string()]),
        ("zunle", vec!["zul".to_string()]),
        ("zunti", vec!["zun".to_string(), "zu'i".to_string()]),
        ("zu'o", vec!["zum".to_string()]),
        ("zurja", vec!["zuj".to_string()]),
        ("zutse", vec!["zut".to_string(), "tse".to_string()]),
        ("zvati", vec!["zva".to_string()]),
        ("zviki", vec!["zvi".to_string()]),
        ("zvuzu", vec![]),
        ("xi", vec!["xix".to_string()]),
        ("zai'e", vec!["zam".to_string()]),
        ("gelse", vec!["ges".to_string(), "ge'e".to_string()]),
        ("je'ebzi", vec!["jeb".to_string()]),
        ("mu'umgu", vec!["mug".to_string()]),
        ("va'arga", vec!["va'a".to_string()]),
        ("co'ai", vec!["cox".to_string()]),
        ("dau", vec!["duv".to_string()]),
        ("fei", vec!["fel".to_string()]),
        ("ga'ei", vec!["gel".to_string()]),
        ("gai", vec!["gam".to_string()]),
        ("jau", vec!["juz".to_string()]),
        ("ke'ai", vec!["ked".to_string()]),
        ("ke'ei", vec!["keb".to_string()]),
        ("ke'ei'a", vec!["kex".to_string()]),
        ("kei'ei", vec!["kim".to_string()]),
        ("lai'ai", vec!["lav".to_string()]),
        ("sa", vec!["saf".to_string()]),
        ("si", vec!["sif".to_string()]),
        ("su", vec!["suf".to_string()]),
        ("su'ei", vec!["sem".to_string()]),
        ("tau'u", vec!["tux".to_string()]),
        ("to'ai", vec!["toz".to_string()]),
        ("vai", vec!["vav".to_string()]),
        ("vo'a", vec!["vob".to_string()]),
        ("vo'ai", vec!["voz".to_string()]),
        ("xei", vec!["xem".to_string()]),
        ("xo'ai", vec!["xoz".to_string()]),
        ("xo'ei", vec!["xon".to_string()]),
        ("zei'e", vec!["zex".to_string()]),
        ("zei'o", vec!["zes".to_string()]),
    ]);
}
